/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.AIHubDiscoverData;
import java.io.IOException;

/**
 * Get the response body when the strategy recommendation is successful.
 */
public class AIHubDiscoverSuccessResponse {
    public static final String SERIALIZED_NAME_CODE = "code";
    @SerializedName(SERIALIZED_NAME_CODE)
    private Integer code;

    public static final String SERIALIZED_NAME_MESSAGE = "message";
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    private String message;

    public static final String SERIALIZED_NAME_DATA = "data";
    @SerializedName(SERIALIZED_NAME_DATA)
    private AIHubDiscoverData data;

    public static final String SERIALIZED_NAME_TRACE_ID = "trace_id";
    @SerializedName(SERIALIZED_NAME_TRACE_ID)
    private String traceId;


    public AIHubDiscoverSuccessResponse code(Integer code) {
        
        this.code = code;
        return this;
    }

     /**
     * Get code
     * @return code
    **/
    public Integer getCode() {
        return code;
    }


    public void setCode(Integer code) {
        this.code = code;
    }

    public AIHubDiscoverSuccessResponse message(String message) {
        
        this.message = message;
        return this;
    }

     /**
     * Get message
     * @return message
    **/
    public String getMessage() {
        return message;
    }


    public void setMessage(String message) {
        this.message = message;
    }

    public AIHubDiscoverSuccessResponse data(AIHubDiscoverData data) {
        
        this.data = data;
        return this;
    }

     /**
     * Get data
     * @return data
    **/
    public AIHubDiscoverData getData() {
        return data;
    }


    public void setData(AIHubDiscoverData data) {
        this.data = data;
    }

    public AIHubDiscoverSuccessResponse traceId(String traceId) {
        
        this.traceId = traceId;
        return this;
    }

     /**
     * Get traceId
     * @return traceId
    **/
    public String getTraceId() {
        return traceId;
    }


    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AIHubDiscoverSuccessResponse aiHubDiscoverSuccessResponse = (AIHubDiscoverSuccessResponse) o;
        return Objects.equals(this.code, aiHubDiscoverSuccessResponse.code) &&
                Objects.equals(this.message, aiHubDiscoverSuccessResponse.message) &&
                Objects.equals(this.data, aiHubDiscoverSuccessResponse.data) &&
                Objects.equals(this.traceId, aiHubDiscoverSuccessResponse.traceId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, message, data, traceId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AIHubDiscoverSuccessResponse {\n");
        sb.append("      code: ").append(toIndentedString(code)).append("\n");
        sb.append("      message: ").append(toIndentedString(message)).append("\n");
        sb.append("      data: ").append(toIndentedString(data)).append("\n");
        sb.append("      traceId: ").append(toIndentedString(traceId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

