/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Strategy detail position info; fields returned depend on strategy type.
 */
public class AIHubPortfolioPosition {
    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;

    public static final String SERIALIZED_NAME_ENTRY_PRICE = "entry_price";
    @SerializedName(SERIALIZED_NAME_ENTRY_PRICE)
    private String entryPrice;

    public static final String SERIALIZED_NAME_QUOTE_AMOUNT = "quote_amount";
    @SerializedName(SERIALIZED_NAME_QUOTE_AMOUNT)
    private String quoteAmount;

    public static final String SERIALIZED_NAME_POSITION_VALUE = "position_value";
    @SerializedName(SERIALIZED_NAME_POSITION_VALUE)
    private String positionValue;

    public static final String SERIALIZED_NAME_MARGIN = "margin";
    @SerializedName(SERIALIZED_NAME_MARGIN)
    private String margin;

    public static final String SERIALIZED_NAME_SIDE = "side";
    @SerializedName(SERIALIZED_NAME_SIDE)
    private String side;


    public AIHubPortfolioPosition amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * Get amount
     * @return amount
    **/
    @javax.annotation.Nullable
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }

    public AIHubPortfolioPosition entryPrice(String entryPrice) {
        
        this.entryPrice = entryPrice;
        return this;
    }

     /**
     * Get entryPrice
     * @return entryPrice
    **/
    @javax.annotation.Nullable
    public String getEntryPrice() {
        return entryPrice;
    }


    public void setEntryPrice(String entryPrice) {
        this.entryPrice = entryPrice;
    }

    public AIHubPortfolioPosition quoteAmount(String quoteAmount) {
        
        this.quoteAmount = quoteAmount;
        return this;
    }

     /**
     * Get quoteAmount
     * @return quoteAmount
    **/
    @javax.annotation.Nullable
    public String getQuoteAmount() {
        return quoteAmount;
    }


    public void setQuoteAmount(String quoteAmount) {
        this.quoteAmount = quoteAmount;
    }

    public AIHubPortfolioPosition positionValue(String positionValue) {
        
        this.positionValue = positionValue;
        return this;
    }

     /**
     * Get positionValue
     * @return positionValue
    **/
    @javax.annotation.Nullable
    public String getPositionValue() {
        return positionValue;
    }


    public void setPositionValue(String positionValue) {
        this.positionValue = positionValue;
    }

    public AIHubPortfolioPosition margin(String margin) {
        
        this.margin = margin;
        return this;
    }

     /**
     * Get margin
     * @return margin
    **/
    @javax.annotation.Nullable
    public String getMargin() {
        return margin;
    }


    public void setMargin(String margin) {
        this.margin = margin;
    }

    public AIHubPortfolioPosition side(String side) {
        
        this.side = side;
        return this;
    }

     /**
     * Get side
     * @return side
    **/
    @javax.annotation.Nullable
    public String getSide() {
        return side;
    }


    public void setSide(String side) {
        this.side = side;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AIHubPortfolioPosition aiHubPortfolioPosition = (AIHubPortfolioPosition) o;
        return Objects.equals(this.amount, aiHubPortfolioPosition.amount) &&
                Objects.equals(this.entryPrice, aiHubPortfolioPosition.entryPrice) &&
                Objects.equals(this.quoteAmount, aiHubPortfolioPosition.quoteAmount) &&
                Objects.equals(this.positionValue, aiHubPortfolioPosition.positionValue) &&
                Objects.equals(this.margin, aiHubPortfolioPosition.margin) &&
                Objects.equals(this.side, aiHubPortfolioPosition.side);
    }

    @Override
    public int hashCode() {
        return Objects.hash(amount, entryPrice, quoteAmount, positionValue, margin, side);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AIHubPortfolioPosition {\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("      entryPrice: ").append(toIndentedString(entryPrice)).append("\n");
        sb.append("      quoteAmount: ").append(toIndentedString(quoteAmount)).append("\n");
        sb.append("      positionValue: ").append(toIndentedString(positionValue)).append("\n");
        sb.append("      margin: ").append(toIndentedString(margin)).append("\n");
        sb.append("      side: ").append(toIndentedString(side)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

