/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.StrategyType;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 单条策略推荐信息。
 */
public class AIHubRecommendation {
    public static final String SERIALIZED_NAME_RECOMMENDATION_ID = "recommendation_id";
    @SerializedName(SERIALIZED_NAME_RECOMMENDATION_ID)
    private String recommendationId;

    public static final String SERIALIZED_NAME_MARKET = "market";
    @SerializedName(SERIALIZED_NAME_MARKET)
    private String market;

    public static final String SERIALIZED_NAME_STRATEGY_TYPE = "strategy_type";
    @SerializedName(SERIALIZED_NAME_STRATEGY_TYPE)
    private StrategyType strategyType;

    public static final String SERIALIZED_NAME_STRATEGY_NAME = "strategy_name";
    @SerializedName(SERIALIZED_NAME_STRATEGY_NAME)
    private String strategyName;

    public static final String SERIALIZED_NAME_BACKTEST_APR = "backtest_apr";
    @SerializedName(SERIALIZED_NAME_BACKTEST_APR)
    private String backtestApr;

    public static final String SERIALIZED_NAME_MAX_DRAWDOWN = "max_drawdown";
    @SerializedName(SERIALIZED_NAME_MAX_DRAWDOWN)
    private String maxDrawdown;

    public static final String SERIALIZED_NAME_SUMMARY = "summary";
    @SerializedName(SERIALIZED_NAME_SUMMARY)
    private String summary;

    public static final String SERIALIZED_NAME_STRATEGY_PARAMS_PREVIEW = "strategy_params_preview";
    @SerializedName(SERIALIZED_NAME_STRATEGY_PARAMS_PREVIEW)
    private Map<String, String> strategyParamsPreview = null;


    public AIHubRecommendation recommendationId(String recommendationId) {
        
        this.recommendationId = recommendationId;
        return this;
    }

     /**
     * Get recommendationId
     * @return recommendationId
    **/
    public String getRecommendationId() {
        return recommendationId;
    }


    public void setRecommendationId(String recommendationId) {
        this.recommendationId = recommendationId;
    }

    public AIHubRecommendation market(String market) {
        
        this.market = market;
        return this;
    }

     /**
     * Get market
     * @return market
    **/
    public String getMarket() {
        return market;
    }


    public void setMarket(String market) {
        this.market = market;
    }

    public AIHubRecommendation strategyType(StrategyType strategyType) {
        
        this.strategyType = strategyType;
        return this;
    }

     /**
     * Get strategyType
     * @return strategyType
    **/
    public StrategyType getStrategyType() {
        return strategyType;
    }


    public void setStrategyType(StrategyType strategyType) {
        this.strategyType = strategyType;
    }

    public AIHubRecommendation strategyName(String strategyName) {
        
        this.strategyName = strategyName;
        return this;
    }

     /**
     * Get strategyName
     * @return strategyName
    **/
    public String getStrategyName() {
        return strategyName;
    }


    public void setStrategyName(String strategyName) {
        this.strategyName = strategyName;
    }

    public AIHubRecommendation backtestApr(String backtestApr) {
        
        this.backtestApr = backtestApr;
        return this;
    }

     /**
     * Get backtestApr
     * @return backtestApr
    **/
    @javax.annotation.Nullable
    public String getBacktestApr() {
        return backtestApr;
    }


    public void setBacktestApr(String backtestApr) {
        this.backtestApr = backtestApr;
    }

    public AIHubRecommendation maxDrawdown(String maxDrawdown) {
        
        this.maxDrawdown = maxDrawdown;
        return this;
    }

     /**
     * Get maxDrawdown
     * @return maxDrawdown
    **/
    @javax.annotation.Nullable
    public String getMaxDrawdown() {
        return maxDrawdown;
    }


    public void setMaxDrawdown(String maxDrawdown) {
        this.maxDrawdown = maxDrawdown;
    }

    public AIHubRecommendation summary(String summary) {
        
        this.summary = summary;
        return this;
    }

     /**
     * Get summary
     * @return summary
    **/
    public String getSummary() {
        return summary;
    }


    public void setSummary(String summary) {
        this.summary = summary;
    }

    public AIHubRecommendation strategyParamsPreview(Map<String, String> strategyParamsPreview) {
        
        this.strategyParamsPreview = strategyParamsPreview;
        return this;
    }

    public AIHubRecommendation putStrategyParamsPreviewItem(String key, String strategyParamsPreviewItem) {
        if (this.strategyParamsPreview == null) {
            this.strategyParamsPreview = new HashMap<>();
        }
        this.strategyParamsPreview.put(key, strategyParamsPreviewItem);
        return this;
    }

     /**
     * 推荐参数预览；按策略类型动态变化
     * @return strategyParamsPreview
    **/
    @javax.annotation.Nullable
    public Map<String, String> getStrategyParamsPreview() {
        return strategyParamsPreview;
    }


    public void setStrategyParamsPreview(Map<String, String> strategyParamsPreview) {
        this.strategyParamsPreview = strategyParamsPreview;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AIHubRecommendation aiHubRecommendation = (AIHubRecommendation) o;
        return Objects.equals(this.recommendationId, aiHubRecommendation.recommendationId) &&
                Objects.equals(this.market, aiHubRecommendation.market) &&
                Objects.equals(this.strategyType, aiHubRecommendation.strategyType) &&
                Objects.equals(this.strategyName, aiHubRecommendation.strategyName) &&
                Objects.equals(this.backtestApr, aiHubRecommendation.backtestApr) &&
                Objects.equals(this.maxDrawdown, aiHubRecommendation.maxDrawdown) &&
                Objects.equals(this.summary, aiHubRecommendation.summary) &&
                Objects.equals(this.strategyParamsPreview, aiHubRecommendation.strategyParamsPreview);
    }

    @Override
    public int hashCode() {
        return Objects.hash(recommendationId, market, strategyType, strategyName, backtestApr, maxDrawdown, summary, strategyParamsPreview);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AIHubRecommendation {\n");
        sb.append("      recommendationId: ").append(toIndentedString(recommendationId)).append("\n");
        sb.append("      market: ").append(toIndentedString(market)).append("\n");
        sb.append("      strategyType: ").append(toIndentedString(strategyType)).append("\n");
        sb.append("      strategyName: ").append(toIndentedString(strategyName)).append("\n");
        sb.append("      backtestApr: ").append(toIndentedString(backtestApr)).append("\n");
        sb.append("      maxDrawdown: ").append(toIndentedString(maxDrawdown)).append("\n");
        sb.append("      summary: ").append(toIndentedString(summary)).append("\n");
        sb.append("      strategyParamsPreview: ").append(toIndentedString(strategyParamsPreview)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

