/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.ApiResponseExSkillClaimRewardRespData;
import java.io.IOException;

/**
 * 领取任务奖励响应
 */
public class ApiResponseExSkillClaimRewardResp {
    public static final String SERIALIZED_NAME_CODE = "code";
    @SerializedName(SERIALIZED_NAME_CODE)
    private Integer code;

    public static final String SERIALIZED_NAME_LABEL = "label";
    @SerializedName(SERIALIZED_NAME_LABEL)
    private String label;

    public static final String SERIALIZED_NAME_MESSAGE = "message";
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    private String message;

    public static final String SERIALIZED_NAME_DATA = "data";
    @SerializedName(SERIALIZED_NAME_DATA)
    private ApiResponseExSkillClaimRewardRespData data;

    public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
    @SerializedName(SERIALIZED_NAME_TIMESTAMP)
    private Long timestamp;


    public ApiResponseExSkillClaimRewardResp code(Integer code) {
        
        this.code = code;
        return this;
    }

     /**
     * 业务错误码，0 表示成功
     * @return code
    **/
    @javax.annotation.Nullable
    public Integer getCode() {
        return code;
    }


    public void setCode(Integer code) {
        this.code = code;
    }

    public ApiResponseExSkillClaimRewardResp label(String label) {
        
        this.label = label;
        return this;
    }

     /**
     * Error identifier code. Empty string on success, machine-readable error label on error
     * @return label
    **/
    @javax.annotation.Nullable
    public String getLabel() {
        return label;
    }


    public void setLabel(String label) {
        this.label = label;
    }

    public ApiResponseExSkillClaimRewardResp message(String message) {
        
        this.message = message;
        return this;
    }

     /**
     * Error description
     * @return message
    **/
    @javax.annotation.Nullable
    public String getMessage() {
        return message;
    }


    public void setMessage(String message) {
        this.message = message;
    }

    public ApiResponseExSkillClaimRewardResp data(ApiResponseExSkillClaimRewardRespData data) {
        
        this.data = data;
        return this;
    }

     /**
     * Get data
     * @return data
    **/
    @javax.annotation.Nullable
    public ApiResponseExSkillClaimRewardRespData getData() {
        return data;
    }


    public void setData(ApiResponseExSkillClaimRewardRespData data) {
        this.data = data;
    }

    public ApiResponseExSkillClaimRewardResp timestamp(Long timestamp) {
        
        this.timestamp = timestamp;
        return this;
    }

     /**
     * Server timestamp (milliseconds)
     * @return timestamp
    **/
    @javax.annotation.Nullable
    public Long getTimestamp() {
        return timestamp;
    }


    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApiResponseExSkillClaimRewardResp apiResponseExSkillClaimRewardResp = (ApiResponseExSkillClaimRewardResp) o;
        return Objects.equals(this.code, apiResponseExSkillClaimRewardResp.code) &&
                Objects.equals(this.label, apiResponseExSkillClaimRewardResp.label) &&
                Objects.equals(this.message, apiResponseExSkillClaimRewardResp.message) &&
                Objects.equals(this.data, apiResponseExSkillClaimRewardResp.data) &&
                Objects.equals(this.timestamp, apiResponseExSkillClaimRewardResp.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, label, message, data, timestamp);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ApiResponseExSkillClaimRewardResp {\n");
        sb.append("      code: ").append(toIndentedString(code)).append("\n");
        sb.append("      label: ").append(toIndentedString(label)).append("\n");
        sb.append("      message: ").append(toIndentedString(message)).append("\n");
        sb.append("      data: ").append(toIndentedString(data)).append("\n");
        sb.append("      timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

