/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.AutoInvestPlanRecordItem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PlanExecutionRecordPaginatedResponse
 */
public class AutoInvestPlanRecordsResp {
    public static final String SERIALIZED_NAME_PAGE = "page";
    @SerializedName(SERIALIZED_NAME_PAGE)
    private Long page;

    public static final String SERIALIZED_NAME_PAGE_SIZE = "page_size";
    @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
    private Long pageSize;

    public static final String SERIALIZED_NAME_TOTAL_PAGE = "total_page";
    @SerializedName(SERIALIZED_NAME_TOTAL_PAGE)
    private Long totalPage;

    public static final String SERIALIZED_NAME_TOTAL = "total";
    @SerializedName(SERIALIZED_NAME_TOTAL)
    private Long total;

    public static final String SERIALIZED_NAME_LIST = "list";
    @SerializedName(SERIALIZED_NAME_LIST)
    private List<AutoInvestPlanRecordItem> list = new ArrayList<>();


    public AutoInvestPlanRecordsResp page(Long page) {
        
        this.page = page;
        return this;
    }

     /**
     * page number
     * @return page
    **/
    public Long getPage() {
        return page;
    }


    public void setPage(Long page) {
        this.page = page;
    }

    public AutoInvestPlanRecordsResp pageSize(Long pageSize) {
        
        this.pageSize = pageSize;
        return this;
    }

     /**
     * Items per page
     * @return pageSize
    **/
    public Long getPageSize() {
        return pageSize;
    }


    public void setPageSize(Long pageSize) {
        this.pageSize = pageSize;
    }

    public AutoInvestPlanRecordsResp totalPage(Long totalPage) {
        
        this.totalPage = totalPage;
        return this;
    }

     /**
     * TotalPage number
     * @return totalPage
    **/
    public Long getTotalPage() {
        return totalPage;
    }


    public void setTotalPage(Long totalPage) {
        this.totalPage = totalPage;
    }

    public AutoInvestPlanRecordsResp total(Long total) {
        
        this.total = total;
        return this;
    }

     /**
     * Total entries
     * @return total
    **/
    public Long getTotal() {
        return total;
    }


    public void setTotal(Long total) {
        this.total = total;
    }

    public AutoInvestPlanRecordsResp list(List<AutoInvestPlanRecordItem> list) {
        
        this.list = list;
        return this;
    }

    public AutoInvestPlanRecordsResp addListItem(AutoInvestPlanRecordItem listItem) {
        this.list.add(listItem);
        return this;
    }

     /**
     * Get list
     * @return list
    **/
    public List<AutoInvestPlanRecordItem> getList() {
        return list;
    }


    public void setList(List<AutoInvestPlanRecordItem> list) {
        this.list = list;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AutoInvestPlanRecordsResp autoInvestPlanRecordsResp = (AutoInvestPlanRecordsResp) o;
        return Objects.equals(this.page, autoInvestPlanRecordsResp.page) &&
                Objects.equals(this.pageSize, autoInvestPlanRecordsResp.pageSize) &&
                Objects.equals(this.totalPage, autoInvestPlanRecordsResp.totalPage) &&
                Objects.equals(this.total, autoInvestPlanRecordsResp.total) &&
                Objects.equals(this.list, autoInvestPlanRecordsResp.list);
    }

    @Override
    public int hashCode() {
        return Objects.hash(page, pageSize, totalPage, total, list);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AutoInvestPlanRecordsResp {\n");
        sb.append("      page: ").append(toIndentedString(page)).append("\n");
        sb.append("      pageSize: ").append(toIndentedString(pageSize)).append("\n");
        sb.append("      totalPage: ").append(toIndentedString(totalPage)).append("\n");
        sb.append("      total: ").append(toIndentedString(total)).append("\n");
        sb.append("      list: ").append(toIndentedString(list)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

