/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * AutoInvestPlanCreateItems
 */
public class AutoInvestPlanCreateItems {
    public static final String SERIALIZED_NAME_ASSET = "asset";
    @SerializedName(SERIALIZED_NAME_ASSET)
    private String asset;

    public static final String SERIALIZED_NAME_RATIO = "ratio";
    @SerializedName(SERIALIZED_NAME_RATIO)
    private String ratio;


    public AutoInvestPlanCreateItems asset(String asset) {
        
        this.asset = asset;
        return this;
    }

     /**
     * Investment currency, e.g., BTC; Must be enabled and market exists; Cannot be repeated within the same plan
     * @return asset
    **/
    public String getAsset() {
        return asset;
    }


    public void setAsset(String asset) {
        this.asset = asset;
    }

    public AutoInvestPlanCreateItems ratio(String ratio) {
        
        this.ratio = ratio;
        return this;
    }

     /**
     * The proportion of this currency in the portfolio，The sum of all items&#39; ratios must be 100
     * @return ratio
    **/
    public String getRatio() {
        return ratio;
    }


    public void setRatio(String ratio) {
        this.ratio = ratio;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AutoInvestPlanCreateItems autoInvestPlanCreateItems = (AutoInvestPlanCreateItems) o;
        return Objects.equals(this.asset, autoInvestPlanCreateItems.asset) &&
                Objects.equals(this.ratio, autoInvestPlanCreateItems.ratio);
    }

    @Override
    public int hashCode() {
        return Objects.hash(asset, ratio);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AutoInvestPlanCreateItems {\n");
        sb.append("      asset: ").append(toIndentedString(asset)).append("\n");
        sb.append("      ratio: ").append(toIndentedString(ratio)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

