/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Create auto invest planResponse
 */
public class AutoInvestPlanCreateResp {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Long id;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;

    public static final String SERIALIZED_NAME_MONEY = "money";
    @SerializedName(SERIALIZED_NAME_MONEY)
    private String money;

    public static final String SERIALIZED_NAME_NEXT_TIME = "next_time";
    @SerializedName(SERIALIZED_NAME_NEXT_TIME)
    private Long nextTime;

    public static final String SERIALIZED_NAME_PERIOD_TYPE = "period_type";
    @SerializedName(SERIALIZED_NAME_PERIOD_TYPE)
    private String periodType;

    public static final String SERIALIZED_NAME_PERIOD_DAY = "period_day";
    @SerializedName(SERIALIZED_NAME_PERIOD_DAY)
    private Long periodDay;

    public static final String SERIALIZED_NAME_PERIOD_HOUR = "period_hour";
    @SerializedName(SERIALIZED_NAME_PERIOD_HOUR)
    private Long periodHour;

    public static final String SERIALIZED_NAME_FUND_FLOW = "fund_flow";
    @SerializedName(SERIALIZED_NAME_FUND_FLOW)
    private String fundFlow;

    public static final String SERIALIZED_NAME_FUND_SOURCE = "fund_source";
    @SerializedName(SERIALIZED_NAME_FUND_SOURCE)
    private String fundSource;


    public AutoInvestPlanCreateResp id(Long id) {
        
        this.id = id;
        return this;
    }

     /**
     * Plan ID
     * @return id
    **/
    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }

    public AutoInvestPlanCreateResp amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * Per PeriodAuto InvestAmount
     * @return amount
    **/
    @javax.annotation.Nullable
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }

    public AutoInvestPlanCreateResp money(String money) {
        
        this.money = money;
        return this;
    }

     /**
     * Quote currency
     * @return money
    **/
    @javax.annotation.Nullable
    public String getMoney() {
        return money;
    }


    public void setMoney(String money) {
        this.money = money;
    }

    public AutoInvestPlanCreateResp nextTime(Long nextTime) {
        
        this.nextTime = nextTime;
        return this;
    }

     /**
     * Next execution time
     * @return nextTime
    **/
    @javax.annotation.Nullable
    public Long getNextTime() {
        return nextTime;
    }


    public void setNextTime(Long nextTime) {
        this.nextTime = nextTime;
    }

    public AutoInvestPlanCreateResp periodType(String periodType) {
        
        this.periodType = periodType;
        return this;
    }

     /**
     * Cycle type
     * @return periodType
    **/
    @javax.annotation.Nullable
    public String getPeriodType() {
        return periodType;
    }


    public void setPeriodType(String periodType) {
        this.periodType = periodType;
    }

    public AutoInvestPlanCreateResp periodDay(Long periodDay) {
        
        this.periodDay = periodDay;
        return this;
    }

     /**
     * Cycle day
     * @return periodDay
    **/
    @javax.annotation.Nullable
    public Long getPeriodDay() {
        return periodDay;
    }


    public void setPeriodDay(Long periodDay) {
        this.periodDay = periodDay;
    }

    public AutoInvestPlanCreateResp periodHour(Long periodHour) {
        
        this.periodHour = periodHour;
        return this;
    }

     /**
     * CycleHours
     * @return periodHour
    **/
    @javax.annotation.Nullable
    public Long getPeriodHour() {
        return periodHour;
    }


    public void setPeriodHour(Long periodHour) {
        this.periodHour = periodHour;
    }

    public AutoInvestPlanCreateResp fundFlow(String fundFlow) {
        
        this.fundFlow = fundFlow;
        return this;
    }

     /**
     * Fund Flow Direction
     * @return fundFlow
    **/
    @javax.annotation.Nullable
    public String getFundFlow() {
        return fundFlow;
    }


    public void setFundFlow(String fundFlow) {
        this.fundFlow = fundFlow;
    }

    public AutoInvestPlanCreateResp fundSource(String fundSource) {
        
        this.fundSource = fundSource;
        return this;
    }

     /**
     * Fund source
     * @return fundSource
    **/
    @javax.annotation.Nullable
    public String getFundSource() {
        return fundSource;
    }


    public void setFundSource(String fundSource) {
        this.fundSource = fundSource;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AutoInvestPlanCreateResp autoInvestPlanCreateResp = (AutoInvestPlanCreateResp) o;
        return Objects.equals(this.id, autoInvestPlanCreateResp.id) &&
                Objects.equals(this.amount, autoInvestPlanCreateResp.amount) &&
                Objects.equals(this.money, autoInvestPlanCreateResp.money) &&
                Objects.equals(this.nextTime, autoInvestPlanCreateResp.nextTime) &&
                Objects.equals(this.periodType, autoInvestPlanCreateResp.periodType) &&
                Objects.equals(this.periodDay, autoInvestPlanCreateResp.periodDay) &&
                Objects.equals(this.periodHour, autoInvestPlanCreateResp.periodHour) &&
                Objects.equals(this.fundFlow, autoInvestPlanCreateResp.fundFlow) &&
                Objects.equals(this.fundSource, autoInvestPlanCreateResp.fundSource);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, amount, money, nextTime, periodType, periodDay, periodHour, fundFlow, fundSource);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AutoInvestPlanCreateResp {\n");
        sb.append("      id: ").append(toIndentedString(id)).append("\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("      money: ").append(toIndentedString(money)).append("\n");
        sb.append("      nextTime: ").append(toIndentedString(nextTime)).append("\n");
        sb.append("      periodType: ").append(toIndentedString(periodType)).append("\n");
        sb.append("      periodDay: ").append(toIndentedString(periodDay)).append("\n");
        sb.append("      periodHour: ").append(toIndentedString(periodHour)).append("\n");
        sb.append("      fundFlow: ").append(toIndentedString(fundFlow)).append("\n");
        sb.append("      fundSource: ").append(toIndentedString(fundSource)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

