/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Chase order detail or list item
 */
public class ChaseOrder {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private String id;

    public static final String SERIALIZED_NAME_USER = "user";
    @SerializedName(SERIALIZED_NAME_USER)
    private String user;

    public static final String SERIALIZED_NAME_CONTRACT = "contract";
    @SerializedName(SERIALIZED_NAME_CONTRACT)
    private String contract;

    public static final String SERIALIZED_NAME_SETTLE = "settle";
    @SerializedName(SERIALIZED_NAME_SETTLE)
    private String settle;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;

    public static final String SERIALIZED_NAME_PRICE_LIMIT = "price_limit";
    @SerializedName(SERIALIZED_NAME_PRICE_LIMIT)
    private String priceLimit;

    public static final String SERIALIZED_NAME_REDUCE_ONLY = "reduce_only";
    @SerializedName(SERIALIZED_NAME_REDUCE_ONLY)
    private Boolean reduceOnly;

    public static final String SERIALIZED_NAME_TEXT = "text";
    @SerializedName(SERIALIZED_NAME_TEXT)
    private String text;

    public static final String SERIALIZED_NAME_CREATE_TIME = "create_time";
    @SerializedName(SERIALIZED_NAME_CREATE_TIME)
    private Long createTime;

    public static final String SERIALIZED_NAME_FINISH_TIME = "finish_time";
    @SerializedName(SERIALIZED_NAME_FINISH_TIME)
    private Long finishTime;

    public static final String SERIALIZED_NAME_ORIGINAL_STATUS = "original_status";
    @SerializedName(SERIALIZED_NAME_ORIGINAL_STATUS)
    private Integer originalStatus;

    public static final String SERIALIZED_NAME_STATUS = "status";
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;

    public static final String SERIALIZED_NAME_REASON = "reason";
    @SerializedName(SERIALIZED_NAME_REASON)
    private String reason;

    public static final String SERIALIZED_NAME_FILL_AMOUNT = "fill_amount";
    @SerializedName(SERIALIZED_NAME_FILL_AMOUNT)
    private String fillAmount;

    public static final String SERIALIZED_NAME_AVERAGE_FILL_PRICE = "average_fill_price";
    @SerializedName(SERIALIZED_NAME_AVERAGE_FILL_PRICE)
    private String averageFillPrice;

    public static final String SERIALIZED_NAME_SUBORDER_ID = "suborder_id";
    @SerializedName(SERIALIZED_NAME_SUBORDER_ID)
    private String suborderId;

    public static final String SERIALIZED_NAME_IS_DUAL_MODE = "is_dual_mode";
    @SerializedName(SERIALIZED_NAME_IS_DUAL_MODE)
    private Boolean isDualMode;

    public static final String SERIALIZED_NAME_SIDE_LABEL = "side_label";
    @SerializedName(SERIALIZED_NAME_SIDE_LABEL)
    private String sideLabel;

    public static final String SERIALIZED_NAME_POSITION_SIDE_OUTPUT = "position_side_output";
    @SerializedName(SERIALIZED_NAME_POSITION_SIDE_OUTPUT)
    private String positionSideOutput;

    public static final String SERIALIZED_NAME_CHASE_PRICE = "chase_price";
    @SerializedName(SERIALIZED_NAME_CHASE_PRICE)
    private String chasePrice;

    public static final String SERIALIZED_NAME_INTERVAL_SEC = "interval_sec";
    @SerializedName(SERIALIZED_NAME_INTERVAL_SEC)
    private Integer intervalSec;

    public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
    @SerializedName(SERIALIZED_NAME_UPDATED_AT)
    private Long updatedAt;

    public static final String SERIALIZED_NAME_SUBORDER_PRICE = "suborder_price";
    @SerializedName(SERIALIZED_NAME_SUBORDER_PRICE)
    private String suborderPrice;

    public static final String SERIALIZED_NAME_SUBORDER_ONGOING = "suborder_ongoing";
    @SerializedName(SERIALIZED_NAME_SUBORDER_ONGOING)
    private Boolean suborderOngoing;

    public static final String SERIALIZED_NAME_SUBORDER_FINISH_AS = "suborder_finish_as";
    @SerializedName(SERIALIZED_NAME_SUBORDER_FINISH_AS)
    private String suborderFinishAs;

    public static final String SERIALIZED_NAME_PRICE_TYPE = "price_type";
    @SerializedName(SERIALIZED_NAME_PRICE_TYPE)
    private Integer priceType;

    public static final String SERIALIZED_NAME_PRICE_GAP_TYPE = "price_gap_type";
    @SerializedName(SERIALIZED_NAME_PRICE_GAP_TYPE)
    private String priceGapType;

    public static final String SERIALIZED_NAME_PRICE_GAP_VALUE = "price_gap_value";
    @SerializedName(SERIALIZED_NAME_PRICE_GAP_VALUE)
    private String priceGapValue;

    public static final String SERIALIZED_NAME_STATUS_CODE = "status_code";
    @SerializedName(SERIALIZED_NAME_STATUS_CODE)
    private String statusCode;

    public static final String SERIALIZED_NAME_CREATE_TIME_PRECISE = "create_time_precise";
    @SerializedName(SERIALIZED_NAME_CREATE_TIME_PRECISE)
    private String createTimePrecise;

    public static final String SERIALIZED_NAME_FINISH_TIME_PRECISE = "finish_time_precise";
    @SerializedName(SERIALIZED_NAME_FINISH_TIME_PRECISE)
    private String finishTimePrecise;

    public static final String SERIALIZED_NAME_POS_MARGIN_MODE = "pos_margin_mode";
    @SerializedName(SERIALIZED_NAME_POS_MARGIN_MODE)
    private String posMarginMode;

    public static final String SERIALIZED_NAME_POSITION_MODE = "position_mode";
    @SerializedName(SERIALIZED_NAME_POSITION_MODE)
    private String positionMode;

    public static final String SERIALIZED_NAME_LEVERAGE = "leverage";
    @SerializedName(SERIALIZED_NAME_LEVERAGE)
    private String leverage;

    public static final String SERIALIZED_NAME_ERROR_LABEL = "error_label";
    @SerializedName(SERIALIZED_NAME_ERROR_LABEL)
    private String errorLabel;


    public ChaseOrder id(String id) {
        
        this.id = id;
        return this;
    }

     /**
     * Get id
     * @return id
    **/
    @javax.annotation.Nullable
    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id;
    }

    public ChaseOrder user(String user) {
        
        this.user = user;
        return this;
    }

     /**
     * Get user
     * @return user
    **/
    @javax.annotation.Nullable
    public String getUser() {
        return user;
    }


    public void setUser(String user) {
        this.user = user;
    }

    public ChaseOrder contract(String contract) {
        
        this.contract = contract;
        return this;
    }

     /**
     * Get contract
     * @return contract
    **/
    @javax.annotation.Nullable
    public String getContract() {
        return contract;
    }


    public void setContract(String contract) {
        this.contract = contract;
    }

    public ChaseOrder settle(String settle) {
        
        this.settle = settle;
        return this;
    }

     /**
     * Get settle
     * @return settle
    **/
    @javax.annotation.Nullable
    public String getSettle() {
        return settle;
    }


    public void setSettle(String settle) {
        this.settle = settle;
    }

    public ChaseOrder amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * Total size in contracts; positive for buy, negative for sell
     * @return amount
    **/
    @javax.annotation.Nullable
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }

    public ChaseOrder priceLimit(String priceLimit) {
        
        this.priceLimit = priceLimit;
        return this;
    }

     /**
     * Get priceLimit
     * @return priceLimit
    **/
    @javax.annotation.Nullable
    public String getPriceLimit() {
        return priceLimit;
    }


    public void setPriceLimit(String priceLimit) {
        this.priceLimit = priceLimit;
    }

    public ChaseOrder reduceOnly(Boolean reduceOnly) {
        
        this.reduceOnly = reduceOnly;
        return this;
    }

     /**
     * Get reduceOnly
     * @return reduceOnly
    **/
    @javax.annotation.Nullable
    public Boolean getReduceOnly() {
        return reduceOnly;
    }


    public void setReduceOnly(Boolean reduceOnly) {
        this.reduceOnly = reduceOnly;
    }

    public ChaseOrder text(String text) {
        
        this.text = text;
        return this;
    }

     /**
     * Get text
     * @return text
    **/
    @javax.annotation.Nullable
    public String getText() {
        return text;
    }


    public void setText(String text) {
        this.text = text;
    }

    public ChaseOrder createTime(Long createTime) {
        
        this.createTime = createTime;
        return this;
    }

     /**
     * Get createTime
     * @return createTime
    **/
    @javax.annotation.Nullable
    public Long getCreateTime() {
        return createTime;
    }


    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public ChaseOrder finishTime(Long finishTime) {
        
        this.finishTime = finishTime;
        return this;
    }

     /**
     * Get finishTime
     * @return finishTime
    **/
    @javax.annotation.Nullable
    public Long getFinishTime() {
        return finishTime;
    }


    public void setFinishTime(Long finishTime) {
        this.finishTime = finishTime;
    }

    public ChaseOrder originalStatus(Integer originalStatus) {
        
        this.originalStatus = originalStatus;
        return this;
    }

     /**
     * Raw status enum
     * @return originalStatus
    **/
    @javax.annotation.Nullable
    public Integer getOriginalStatus() {
        return originalStatus;
    }


    public void setOriginalStatus(Integer originalStatus) {
        this.originalStatus = originalStatus;
    }

    public ChaseOrder status(String status) {
        
        this.status = status;
        return this;
    }

     /**
     * Simplified status, e.g. open / finished
     * @return status
    **/
    @javax.annotation.Nullable
    public String getStatus() {
        return status;
    }


    public void setStatus(String status) {
        this.status = status;
    }

    public ChaseOrder reason(String reason) {
        
        this.reason = reason;
        return this;
    }

     /**
     * Get reason
     * @return reason
    **/
    @javax.annotation.Nullable
    public String getReason() {
        return reason;
    }


    public void setReason(String reason) {
        this.reason = reason;
    }

    public ChaseOrder fillAmount(String fillAmount) {
        
        this.fillAmount = fillAmount;
        return this;
    }

     /**
     * Get fillAmount
     * @return fillAmount
    **/
    @javax.annotation.Nullable
    public String getFillAmount() {
        return fillAmount;
    }


    public void setFillAmount(String fillAmount) {
        this.fillAmount = fillAmount;
    }

    public ChaseOrder averageFillPrice(String averageFillPrice) {
        
        this.averageFillPrice = averageFillPrice;
        return this;
    }

     /**
     * Get averageFillPrice
     * @return averageFillPrice
    **/
    @javax.annotation.Nullable
    public String getAverageFillPrice() {
        return averageFillPrice;
    }


    public void setAverageFillPrice(String averageFillPrice) {
        this.averageFillPrice = averageFillPrice;
    }

    public ChaseOrder suborderId(String suborderId) {
        
        this.suborderId = suborderId;
        return this;
    }

     /**
     * Get suborderId
     * @return suborderId
    **/
    @javax.annotation.Nullable
    public String getSuborderId() {
        return suborderId;
    }


    public void setSuborderId(String suborderId) {
        this.suborderId = suborderId;
    }

    public ChaseOrder isDualMode(Boolean isDualMode) {
        
        this.isDualMode = isDualMode;
        return this;
    }

     /**
     * Get isDualMode
     * @return isDualMode
    **/
    @javax.annotation.Nullable
    public Boolean getIsDualMode() {
        return isDualMode;
    }


    public void setIsDualMode(Boolean isDualMode) {
        this.isDualMode = isDualMode;
    }

    public ChaseOrder sideLabel(String sideLabel) {
        
        this.sideLabel = sideLabel;
        return this;
    }

     /**
     * Get sideLabel
     * @return sideLabel
    **/
    @javax.annotation.Nullable
    public String getSideLabel() {
        return sideLabel;
    }


    public void setSideLabel(String sideLabel) {
        this.sideLabel = sideLabel;
    }

    public ChaseOrder positionSideOutput(String positionSideOutput) {
        
        this.positionSideOutput = positionSideOutput;
        return this;
    }

     /**
     * Get positionSideOutput
     * @return positionSideOutput
    **/
    @javax.annotation.Nullable
    public String getPositionSideOutput() {
        return positionSideOutput;
    }


    public void setPositionSideOutput(String positionSideOutput) {
        this.positionSideOutput = positionSideOutput;
    }

    public ChaseOrder chasePrice(String chasePrice) {
        
        this.chasePrice = chasePrice;
        return this;
    }

     /**
     * Get chasePrice
     * @return chasePrice
    **/
    @javax.annotation.Nullable
    public String getChasePrice() {
        return chasePrice;
    }


    public void setChasePrice(String chasePrice) {
        this.chasePrice = chasePrice;
    }

    public ChaseOrder intervalSec(Integer intervalSec) {
        
        this.intervalSec = intervalSec;
        return this;
    }

     /**
     * Get intervalSec
     * @return intervalSec
    **/
    @javax.annotation.Nullable
    public Integer getIntervalSec() {
        return intervalSec;
    }


    public void setIntervalSec(Integer intervalSec) {
        this.intervalSec = intervalSec;
    }

    public ChaseOrder updatedAt(Long updatedAt) {
        
        this.updatedAt = updatedAt;
        return this;
    }

     /**
     * Get updatedAt
     * @return updatedAt
    **/
    @javax.annotation.Nullable
    public Long getUpdatedAt() {
        return updatedAt;
    }


    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    public ChaseOrder suborderPrice(String suborderPrice) {
        
        this.suborderPrice = suborderPrice;
        return this;
    }

     /**
     * Get suborderPrice
     * @return suborderPrice
    **/
    @javax.annotation.Nullable
    public String getSuborderPrice() {
        return suborderPrice;
    }


    public void setSuborderPrice(String suborderPrice) {
        this.suborderPrice = suborderPrice;
    }

    public ChaseOrder suborderOngoing(Boolean suborderOngoing) {
        
        this.suborderOngoing = suborderOngoing;
        return this;
    }

     /**
     * Get suborderOngoing
     * @return suborderOngoing
    **/
    @javax.annotation.Nullable
    public Boolean getSuborderOngoing() {
        return suborderOngoing;
    }


    public void setSuborderOngoing(Boolean suborderOngoing) {
        this.suborderOngoing = suborderOngoing;
    }

    public ChaseOrder suborderFinishAs(String suborderFinishAs) {
        
        this.suborderFinishAs = suborderFinishAs;
        return this;
    }

     /**
     * Get suborderFinishAs
     * @return suborderFinishAs
    **/
    @javax.annotation.Nullable
    public String getSuborderFinishAs() {
        return suborderFinishAs;
    }


    public void setSuborderFinishAs(String suborderFinishAs) {
        this.suborderFinishAs = suborderFinishAs;
    }

    public ChaseOrder priceType(Integer priceType) {
        
        this.priceType = priceType;
        return this;
    }

     /**
     * PriceType enum: 1 latest, 2 index, 3 mark
     * @return priceType
    **/
    @javax.annotation.Nullable
    public Integer getPriceType() {
        return priceType;
    }


    public void setPriceType(Integer priceType) {
        this.priceType = priceType;
    }

    public ChaseOrder priceGapType(String priceGapType) {
        
        this.priceGapType = priceGapType;
        return this;
    }

     /**
     * Get priceGapType
     * @return priceGapType
    **/
    @javax.annotation.Nullable
    public String getPriceGapType() {
        return priceGapType;
    }


    public void setPriceGapType(String priceGapType) {
        this.priceGapType = priceGapType;
    }

    public ChaseOrder priceGapValue(String priceGapValue) {
        
        this.priceGapValue = priceGapValue;
        return this;
    }

     /**
     * Get priceGapValue
     * @return priceGapValue
    **/
    @javax.annotation.Nullable
    public String getPriceGapValue() {
        return priceGapValue;
    }


    public void setPriceGapValue(String priceGapValue) {
        this.priceGapValue = priceGapValue;
    }

    public ChaseOrder statusCode(String statusCode) {
        
        this.statusCode = statusCode;
        return this;
    }

     /**
     * Get statusCode
     * @return statusCode
    **/
    @javax.annotation.Nullable
    public String getStatusCode() {
        return statusCode;
    }


    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    public ChaseOrder createTimePrecise(String createTimePrecise) {
        
        this.createTimePrecise = createTimePrecise;
        return this;
    }

     /**
     * Creation time (seconds.microseconds)
     * @return createTimePrecise
    **/
    @javax.annotation.Nullable
    public String getCreateTimePrecise() {
        return createTimePrecise;
    }


    public void setCreateTimePrecise(String createTimePrecise) {
        this.createTimePrecise = createTimePrecise;
    }

    public ChaseOrder finishTimePrecise(String finishTimePrecise) {
        
        this.finishTimePrecise = finishTimePrecise;
        return this;
    }

     /**
     * Get finishTimePrecise
     * @return finishTimePrecise
    **/
    @javax.annotation.Nullable
    public String getFinishTimePrecise() {
        return finishTimePrecise;
    }


    public void setFinishTimePrecise(String finishTimePrecise) {
        this.finishTimePrecise = finishTimePrecise;
    }

    public ChaseOrder posMarginMode(String posMarginMode) {
        
        this.posMarginMode = posMarginMode;
        return this;
    }

     /**
     * Get posMarginMode
     * @return posMarginMode
    **/
    @javax.annotation.Nullable
    public String getPosMarginMode() {
        return posMarginMode;
    }


    public void setPosMarginMode(String posMarginMode) {
        this.posMarginMode = posMarginMode;
    }

    public ChaseOrder positionMode(String positionMode) {
        
        this.positionMode = positionMode;
        return this;
    }

     /**
     * Get positionMode
     * @return positionMode
    **/
    @javax.annotation.Nullable
    public String getPositionMode() {
        return positionMode;
    }


    public void setPositionMode(String positionMode) {
        this.positionMode = positionMode;
    }

    public ChaseOrder leverage(String leverage) {
        
        this.leverage = leverage;
        return this;
    }

     /**
     * Get leverage
     * @return leverage
    **/
    @javax.annotation.Nullable
    public String getLeverage() {
        return leverage;
    }


    public void setLeverage(String leverage) {
        this.leverage = leverage;
    }

    public ChaseOrder errorLabel(String errorLabel) {
        
        this.errorLabel = errorLabel;
        return this;
    }

     /**
     * Get errorLabel
     * @return errorLabel
    **/
    @javax.annotation.Nullable
    public String getErrorLabel() {
        return errorLabel;
    }


    public void setErrorLabel(String errorLabel) {
        this.errorLabel = errorLabel;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ChaseOrder chaseOrder = (ChaseOrder) o;
        return Objects.equals(this.id, chaseOrder.id) &&
                Objects.equals(this.user, chaseOrder.user) &&
                Objects.equals(this.contract, chaseOrder.contract) &&
                Objects.equals(this.settle, chaseOrder.settle) &&
                Objects.equals(this.amount, chaseOrder.amount) &&
                Objects.equals(this.priceLimit, chaseOrder.priceLimit) &&
                Objects.equals(this.reduceOnly, chaseOrder.reduceOnly) &&
                Objects.equals(this.text, chaseOrder.text) &&
                Objects.equals(this.createTime, chaseOrder.createTime) &&
                Objects.equals(this.finishTime, chaseOrder.finishTime) &&
                Objects.equals(this.originalStatus, chaseOrder.originalStatus) &&
                Objects.equals(this.status, chaseOrder.status) &&
                Objects.equals(this.reason, chaseOrder.reason) &&
                Objects.equals(this.fillAmount, chaseOrder.fillAmount) &&
                Objects.equals(this.averageFillPrice, chaseOrder.averageFillPrice) &&
                Objects.equals(this.suborderId, chaseOrder.suborderId) &&
                Objects.equals(this.isDualMode, chaseOrder.isDualMode) &&
                Objects.equals(this.sideLabel, chaseOrder.sideLabel) &&
                Objects.equals(this.positionSideOutput, chaseOrder.positionSideOutput) &&
                Objects.equals(this.chasePrice, chaseOrder.chasePrice) &&
                Objects.equals(this.intervalSec, chaseOrder.intervalSec) &&
                Objects.equals(this.updatedAt, chaseOrder.updatedAt) &&
                Objects.equals(this.suborderPrice, chaseOrder.suborderPrice) &&
                Objects.equals(this.suborderOngoing, chaseOrder.suborderOngoing) &&
                Objects.equals(this.suborderFinishAs, chaseOrder.suborderFinishAs) &&
                Objects.equals(this.priceType, chaseOrder.priceType) &&
                Objects.equals(this.priceGapType, chaseOrder.priceGapType) &&
                Objects.equals(this.priceGapValue, chaseOrder.priceGapValue) &&
                Objects.equals(this.statusCode, chaseOrder.statusCode) &&
                Objects.equals(this.createTimePrecise, chaseOrder.createTimePrecise) &&
                Objects.equals(this.finishTimePrecise, chaseOrder.finishTimePrecise) &&
                Objects.equals(this.posMarginMode, chaseOrder.posMarginMode) &&
                Objects.equals(this.positionMode, chaseOrder.positionMode) &&
                Objects.equals(this.leverage, chaseOrder.leverage) &&
                Objects.equals(this.errorLabel, chaseOrder.errorLabel);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, user, contract, settle, amount, priceLimit, reduceOnly, text, createTime, finishTime, originalStatus, status, reason, fillAmount, averageFillPrice, suborderId, isDualMode, sideLabel, positionSideOutput, chasePrice, intervalSec, updatedAt, suborderPrice, suborderOngoing, suborderFinishAs, priceType, priceGapType, priceGapValue, statusCode, createTimePrecise, finishTimePrecise, posMarginMode, positionMode, leverage, errorLabel);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ChaseOrder {\n");
        sb.append("      id: ").append(toIndentedString(id)).append("\n");
        sb.append("      user: ").append(toIndentedString(user)).append("\n");
        sb.append("      contract: ").append(toIndentedString(contract)).append("\n");
        sb.append("      settle: ").append(toIndentedString(settle)).append("\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("      priceLimit: ").append(toIndentedString(priceLimit)).append("\n");
        sb.append("      reduceOnly: ").append(toIndentedString(reduceOnly)).append("\n");
        sb.append("      text: ").append(toIndentedString(text)).append("\n");
        sb.append("      createTime: ").append(toIndentedString(createTime)).append("\n");
        sb.append("      finishTime: ").append(toIndentedString(finishTime)).append("\n");
        sb.append("      originalStatus: ").append(toIndentedString(originalStatus)).append("\n");
        sb.append("      status: ").append(toIndentedString(status)).append("\n");
        sb.append("      reason: ").append(toIndentedString(reason)).append("\n");
        sb.append("      fillAmount: ").append(toIndentedString(fillAmount)).append("\n");
        sb.append("      averageFillPrice: ").append(toIndentedString(averageFillPrice)).append("\n");
        sb.append("      suborderId: ").append(toIndentedString(suborderId)).append("\n");
        sb.append("      isDualMode: ").append(toIndentedString(isDualMode)).append("\n");
        sb.append("      sideLabel: ").append(toIndentedString(sideLabel)).append("\n");
        sb.append("      positionSideOutput: ").append(toIndentedString(positionSideOutput)).append("\n");
        sb.append("      chasePrice: ").append(toIndentedString(chasePrice)).append("\n");
        sb.append("      intervalSec: ").append(toIndentedString(intervalSec)).append("\n");
        sb.append("      updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("      suborderPrice: ").append(toIndentedString(suborderPrice)).append("\n");
        sb.append("      suborderOngoing: ").append(toIndentedString(suborderOngoing)).append("\n");
        sb.append("      suborderFinishAs: ").append(toIndentedString(suborderFinishAs)).append("\n");
        sb.append("      priceType: ").append(toIndentedString(priceType)).append("\n");
        sb.append("      priceGapType: ").append(toIndentedString(priceGapType)).append("\n");
        sb.append("      priceGapValue: ").append(toIndentedString(priceGapValue)).append("\n");
        sb.append("      statusCode: ").append(toIndentedString(statusCode)).append("\n");
        sb.append("      createTimePrecise: ").append(toIndentedString(createTimePrecise)).append("\n");
        sb.append("      finishTimePrecise: ").append(toIndentedString(finishTimePrecise)).append("\n");
        sb.append("      posMarginMode: ").append(toIndentedString(posMarginMode)).append("\n");
        sb.append("      positionMode: ").append(toIndentedString(positionMode)).append("\n");
        sb.append("      leverage: ").append(toIndentedString(leverage)).append("\n");
        sb.append("      errorLabel: ").append(toIndentedString(errorLabel)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

