/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The direction enumeration supported by the contract Martin strategy is consistent with the original interface of the App.
 */
@JsonAdapter(ContractMartingaleDirection.Adapter.class)
public enum ContractMartingaleDirection {
    
    BUY("buy"),
    
    SELL("sell");

    private String value;

    ContractMartingaleDirection(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static ContractMartingaleDirection fromValue(String value) {
        for (ContractMartingaleDirection b : ContractMartingaleDirection.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ContractMartingaleDirection> {
        @Override
        public void write(final JsonWriter jsonWriter, final ContractMartingaleDirection enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public ContractMartingaleDirection read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return ContractMartingaleDirection.fromValue(value);
        }
    }
}

