/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.CreateEarnFixedTermLendResponseData;
import java.io.IOException;

/**
 * CreateEarnFixedTermLendResponse
 */
public class CreateEarnFixedTermLendResponse {
    public static final String SERIALIZED_NAME_CODE = "code";
    @SerializedName(SERIALIZED_NAME_CODE)
    private Integer code;

    public static final String SERIALIZED_NAME_MESSAGE = "message";
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    private String message;

    public static final String SERIALIZED_NAME_DATA = "data";
    @SerializedName(SERIALIZED_NAME_DATA)
    private CreateEarnFixedTermLendResponseData data;

    public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
    @SerializedName(SERIALIZED_NAME_TIMESTAMP)
    private Integer timestamp;


    public CreateEarnFixedTermLendResponse code(Integer code) {
        
        this.code = code;
        return this;
    }

     /**
     * Return code, 0 means success
     * @return code
    **/
    @javax.annotation.Nullable
    public Integer getCode() {
        return code;
    }


    public void setCode(Integer code) {
        this.code = code;
    }

    public CreateEarnFixedTermLendResponse message(String message) {
        
        this.message = message;
        return this;
    }

     /**
     * Response message
     * @return message
    **/
    @javax.annotation.Nullable
    public String getMessage() {
        return message;
    }


    public void setMessage(String message) {
        this.message = message;
    }

    public CreateEarnFixedTermLendResponse data(CreateEarnFixedTermLendResponseData data) {
        
        this.data = data;
        return this;
    }

     /**
     * Get data
     * @return data
    **/
    @javax.annotation.Nullable
    public CreateEarnFixedTermLendResponseData getData() {
        return data;
    }


    public void setData(CreateEarnFixedTermLendResponseData data) {
        this.data = data;
    }

    public CreateEarnFixedTermLendResponse timestamp(Integer timestamp) {
        
        this.timestamp = timestamp;
        return this;
    }

     /**
     * Response timestamp (in seconds)
     * @return timestamp
    **/
    @javax.annotation.Nullable
    public Integer getTimestamp() {
        return timestamp;
    }


    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateEarnFixedTermLendResponse createEarnFixedTermLendResponse = (CreateEarnFixedTermLendResponse) o;
        return Objects.equals(this.code, createEarnFixedTermLendResponse.code) &&
                Objects.equals(this.message, createEarnFixedTermLendResponse.message) &&
                Objects.equals(this.data, createEarnFixedTermLendResponse.data) &&
                Objects.equals(this.timestamp, createEarnFixedTermLendResponse.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, message, data, timestamp);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateEarnFixedTermLendResponse {\n");
        sb.append("      code: ").append(toIndentedString(code)).append("\n");
        sb.append("      message: ").append(toIndentedString(message)).append("\n");
        sb.append("      data: ").append(toIndentedString(data)).append("\n");
        sb.append("      timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

