/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * **For order only**. Represents a currency and its **amount** on a certain side (&#x60;from&#x60; or &#x60;to&#x60;). Used with &#x60;OrderCreateV1Req&#x60;; **Don&#39;t** be used with &#x60;to&#x60; of the preview interface (preview &#x60;to&#x60; uses &#x60;PreviewToParam.ratio&#x60;).
 */
public class CreateParam {
    public static final String SERIALIZED_NAME_ASSET = "asset";
    @SerializedName(SERIALIZED_NAME_ASSET)
    private String asset;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;


    public CreateParam asset(String asset) {
        
        this.asset = asset;
        return this;
    }

     /**
     * Currency symbol, consistent with &#x60;GET /asset-swap/asset/list&#x60; and business support scope.
     * @return asset
    **/
    public String getAsset() {
        return asset;
    }


    public void setAsset(String asset) {
        this.asset = asset;
    }

    public CreateParam amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * The quantity of this currency on this side, **decimal string** (non-scientific notation). &#x60;from&#x60; represents the selling quantity, and &#x60;to&#x60; represents the target side quantity. Different from preview interface &#x60;to[].ratio&#x60;.
     * @return amount
    **/
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateParam createParam = (CreateParam) o;
        return Objects.equals(this.asset, createParam.asset) &&
                Objects.equals(this.amount, createParam.amount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(asset, amount);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateParam {\n");
        sb.append("      asset: ").append(toIndentedString(asset)).append("\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

