/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Place Order Request Body
 */
public class CrossexOrderRequest {
    public static final String SERIALIZED_NAME_TEXT = "text";
    @SerializedName(SERIALIZED_NAME_TEXT)
    private String text;

    public static final String SERIALIZED_NAME_SYMBOL = "symbol";
    @SerializedName(SERIALIZED_NAME_SYMBOL)
    private String symbol;

    /**
     * BUY, SELL
     */
    @JsonAdapter(SideEnum.Adapter.class)
    public enum SideEnum {
        BUY("BUY"),
        
        SELL("SELL");

        private String value;

        SideEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static SideEnum fromValue(String value) {
            for (SideEnum b : SideEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<SideEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final SideEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public SideEnum read(final JsonReader jsonReader) throws IOException {
                String value =  jsonReader.nextString();
                return SideEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_SIDE = "side";
    @SerializedName(SERIALIZED_NAME_SIDE)
    private SideEnum side;

    /**
     * Order type (default: &#x60;LIMIT&#x60;; supported types: &#x60;LIMIT&#x60;, &#x60;MARKET&#x60;)
     */
    @JsonAdapter(TypeEnum.Adapter.class)
    public enum TypeEnum {
        LIMIT("LIMIT"),
        
        MARKET("MARKET");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<TypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public TypeEnum read(final JsonReader jsonReader) throws IOException {
                String value =  jsonReader.nextString();
                return TypeEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    private TypeEnum type = TypeEnum.LIMIT;

    /**
     * Defaults to GTC. Supported values: &#x60;GTC&#x60;, &#x60;IOC&#x60;, &#x60;FOK&#x60;, &#x60;POC&#x60;, and &#x60;RPI&#x60; &#x60;GTC&#x60;: GoodTillCancelled &#x60;IOC&#x60;: ImmediateOrCancelled &#x60;FOK&#x60;: FillOrKill &#x60;POC&#x60;: PendingOrCancelled or PostOnly &#x60;RPI&#x60;: Retail Price Improvement
     */
    @JsonAdapter(TimeInForceEnum.Adapter.class)
    public enum TimeInForceEnum {
        GTC("GTC"),
        
        IOC("IOC"),
        
        FOK("FOK"),
        
        POC("POC"),
        
        RPI("RPI");

        private String value;

        TimeInForceEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TimeInForceEnum fromValue(String value) {
            for (TimeInForceEnum b : TimeInForceEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<TimeInForceEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final TimeInForceEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public TimeInForceEnum read(final JsonReader jsonReader) throws IOException {
                String value =  jsonReader.nextString();
                return TimeInForceEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_TIME_IN_FORCE = "time_in_force";
    @SerializedName(SERIALIZED_NAME_TIME_IN_FORCE)
    private TimeInForceEnum timeInForce = TimeInForceEnum.GTC;

    public static final String SERIALIZED_NAME_QTY = "qty";
    @SerializedName(SERIALIZED_NAME_QTY)
    private String qty;

    public static final String SERIALIZED_NAME_PRICE = "price";
    @SerializedName(SERIALIZED_NAME_PRICE)
    private String price;

    public static final String SERIALIZED_NAME_QUOTE_QTY = "quote_qty";
    @SerializedName(SERIALIZED_NAME_QUOTE_QTY)
    private String quoteQty;

    /**
     * Reduce-only: &#x60;true&#x60; or &#x60;false&#x60;
     */
    @JsonAdapter(ReduceOnlyEnum.Adapter.class)
    public enum ReduceOnlyEnum {
        TRUE("true"),
        
        FALSE("false");

        private String value;

        ReduceOnlyEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static ReduceOnlyEnum fromValue(String value) {
            for (ReduceOnlyEnum b : ReduceOnlyEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<ReduceOnlyEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final ReduceOnlyEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public ReduceOnlyEnum read(final JsonReader jsonReader) throws IOException {
                String value =  jsonReader.nextString();
                return ReduceOnlyEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_REDUCE_ONLY = "reduce_only";
    @SerializedName(SERIALIZED_NAME_REDUCE_ONLY)
    private ReduceOnlyEnum reduceOnly;

    /**
     * Position side: &#x60;NONE&#x60;, &#x60;LONG&#x60;, &#x60;SHORT&#x60; Defaults to &#x60;NONE&#x60; (single position mode) if not specified
     */
    @JsonAdapter(PositionSideEnum.Adapter.class)
    public enum PositionSideEnum {
        LONG("LONG"),
        
        SHORT("SHORT"),
        
        NONE("NONE");

        private String value;

        PositionSideEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static PositionSideEnum fromValue(String value) {
            for (PositionSideEnum b : PositionSideEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<PositionSideEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final PositionSideEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public PositionSideEnum read(final JsonReader jsonReader) throws IOException {
                String value =  jsonReader.nextString();
                return PositionSideEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_POSITION_SIDE = "position_side";
    @SerializedName(SERIALIZED_NAME_POSITION_SIDE)
    private PositionSideEnum positionSide;


    public CrossexOrderRequest text(String text) {
        
        this.text = text;
        return this;
    }

     /**
     * Client-defined Order ID, supports letters (a-z), numbers (0-9), symbols (-, _) only
     * @return text
    **/
    @javax.annotation.Nullable
    public String getText() {
        return text;
    }


    public void setText(String text) {
        this.text = text;
    }

    public CrossexOrderRequest symbol(String symbol) {
        
        this.symbol = symbol;
        return this;
    }

     /**
     * Unique identifier &#x60;{Exchange}_{Business}_{Base}_{Counter}&#x60; Examples: To send a Binance spot order on &#x60;ADA/USDT&#x60;, use &#x60;BINANCE_SPOT_ADA_USDT&#x60;; For an ADA/USDT-margined USDT perpetual futures order on OKX, use &#x60;OKX_FUTURE_ADA_USDT&#x60;; For ADA/USDT margin trading on Gate, use &#x60;GATE_MARGIN_ADA_USDT&#x60;; For ADA/USDT spot trading on Bybit, use &#x60;BYBIT_SPOT_ADA_USDT&#x60;; For an ADA/USD futures order on Kraken, use &#x60;KRAKEN_FUTURE_ADA_USD&#x60;; For an ADA/USDC futures order on Hyperliquid, use &#x60;HYPERLIQUID_FUTURE_ADA_USDC&#x60;; For an ADA/USDC futures order on Deribit, use &#x60;DERIBIT_FUTURE_ADA_USDC&#x60;; Supports spot trades, USDT-margined perpetual futures, and spot margin templates. BYBIT and DERIBIT omit spot margin for now; Kraken and Hyperliquid omit dedicated spot/margin legs inside CrossEx.
     * @return symbol
    **/
    public String getSymbol() {
        return symbol;
    }


    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public CrossexOrderRequest side(SideEnum side) {
        
        this.side = side;
        return this;
    }

     /**
     * BUY, SELL
     * @return side
    **/
    public SideEnum getSide() {
        return side;
    }


    public void setSide(SideEnum side) {
        this.side = side;
    }

    public CrossexOrderRequest type(TypeEnum type) {
        
        this.type = type;
        return this;
    }

     /**
     * Order type (default: &#x60;LIMIT&#x60;; supported types: &#x60;LIMIT&#x60;, &#x60;MARKET&#x60;)
     * @return type
    **/
    @javax.annotation.Nullable
    public TypeEnum getType() {
        return type;
    }


    public void setType(TypeEnum type) {
        this.type = type;
    }

    public CrossexOrderRequest timeInForce(TimeInForceEnum timeInForce) {
        
        this.timeInForce = timeInForce;
        return this;
    }

     /**
     * Defaults to GTC. Supported values: &#x60;GTC&#x60;, &#x60;IOC&#x60;, &#x60;FOK&#x60;, &#x60;POC&#x60;, and &#x60;RPI&#x60; &#x60;GTC&#x60;: GoodTillCancelled &#x60;IOC&#x60;: ImmediateOrCancelled &#x60;FOK&#x60;: FillOrKill &#x60;POC&#x60;: PendingOrCancelled or PostOnly &#x60;RPI&#x60;: Retail Price Improvement
     * @return timeInForce
    **/
    @javax.annotation.Nullable
    public TimeInForceEnum getTimeInForce() {
        return timeInForce;
    }


    public void setTimeInForce(TimeInForceEnum timeInForce) {
        this.timeInForce = timeInForce;
    }

    public CrossexOrderRequest qty(String qty) {
        
        this.qty = qty;
        return this;
    }

     /**
     * Order quantity (required unless spot or margin market buy)
     * @return qty
    **/
    @javax.annotation.Nullable
    public String getQty() {
        return qty;
    }


    public void setQty(String qty) {
        this.qty = qty;
    }

    public CrossexOrderRequest price(String price) {
        
        this.price = price;
        return this;
    }

     /**
     * Limit Order Price (Required for Limit Orders)
     * @return price
    **/
    @javax.annotation.Nullable
    public String getPrice() {
        return price;
    }


    public void setPrice(String price) {
        this.price = price;
    }

    public CrossexOrderRequest quoteQty(String quoteQty) {
        
        this.quoteQty = quoteQty;
        return this;
    }

     /**
     * Order quote quantity; required for spot and margin market buy orders
     * @return quoteQty
    **/
    @javax.annotation.Nullable
    public String getQuoteQty() {
        return quoteQty;
    }


    public void setQuoteQty(String quoteQty) {
        this.quoteQty = quoteQty;
    }

    public CrossexOrderRequest reduceOnly(ReduceOnlyEnum reduceOnly) {
        
        this.reduceOnly = reduceOnly;
        return this;
    }

     /**
     * Reduce-only: &#x60;true&#x60; or &#x60;false&#x60;
     * @return reduceOnly
    **/
    @javax.annotation.Nullable
    public ReduceOnlyEnum getReduceOnly() {
        return reduceOnly;
    }


    public void setReduceOnly(ReduceOnlyEnum reduceOnly) {
        this.reduceOnly = reduceOnly;
    }

    public CrossexOrderRequest positionSide(PositionSideEnum positionSide) {
        
        this.positionSide = positionSide;
        return this;
    }

     /**
     * Position side: &#x60;NONE&#x60;, &#x60;LONG&#x60;, &#x60;SHORT&#x60; Defaults to &#x60;NONE&#x60; (single position mode) if not specified
     * @return positionSide
    **/
    @javax.annotation.Nullable
    public PositionSideEnum getPositionSide() {
        return positionSide;
    }


    public void setPositionSide(PositionSideEnum positionSide) {
        this.positionSide = positionSide;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CrossexOrderRequest crossexOrderRequest = (CrossexOrderRequest) o;
        return Objects.equals(this.text, crossexOrderRequest.text) &&
                Objects.equals(this.symbol, crossexOrderRequest.symbol) &&
                Objects.equals(this.side, crossexOrderRequest.side) &&
                Objects.equals(this.type, crossexOrderRequest.type) &&
                Objects.equals(this.timeInForce, crossexOrderRequest.timeInForce) &&
                Objects.equals(this.qty, crossexOrderRequest.qty) &&
                Objects.equals(this.price, crossexOrderRequest.price) &&
                Objects.equals(this.quoteQty, crossexOrderRequest.quoteQty) &&
                Objects.equals(this.reduceOnly, crossexOrderRequest.reduceOnly) &&
                Objects.equals(this.positionSide, crossexOrderRequest.positionSide);
    }

    @Override
    public int hashCode() {
        return Objects.hash(text, symbol, side, type, timeInForce, qty, price, quoteQty, reduceOnly, positionSide);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CrossexOrderRequest {\n");
        sb.append("      text: ").append(toIndentedString(text)).append("\n");
        sb.append("      symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("      side: ").append(toIndentedString(side)).append("\n");
        sb.append("      type: ").append(toIndentedString(type)).append("\n");
        sb.append("      timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
        sb.append("      qty: ").append(toIndentedString(qty)).append("\n");
        sb.append("      price: ").append(toIndentedString(price)).append("\n");
        sb.append("      quoteQty: ").append(toIndentedString(quoteQty)).append("\n");
        sb.append("      reduceOnly: ").append(toIndentedString(reduceOnly)).append("\n");
        sb.append("      positionSide: ").append(toIndentedString(positionSide)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

