/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * 资金划转请求体
 */
public class CrossexTransferRequest {
    public static final String SERIALIZED_NAME_COIN = "coin";
    @SerializedName(SERIALIZED_NAME_COIN)
    private String coin;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;

    public static final String SERIALIZED_NAME_FROM = "from";
    @SerializedName(SERIALIZED_NAME_FROM)
    private String from;

    public static final String SERIALIZED_NAME_TO = "to";
    @SerializedName(SERIALIZED_NAME_TO)
    private String to;

    public static final String SERIALIZED_NAME_TEXT = "text";
    @SerializedName(SERIALIZED_NAME_TEXT)
    private String text;


    public CrossexTransferRequest coin(String coin) {
        
        this.coin = coin;
        return this;
    }

     /**
     * Currency
     * @return coin
    **/
    public String getCoin() {
        return coin;
    }


    public void setCoin(String coin) {
        this.coin = coin;
    }

    public CrossexTransferRequest amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * Transfer amount
     * @return amount
    **/
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }

    public CrossexTransferRequest from(String from) {
        
        this.from = from;
        return this;
    }

     /**
     * Transfer-in account: CROSSEX_BINANCE, CROSSEX_OKX, CROSSEX_GATE, CROSSEX_BYBIT, CROSSEX, SPOT
     * @return from
    **/
    public String getFrom() {
        return from;
    }


    public void setFrom(String from) {
        this.from = from;
    }

    public CrossexTransferRequest to(String to) {
        
        this.to = to;
        return this;
    }

     /**
     * Transfer-out account: CROSSEX_BINANCE, CROSSEX_OKX, CROSSEX_GATE, CROSSEX_BYBIT, CROSSEX, SPOT
     * @return to
    **/
    public String getTo() {
        return to;
    }


    public void setTo(String to) {
        this.to = to;
    }

    public CrossexTransferRequest text(String text) {
        
        this.text = text;
        return this;
    }

     /**
     * User-defined ID
     * @return text
    **/
    @javax.annotation.Nullable
    public String getText() {
        return text;
    }


    public void setText(String text) {
        this.text = text;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CrossexTransferRequest crossexTransferRequest = (CrossexTransferRequest) o;
        return Objects.equals(this.coin, crossexTransferRequest.coin) &&
                Objects.equals(this.amount, crossexTransferRequest.amount) &&
                Objects.equals(this.from, crossexTransferRequest.from) &&
                Objects.equals(this.to, crossexTransferRequest.to) &&
                Objects.equals(this.text, crossexTransferRequest.text);
    }

    @Override
    public int hashCode() {
        return Objects.hash(coin, amount, from, to, text);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CrossexTransferRequest {\n");
        sb.append("      coin: ").append(toIndentedString(coin)).append("\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("      from: ").append(toIndentedString(from)).append("\n");
        sb.append("      to: ").append(toIndentedString(to)).append("\n");
        sb.append("      text: ").append(toIndentedString(text)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

