/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Product configuration
 */
public class FixedTermProductInfo {
    public static final String SERIALIZED_NAME_PRE_REDEEM = "pre_redeem";
    @SerializedName(SERIALIZED_NAME_PRE_REDEEM)
    private Integer preRedeem;

    public static final String SERIALIZED_NAME_REINVEST = "reinvest";
    @SerializedName(SERIALIZED_NAME_REINVEST)
    private Integer reinvest;

    public static final String SERIALIZED_NAME_REDEEM_ACCOUNT = "redeem_account";
    @SerializedName(SERIALIZED_NAME_REDEEM_ACCOUNT)
    private Integer redeemAccount;

    public static final String SERIALIZED_NAME_MIN_VIP = "min_vip";
    @SerializedName(SERIALIZED_NAME_MIN_VIP)
    private Integer minVip;

    public static final String SERIALIZED_NAME_MAX_VIP = "max_vip";
    @SerializedName(SERIALIZED_NAME_MAX_VIP)
    private Integer maxVip;


    public FixedTermProductInfo preRedeem(Integer preRedeem) {
        
        this.preRedeem = preRedeem;
        return this;
    }

     /**
     * Whether early redemption is supported: 0 for not supported, 1 for supported
     * @return preRedeem
    **/
    public Integer getPreRedeem() {
        return preRedeem;
    }


    public void setPreRedeem(Integer preRedeem) {
        this.preRedeem = preRedeem;
    }

    public FixedTermProductInfo reinvest(Integer reinvest) {
        
        this.reinvest = reinvest;
        return this;
    }

     /**
     * Whether auto-renewal is supported: 0 for not supported, 1 for supported
     * @return reinvest
    **/
    public Integer getReinvest() {
        return reinvest;
    }


    public void setReinvest(Integer reinvest) {
        this.reinvest = reinvest;
    }

    public FixedTermProductInfo redeemAccount(Integer redeemAccount) {
        
        this.redeemAccount = redeemAccount;
        return this;
    }

     /**
     * Redemption payout account type
     * @return redeemAccount
    **/
    public Integer getRedeemAccount() {
        return redeemAccount;
    }


    public void setRedeemAccount(Integer redeemAccount) {
        this.redeemAccount = redeemAccount;
    }

    public FixedTermProductInfo minVip(Integer minVip) {
        
        this.minVip = minVip;
        return this;
    }

     /**
     * Minimum VIP level requirement, 0 means no restriction
     * @return minVip
    **/
    public Integer getMinVip() {
        return minVip;
    }


    public void setMinVip(Integer minVip) {
        this.minVip = minVip;
    }

    public FixedTermProductInfo maxVip(Integer maxVip) {
        
        this.maxVip = maxVip;
        return this;
    }

     /**
     * Maximum VIP level requirement, 0 means no restriction
     * @return maxVip
    **/
    public Integer getMaxVip() {
        return maxVip;
    }


    public void setMaxVip(Integer maxVip) {
        this.maxVip = maxVip;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FixedTermProductInfo fixedTermProductInfo = (FixedTermProductInfo) o;
        return Objects.equals(this.preRedeem, fixedTermProductInfo.preRedeem) &&
                Objects.equals(this.reinvest, fixedTermProductInfo.reinvest) &&
                Objects.equals(this.redeemAccount, fixedTermProductInfo.redeemAccount) &&
                Objects.equals(this.minVip, fixedTermProductInfo.minVip) &&
                Objects.equals(this.maxVip, fixedTermProductInfo.maxVip);
    }

    @Override
    public int hashCode() {
        return Objects.hash(preRedeem, reinvest, redeemAccount, minVip, maxVip);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FixedTermProductInfo {\n");
        sb.append("      preRedeem: ").append(toIndentedString(preRedeem)).append("\n");
        sb.append("      reinvest: ").append(toIndentedString(reinvest)).append("\n");
        sb.append("      redeemAccount: ").append(toIndentedString(redeemAccount)).append("\n");
        sb.append("      minVip: ").append(toIndentedString(minVip)).append("\n");
        sb.append("      maxVip: ").append(toIndentedString(maxVip)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

