/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Fixed-term earn product
 */
public class FixedTermProduct {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;

    public static final String SERIALIZED_NAME_ASSET = "asset";
    @SerializedName(SERIALIZED_NAME_ASSET)
    private String asset;

    public static final String SERIALIZED_NAME_LOCK_UP_PERIOD = "lock_up_period";
    @SerializedName(SERIALIZED_NAME_LOCK_UP_PERIOD)
    private Integer lockUpPeriod;

    public static final String SERIALIZED_NAME_MIN_LEND_AMOUNT = "min_lend_amount";
    @SerializedName(SERIALIZED_NAME_MIN_LEND_AMOUNT)
    private String minLendAmount;

    public static final String SERIALIZED_NAME_USER_MAX_LEND_AMOUNT = "user_max_lend_amount";
    @SerializedName(SERIALIZED_NAME_USER_MAX_LEND_AMOUNT)
    private String userMaxLendAmount;

    public static final String SERIALIZED_NAME_TOTAL_LEND_AMOUNT = "total_lend_amount";
    @SerializedName(SERIALIZED_NAME_TOTAL_LEND_AMOUNT)
    private String totalLendAmount;

    public static final String SERIALIZED_NAME_YEAR_RATE = "year_rate";
    @SerializedName(SERIALIZED_NAME_YEAR_RATE)
    private String yearRate;

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    private Integer type;

    public static final String SERIALIZED_NAME_PRE_REDEEM = "pre_redeem";
    @SerializedName(SERIALIZED_NAME_PRE_REDEEM)
    private Integer preRedeem;

    public static final String SERIALIZED_NAME_REINVEST = "reinvest";
    @SerializedName(SERIALIZED_NAME_REINVEST)
    private Integer reinvest;

    public static final String SERIALIZED_NAME_REDEEM_ACCOUNT = "redeem_account";
    @SerializedName(SERIALIZED_NAME_REDEEM_ACCOUNT)
    private Integer redeemAccount;

    public static final String SERIALIZED_NAME_MIN_VIP = "min_vip";
    @SerializedName(SERIALIZED_NAME_MIN_VIP)
    private Integer minVip;

    public static final String SERIALIZED_NAME_MAX_VIP = "max_vip";
    @SerializedName(SERIALIZED_NAME_MAX_VIP)
    private Integer maxVip;

    public static final String SERIALIZED_NAME_STATUS = "status";
    @SerializedName(SERIALIZED_NAME_STATUS)
    private Integer status;

    public static final String SERIALIZED_NAME_CREATE_TIME = "create_time";
    @SerializedName(SERIALIZED_NAME_CREATE_TIME)
    private String createTime;

    public static final String SERIALIZED_NAME_USER_MAX_LEND_VOLUME = "user_max_lend_volume";
    @SerializedName(SERIALIZED_NAME_USER_MAX_LEND_VOLUME)
    private String userMaxLendVolume;

    public static final String SERIALIZED_NAME_USER_TOTAL_AMOUNT = "user_total_amount";
    @SerializedName(SERIALIZED_NAME_USER_TOTAL_AMOUNT)
    private String userTotalAmount;

    public static final String SERIALIZED_NAME_SALE_STATUS = "sale_status";
    @SerializedName(SERIALIZED_NAME_SALE_STATUS)
    private Integer saleStatus;


    public FixedTermProduct id(Integer id) {
        
        this.id = id;
        return this;
    }

     /**
     * Product ID
     * @return id
    **/
    @javax.annotation.Nullable
    public Integer getId() {
        return id;
    }


    public void setId(Integer id) {
        this.id = id;
    }

    public FixedTermProduct name(String name) {
        
        this.name = name;
        return this;
    }

     /**
     * Product name
     * @return name
    **/
    @javax.annotation.Nullable
    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }

    public FixedTermProduct asset(String asset) {
        
        this.asset = asset;
        return this;
    }

     /**
     * Currency
     * @return asset
    **/
    @javax.annotation.Nullable
    public String getAsset() {
        return asset;
    }


    public void setAsset(String asset) {
        this.asset = asset;
    }

    public FixedTermProduct lockUpPeriod(Integer lockUpPeriod) {
        
        this.lockUpPeriod = lockUpPeriod;
        return this;
    }

     /**
     * Lock-up period (in days)
     * @return lockUpPeriod
    **/
    @javax.annotation.Nullable
    public Integer getLockUpPeriod() {
        return lockUpPeriod;
    }


    public void setLockUpPeriod(Integer lockUpPeriod) {
        this.lockUpPeriod = lockUpPeriod;
    }

    public FixedTermProduct minLendAmount(String minLendAmount) {
        
        this.minLendAmount = minLendAmount;
        return this;
    }

     /**
     * Minimum earn amount
     * @return minLendAmount
    **/
    @javax.annotation.Nullable
    public String getMinLendAmount() {
        return minLendAmount;
    }


    public void setMinLendAmount(String minLendAmount) {
        this.minLendAmount = minLendAmount;
    }

    public FixedTermProduct userMaxLendAmount(String userMaxLendAmount) {
        
        this.userMaxLendAmount = userMaxLendAmount;
        return this;
    }

     /**
     * User maximum earn limit
     * @return userMaxLendAmount
    **/
    @javax.annotation.Nullable
    public String getUserMaxLendAmount() {
        return userMaxLendAmount;
    }


    public void setUserMaxLendAmount(String userMaxLendAmount) {
        this.userMaxLendAmount = userMaxLendAmount;
    }

    public FixedTermProduct totalLendAmount(String totalLendAmount) {
        
        this.totalLendAmount = totalLendAmount;
        return this;
    }

     /**
     * Platform earn limit
     * @return totalLendAmount
    **/
    @javax.annotation.Nullable
    public String getTotalLendAmount() {
        return totalLendAmount;
    }


    public void setTotalLendAmount(String totalLendAmount) {
        this.totalLendAmount = totalLendAmount;
    }

    public FixedTermProduct yearRate(String yearRate) {
        
        this.yearRate = yearRate;
        return this;
    }

     /**
     * Annual interest rate
     * @return yearRate
    **/
    @javax.annotation.Nullable
    public String getYearRate() {
        return yearRate;
    }


    public void setYearRate(String yearRate) {
        this.yearRate = yearRate;
    }

    public FixedTermProduct type(Integer type) {
        
        this.type = type;
        return this;
    }

     /**
     * Product type: 1 for regular, 2 for VIP
     * @return type
    **/
    @javax.annotation.Nullable
    public Integer getType() {
        return type;
    }


    public void setType(Integer type) {
        this.type = type;
    }

    public FixedTermProduct preRedeem(Integer preRedeem) {
        
        this.preRedeem = preRedeem;
        return this;
    }

     /**
     * Whether early redemption is supported: 0 for not supported, 1 for supported
     * @return preRedeem
    **/
    @javax.annotation.Nullable
    public Integer getPreRedeem() {
        return preRedeem;
    }


    public void setPreRedeem(Integer preRedeem) {
        this.preRedeem = preRedeem;
    }

    public FixedTermProduct reinvest(Integer reinvest) {
        
        this.reinvest = reinvest;
        return this;
    }

     /**
     * Whether auto-renewal is supported: 0 for not supported, 1 for supported
     * @return reinvest
    **/
    @javax.annotation.Nullable
    public Integer getReinvest() {
        return reinvest;
    }


    public void setReinvest(Integer reinvest) {
        this.reinvest = reinvest;
    }

    public FixedTermProduct redeemAccount(Integer redeemAccount) {
        
        this.redeemAccount = redeemAccount;
        return this;
    }

     /**
     * Whether fixed-to-flexible conversion is supported: 0 for not supported, 1 for supported
     * @return redeemAccount
    **/
    @javax.annotation.Nullable
    public Integer getRedeemAccount() {
        return redeemAccount;
    }


    public void setRedeemAccount(Integer redeemAccount) {
        this.redeemAccount = redeemAccount;
    }

    public FixedTermProduct minVip(Integer minVip) {
        
        this.minVip = minVip;
        return this;
    }

     /**
     * Minimum VIP level requirement, 0-16, 0 means no restriction
     * @return minVip
    **/
    @javax.annotation.Nullable
    public Integer getMinVip() {
        return minVip;
    }


    public void setMinVip(Integer minVip) {
        this.minVip = minVip;
    }

    public FixedTermProduct maxVip(Integer maxVip) {
        
        this.maxVip = maxVip;
        return this;
    }

     /**
     * Maximum VIP level requirement (0-16), 0 means no restriction
     * @return maxVip
    **/
    @javax.annotation.Nullable
    public Integer getMaxVip() {
        return maxVip;
    }


    public void setMaxVip(Integer maxVip) {
        this.maxVip = maxVip;
    }

    public FixedTermProduct status(Integer status) {
        
        this.status = status;
        return this;
    }

     /**
     * Product status: 1 for unlisted, 2 for listed, 3 for delisted
     * @return status
    **/
    @javax.annotation.Nullable
    public Integer getStatus() {
        return status;
    }


    public void setStatus(Integer status) {
        this.status = status;
    }

    public FixedTermProduct createTime(String createTime) {
        
        this.createTime = createTime;
        return this;
    }

     /**
     * Created time
     * @return createTime
    **/
    @javax.annotation.Nullable
    public String getCreateTime() {
        return createTime;
    }


    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public FixedTermProduct userMaxLendVolume(String userMaxLendVolume) {
        
        this.userMaxLendVolume = userMaxLendVolume;
        return this;
    }

     /**
     * User maximum earn amount
     * @return userMaxLendVolume
    **/
    @javax.annotation.Nullable
    public String getUserMaxLendVolume() {
        return userMaxLendVolume;
    }


    public void setUserMaxLendVolume(String userMaxLendVolume) {
        this.userMaxLendVolume = userMaxLendVolume;
    }

    public FixedTermProduct userTotalAmount(String userTotalAmount) {
        
        this.userTotalAmount = userTotalAmount;
        return this;
    }

     /**
     * Total amount the user has invested in earn products
     * @return userTotalAmount
    **/
    @javax.annotation.Nullable
    public String getUserTotalAmount() {
        return userTotalAmount;
    }


    public void setUserTotalAmount(String userTotalAmount) {
        this.userTotalAmount = userTotalAmount;
    }

    public FixedTermProduct saleStatus(Integer saleStatus) {
        
        this.saleStatus = saleStatus;
        return this;
    }

     /**
     * Sale status: 1 for on sale, 2 for sold out
     * @return saleStatus
    **/
    @javax.annotation.Nullable
    public Integer getSaleStatus() {
        return saleStatus;
    }


    public void setSaleStatus(Integer saleStatus) {
        this.saleStatus = saleStatus;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FixedTermProduct fixedTermProduct = (FixedTermProduct) o;
        return Objects.equals(this.id, fixedTermProduct.id) &&
                Objects.equals(this.name, fixedTermProduct.name) &&
                Objects.equals(this.asset, fixedTermProduct.asset) &&
                Objects.equals(this.lockUpPeriod, fixedTermProduct.lockUpPeriod) &&
                Objects.equals(this.minLendAmount, fixedTermProduct.minLendAmount) &&
                Objects.equals(this.userMaxLendAmount, fixedTermProduct.userMaxLendAmount) &&
                Objects.equals(this.totalLendAmount, fixedTermProduct.totalLendAmount) &&
                Objects.equals(this.yearRate, fixedTermProduct.yearRate) &&
                Objects.equals(this.type, fixedTermProduct.type) &&
                Objects.equals(this.preRedeem, fixedTermProduct.preRedeem) &&
                Objects.equals(this.reinvest, fixedTermProduct.reinvest) &&
                Objects.equals(this.redeemAccount, fixedTermProduct.redeemAccount) &&
                Objects.equals(this.minVip, fixedTermProduct.minVip) &&
                Objects.equals(this.maxVip, fixedTermProduct.maxVip) &&
                Objects.equals(this.status, fixedTermProduct.status) &&
                Objects.equals(this.createTime, fixedTermProduct.createTime) &&
                Objects.equals(this.userMaxLendVolume, fixedTermProduct.userMaxLendVolume) &&
                Objects.equals(this.userTotalAmount, fixedTermProduct.userTotalAmount) &&
                Objects.equals(this.saleStatus, fixedTermProduct.saleStatus);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, asset, lockUpPeriod, minLendAmount, userMaxLendAmount, totalLendAmount, yearRate, type, preRedeem, reinvest, redeemAccount, minVip, maxVip, status, createTime, userMaxLendVolume, userTotalAmount, saleStatus);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FixedTermProduct {\n");
        sb.append("      id: ").append(toIndentedString(id)).append("\n");
        sb.append("      name: ").append(toIndentedString(name)).append("\n");
        sb.append("      asset: ").append(toIndentedString(asset)).append("\n");
        sb.append("      lockUpPeriod: ").append(toIndentedString(lockUpPeriod)).append("\n");
        sb.append("      minLendAmount: ").append(toIndentedString(minLendAmount)).append("\n");
        sb.append("      userMaxLendAmount: ").append(toIndentedString(userMaxLendAmount)).append("\n");
        sb.append("      totalLendAmount: ").append(toIndentedString(totalLendAmount)).append("\n");
        sb.append("      yearRate: ").append(toIndentedString(yearRate)).append("\n");
        sb.append("      type: ").append(toIndentedString(type)).append("\n");
        sb.append("      preRedeem: ").append(toIndentedString(preRedeem)).append("\n");
        sb.append("      reinvest: ").append(toIndentedString(reinvest)).append("\n");
        sb.append("      redeemAccount: ").append(toIndentedString(redeemAccount)).append("\n");
        sb.append("      minVip: ").append(toIndentedString(minVip)).append("\n");
        sb.append("      maxVip: ").append(toIndentedString(maxVip)).append("\n");
        sb.append("      status: ").append(toIndentedString(status)).append("\n");
        sb.append("      createTime: ").append(toIndentedString(createTime)).append("\n");
        sb.append("      userMaxLendVolume: ").append(toIndentedString(userMaxLendVolume)).append("\n");
        sb.append("      userTotalAmount: ").append(toIndentedString(userTotalAmount)).append("\n");
        sb.append("      saleStatus: ").append(toIndentedString(saleStatus)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

