/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * FlashSwapMultiCurrencyPreviewParam
 */
public class FlashSwapMultiCurrencyPreviewParam {
    public static final String SERIALIZED_NAME_SELL_ASSET = "sell_asset";
    @SerializedName(SERIALIZED_NAME_SELL_ASSET)
    private String sellAsset;

    public static final String SERIALIZED_NAME_SELL_AMOUNT = "sell_amount";
    @SerializedName(SERIALIZED_NAME_SELL_AMOUNT)
    private String sellAmount;

    public static final String SERIALIZED_NAME_BUY_ASSET = "buy_asset";
    @SerializedName(SERIALIZED_NAME_BUY_ASSET)
    private String buyAsset;

    public static final String SERIALIZED_NAME_BUY_AMOUNT = "buy_amount";
    @SerializedName(SERIALIZED_NAME_BUY_AMOUNT)
    private String buyAmount;


    public FlashSwapMultiCurrencyPreviewParam sellAsset(String sellAsset) {
        
        this.sellAsset = sellAsset;
        return this;
    }

     /**
     * Currency to sell
     * @return sellAsset
    **/
    public String getSellAsset() {
        return sellAsset;
    }


    public void setSellAsset(String sellAsset) {
        this.sellAsset = sellAsset;
    }

    public FlashSwapMultiCurrencyPreviewParam sellAmount(String sellAmount) {
        
        this.sellAmount = sellAmount;
        return this;
    }

     /**
     * Sell amount
     * @return sellAmount
    **/
    @javax.annotation.Nullable
    public String getSellAmount() {
        return sellAmount;
    }


    public void setSellAmount(String sellAmount) {
        this.sellAmount = sellAmount;
    }

    public FlashSwapMultiCurrencyPreviewParam buyAsset(String buyAsset) {
        
        this.buyAsset = buyAsset;
        return this;
    }

     /**
     * Currency to buy
     * @return buyAsset
    **/
    public String getBuyAsset() {
        return buyAsset;
    }


    public void setBuyAsset(String buyAsset) {
        this.buyAsset = buyAsset;
    }

    public FlashSwapMultiCurrencyPreviewParam buyAmount(String buyAmount) {
        
        this.buyAmount = buyAmount;
        return this;
    }

     /**
     * Buy amount
     * @return buyAmount
    **/
    @javax.annotation.Nullable
    public String getBuyAmount() {
        return buyAmount;
    }


    public void setBuyAmount(String buyAmount) {
        this.buyAmount = buyAmount;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FlashSwapMultiCurrencyPreviewParam flashSwapMultiCurrencyPreviewParam = (FlashSwapMultiCurrencyPreviewParam) o;
        return Objects.equals(this.sellAsset, flashSwapMultiCurrencyPreviewParam.sellAsset) &&
                Objects.equals(this.sellAmount, flashSwapMultiCurrencyPreviewParam.sellAmount) &&
                Objects.equals(this.buyAsset, flashSwapMultiCurrencyPreviewParam.buyAsset) &&
                Objects.equals(this.buyAmount, flashSwapMultiCurrencyPreviewParam.buyAmount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sellAsset, sellAmount, buyAsset, buyAmount);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FlashSwapMultiCurrencyPreviewParam {\n");
        sb.append("      sellAsset: ").append(toIndentedString(sellAsset)).append("\n");
        sb.append("      sellAmount: ").append(toIndentedString(sellAmount)).append("\n");
        sb.append("      buyAsset: ").append(toIndentedString(buyAsset)).append("\n");
        sb.append("      buyAmount: ").append(toIndentedString(buyAmount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

