/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * InlineResponse20044
 */
public class InlineResponse20044 {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private String id;

    public static final String SERIALIZED_NAME_USER_ID = "user_id";
    @SerializedName(SERIALIZED_NAME_USER_ID)
    private String userId;

    public static final String SERIALIZED_NAME_BUSINESS_ID = "business_id";
    @SerializedName(SERIALIZED_NAME_BUSINESS_ID)
    private String businessId;

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;

    public static final String SERIALIZED_NAME_EXCHANGE_TYPE = "exchange_type";
    @SerializedName(SERIALIZED_NAME_EXCHANGE_TYPE)
    private String exchangeType;

    public static final String SERIALIZED_NAME_COIN = "coin";
    @SerializedName(SERIALIZED_NAME_COIN)
    private String coin;

    public static final String SERIALIZED_NAME_CHANGE = "change";
    @SerializedName(SERIALIZED_NAME_CHANGE)
    private String change;

    public static final String SERIALIZED_NAME_BALANCE = "balance";
    @SerializedName(SERIALIZED_NAME_BALANCE)
    private String balance;

    public static final String SERIALIZED_NAME_CREATE_TIME = "create_time";
    @SerializedName(SERIALIZED_NAME_CREATE_TIME)
    private String createTime;


    public InlineResponse20044 id(String id) {
        
        this.id = id;
        return this;
    }

     /**
     * Account Change Record ID
     * @return id
    **/
    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id;
    }

    public InlineResponse20044 userId(String userId) {
        
        this.userId = userId;
        return this;
    }

     /**
     * User ID
     * @return userId
    **/
    public String getUserId() {
        return userId;
    }


    public void setUserId(String userId) {
        this.userId = userId;
    }

    public InlineResponse20044 businessId(String businessId) {
        
        this.businessId = businessId;
        return this;
    }

     /**
     * Business ID
     * @return businessId
    **/
    public String getBusinessId() {
        return businessId;
    }


    public void setBusinessId(String businessId) {
        this.businessId = businessId;
    }

    public InlineResponse20044 type(String type) {
        
        this.type = type;
        return this;
    }

     /**
     * 变更类型| &#x60;TRANSACTION&#x60; 成交 &#x60;TRADING_FEE&#x60; 手续费 &#x60;FUNDING_FEE&#x60; 合约资金费 &#x60;LIQUIDATION_FEE&#x60; 强平费 &#x60;TRANSFER_IN&#x60; 资金转入 &#x60;TRANSFER_OUT&#x60; 资金转出 &#x60;BANKRUPT_COMPENSATION&#x60; 穿仓补贴 &#x60;AUTO_REPAY&#x60; 杠杆仓位自动还负债
     * @return type
    **/
    public String getType() {
        return type;
    }


    public void setType(String type) {
        this.type = type;
    }

    public InlineResponse20044 exchangeType(String exchangeType) {
        
        this.exchangeType = exchangeType;
        return this;
    }

     /**
     * Exchange
     * @return exchangeType
    **/
    public String getExchangeType() {
        return exchangeType;
    }


    public void setExchangeType(String exchangeType) {
        this.exchangeType = exchangeType;
    }

    public InlineResponse20044 coin(String coin) {
        
        this.coin = coin;
        return this;
    }

     /**
     * Currency
     * @return coin
    **/
    public String getCoin() {
        return coin;
    }


    public void setCoin(String coin) {
        this.coin = coin;
    }

    public InlineResponse20044 change(String change) {
        
        this.change = change;
        return this;
    }

     /**
     * Change amount (positive indicates transfer in; negative indicates transfer out)
     * @return change
    **/
    public String getChange() {
        return change;
    }


    public void setChange(String change) {
        this.change = change;
    }

    public InlineResponse20044 balance(String balance) {
        
        this.balance = balance;
        return this;
    }

     /**
     * Balance after change
     * @return balance
    **/
    public String getBalance() {
        return balance;
    }


    public void setBalance(String balance) {
        this.balance = balance;
    }

    public InlineResponse20044 createTime(String createTime) {
        
        this.createTime = createTime;
        return this;
    }

     /**
     * Created time
     * @return createTime
    **/
    public String getCreateTime() {
        return createTime;
    }


    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20044 inlineResponse20044 = (InlineResponse20044) o;
        return Objects.equals(this.id, inlineResponse20044.id) &&
                Objects.equals(this.userId, inlineResponse20044.userId) &&
                Objects.equals(this.businessId, inlineResponse20044.businessId) &&
                Objects.equals(this.type, inlineResponse20044.type) &&
                Objects.equals(this.exchangeType, inlineResponse20044.exchangeType) &&
                Objects.equals(this.coin, inlineResponse20044.coin) &&
                Objects.equals(this.change, inlineResponse20044.change) &&
                Objects.equals(this.balance, inlineResponse20044.balance) &&
                Objects.equals(this.createTime, inlineResponse20044.createTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userId, businessId, type, exchangeType, coin, change, balance, createTime);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20044 {\n");
        sb.append("      id: ").append(toIndentedString(id)).append("\n");
        sb.append("      userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("      businessId: ").append(toIndentedString(businessId)).append("\n");
        sb.append("      type: ").append(toIndentedString(type)).append("\n");
        sb.append("      exchangeType: ").append(toIndentedString(exchangeType)).append("\n");
        sb.append("      coin: ").append(toIndentedString(coin)).append("\n");
        sb.append("      change: ").append(toIndentedString(change)).append("\n");
        sb.append("      balance: ").append(toIndentedString(balance)).append("\n");
        sb.append("      createTime: ").append(toIndentedString(createTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

