/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * InlineObject16
 */
public class InlineObject16 {
    public static final String SERIALIZED_NAME_ASSET = "asset";
    @SerializedName(SERIALIZED_NAME_ASSET)
    private String asset;

    public static final String SERIALIZED_NAME_FIAT_UNIT = "fiat_unit";
    @SerializedName(SERIALIZED_NAME_FIAT_UNIT)
    private String fiatUnit;

    public static final String SERIALIZED_NAME_TRADE_TYPE = "trade_type";
    @SerializedName(SERIALIZED_NAME_TRADE_TYPE)
    private String tradeType;


    public InlineObject16 asset(String asset) {
        
        this.asset = asset;
        return this;
    }

     /**
     * Cryptocurrency
     * @return asset
    **/
    @javax.annotation.Nullable
    public String getAsset() {
        return asset;
    }


    public void setAsset(String asset) {
        this.asset = asset;
    }

    public InlineObject16 fiatUnit(String fiatUnit) {
        
        this.fiatUnit = fiatUnit;
        return this;
    }

     /**
     * Fiat currency
     * @return fiatUnit
    **/
    @javax.annotation.Nullable
    public String getFiatUnit() {
        return fiatUnit;
    }


    public void setFiatUnit(String fiatUnit) {
        this.fiatUnit = fiatUnit;
    }

    public InlineObject16 tradeType(String tradeType) {
        
        this.tradeType = tradeType;
        return this;
    }

     /**
     * Buy/Sell
     * @return tradeType
    **/
    @javax.annotation.Nullable
    public String getTradeType() {
        return tradeType;
    }


    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineObject16 inlineObject16 = (InlineObject16) o;
        return Objects.equals(this.asset, inlineObject16.asset) &&
                Objects.equals(this.fiatUnit, inlineObject16.fiatUnit) &&
                Objects.equals(this.tradeType, inlineObject16.tradeType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(asset, fiatUnit, tradeType);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineObject16 {\n");
        sb.append("      asset: ").append(toIndentedString(asset)).append("\n");
        sb.append("      fiatUnit: ").append(toIndentedString(fiatUnit)).append("\n");
        sb.append("      tradeType: ").append(toIndentedString(tradeType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

