/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Replay video information (has value when content_type&#x3D;video)
 */
public class InlineResponse20010DataVideo {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private String id;

    public static final String SERIALIZED_NAME_STREAM_ID = "stream_id";
    @SerializedName(SERIALIZED_NAME_STREAM_ID)
    private String streamId;

    public static final String SERIALIZED_NAME_TITLE = "title";
    @SerializedName(SERIALIZED_NAME_TITLE)
    private String title;

    public static final String SERIALIZED_NAME_AVATAR = "avatar";
    @SerializedName(SERIALIZED_NAME_AVATAR)
    private String avatar;

    public static final String SERIALIZED_NAME_NICK = "nick";
    @SerializedName(SERIALIZED_NAME_NICK)
    private String nick;

    public static final String SERIALIZED_NAME_NICK_EN = "nick_en";
    @SerializedName(SERIALIZED_NAME_NICK_EN)
    private String nickEn;

    public static final String SERIALIZED_NAME_COVER = "cover";
    @SerializedName(SERIALIZED_NAME_COVER)
    private String cover;

    public static final String SERIALIZED_NAME_WATCHED = "watched";
    @SerializedName(SERIALIZED_NAME_WATCHED)
    private Integer watched;

    public static final String SERIALIZED_NAME_SUBSCRIPTION_REQUIRED = "subscription_required";
    @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_REQUIRED)
    private Boolean subscriptionRequired;

    public static final String SERIALIZED_NAME_HAS_SUBSCRIBED = "has_subscribed";
    @SerializedName(SERIALIZED_NAME_HAS_SUBSCRIBED)
    private Boolean hasSubscribed;

    public static final String SERIALIZED_NAME_DURATION = "duration";
    @SerializedName(SERIALIZED_NAME_DURATION)
    private Integer duration;

    public static final String SERIALIZED_NAME_WEIGHT = "weight";
    @SerializedName(SERIALIZED_NAME_WEIGHT)
    private Integer weight;

    public static final String SERIALIZED_NAME_MOMENTS_UID = "moments_uid";
    @SerializedName(SERIALIZED_NAME_MOMENTS_UID)
    private String momentsUid;

    public static final String SERIALIZED_NAME_SESSION_ID = "session_id";
    @SerializedName(SERIALIZED_NAME_SESSION_ID)
    private String sessionId;

    public static final String SERIALIZED_NAME_ENDED_AT_FORMAT = "ended_at_format";
    @SerializedName(SERIALIZED_NAME_ENDED_AT_FORMAT)
    private String endedAtFormat;

    public static final String SERIALIZED_NAME_ENDED_AT_TYPE = "ended_at_type";
    @SerializedName(SERIALIZED_NAME_ENDED_AT_TYPE)
    private Integer endedAtType;

    public static final String SERIALIZED_NAME_TIER = "tier";
    @SerializedName(SERIALIZED_NAME_TIER)
    private Integer tier;

    public static final String SERIALIZED_NAME_TAG = "tag";
    @SerializedName(SERIALIZED_NAME_TAG)
    private String tag;


    public InlineResponse20010DataVideo id(String id) {
        
        this.id = id;
        return this;
    }

     /**
     * Video ID
     * @return id
    **/
    @javax.annotation.Nullable
    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id;
    }

    public InlineResponse20010DataVideo streamId(String streamId) {
        
        this.streamId = streamId;
        return this;
    }

     /**
     * Live stream ID
     * @return streamId
    **/
    @javax.annotation.Nullable
    public String getStreamId() {
        return streamId;
    }


    public void setStreamId(String streamId) {
        this.streamId = streamId;
    }

    public InlineResponse20010DataVideo title(String title) {
        
        this.title = title;
        return this;
    }

     /**
     * Video Title
     * @return title
    **/
    @javax.annotation.Nullable
    public String getTitle() {
        return title;
    }


    public void setTitle(String title) {
        this.title = title;
    }

    public InlineResponse20010DataVideo avatar(String avatar) {
        
        this.avatar = avatar;
        return this;
    }

     /**
     * Author avatar URL
     * @return avatar
    **/
    @javax.annotation.Nullable
    public String getAvatar() {
        return avatar;
    }


    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public InlineResponse20010DataVideo nick(String nick) {
        
        this.nick = nick;
        return this;
    }

     /**
     * Author nickname
     * @return nick
    **/
    @javax.annotation.Nullable
    public String getNick() {
        return nick;
    }


    public void setNick(String nick) {
        this.nick = nick;
    }

    public InlineResponse20010DataVideo nickEn(String nickEn) {
        
        this.nickEn = nickEn;
        return this;
    }

     /**
     * Author English nickname
     * @return nickEn
    **/
    @javax.annotation.Nullable
    public String getNickEn() {
        return nickEn;
    }


    public void setNickEn(String nickEn) {
        this.nickEn = nickEn;
    }

    public InlineResponse20010DataVideo cover(String cover) {
        
        this.cover = cover;
        return this;
    }

     /**
     * Cover image URL
     * @return cover
    **/
    @javax.annotation.Nullable
    public String getCover() {
        return cover;
    }


    public void setCover(String cover) {
        this.cover = cover;
    }

    public InlineResponse20010DataVideo watched(Integer watched) {
        
        this.watched = watched;
        return this;
    }

     /**
     * Viewer count
     * @return watched
    **/
    @javax.annotation.Nullable
    public Integer getWatched() {
        return watched;
    }


    public void setWatched(Integer watched) {
        this.watched = watched;
    }

    public InlineResponse20010DataVideo subscriptionRequired(Boolean subscriptionRequired) {
        
        this.subscriptionRequired = subscriptionRequired;
        return this;
    }

     /**
     * Whether subscription is required
     * @return subscriptionRequired
    **/
    @javax.annotation.Nullable
    public Boolean getSubscriptionRequired() {
        return subscriptionRequired;
    }


    public void setSubscriptionRequired(Boolean subscriptionRequired) {
        this.subscriptionRequired = subscriptionRequired;
    }

    public InlineResponse20010DataVideo hasSubscribed(Boolean hasSubscribed) {
        
        this.hasSubscribed = hasSubscribed;
        return this;
    }

     /**
     * Whether the current user has subscribed
     * @return hasSubscribed
    **/
    @javax.annotation.Nullable
    public Boolean getHasSubscribed() {
        return hasSubscribed;
    }


    public void setHasSubscribed(Boolean hasSubscribed) {
        this.hasSubscribed = hasSubscribed;
    }

    public InlineResponse20010DataVideo duration(Integer duration) {
        
        this.duration = duration;
        return this;
    }

     /**
     * Video duration (in seconds)
     * @return duration
    **/
    @javax.annotation.Nullable
    public Integer getDuration() {
        return duration;
    }


    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public InlineResponse20010DataVideo weight(Integer weight) {
        
        this.weight = weight;
        return this;
    }

     /**
     * Sort weight
     * @return weight
    **/
    @javax.annotation.Nullable
    public Integer getWeight() {
        return weight;
    }


    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public InlineResponse20010DataVideo momentsUid(String momentsUid) {
        
        this.momentsUid = momentsUid;
        return this;
    }

     /**
     * Square user ID
     * @return momentsUid
    **/
    @javax.annotation.Nullable
    public String getMomentsUid() {
        return momentsUid;
    }


    public void setMomentsUid(String momentsUid) {
        this.momentsUid = momentsUid;
    }

    public InlineResponse20010DataVideo sessionId(String sessionId) {
        
        this.sessionId = sessionId;
        return this;
    }

     /**
     * Session ID
     * @return sessionId
    **/
    @javax.annotation.Nullable
    public String getSessionId() {
        return sessionId;
    }


    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public InlineResponse20010DataVideo endedAtFormat(String endedAtFormat) {
        
        this.endedAtFormat = endedAtFormat;
        return this;
    }

     /**
     * End time format
     * @return endedAtFormat
    **/
    @javax.annotation.Nullable
    public String getEndedAtFormat() {
        return endedAtFormat;
    }


    public void setEndedAtFormat(String endedAtFormat) {
        this.endedAtFormat = endedAtFormat;
    }

    public InlineResponse20010DataVideo endedAtType(Integer endedAtType) {
        
        this.endedAtType = endedAtType;
        return this;
    }

     /**
     * End time type
     * @return endedAtType
    **/
    @javax.annotation.Nullable
    public Integer getEndedAtType() {
        return endedAtType;
    }


    public void setEndedAtType(Integer endedAtType) {
        this.endedAtType = endedAtType;
    }

    public InlineResponse20010DataVideo tier(Integer tier) {
        
        this.tier = tier;
        return this;
    }

     /**
     * Author level
     * @return tier
    **/
    @javax.annotation.Nullable
    public Integer getTier() {
        return tier;
    }


    public void setTier(Integer tier) {
        this.tier = tier;
    }

    public InlineResponse20010DataVideo tag(String tag) {
        
        this.tag = tag;
        return this;
    }

     /**
     * Tag
     * @return tag
    **/
    @javax.annotation.Nullable
    public String getTag() {
        return tag;
    }


    public void setTag(String tag) {
        this.tag = tag;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20010DataVideo inlineResponse20010DataVideo = (InlineResponse20010DataVideo) o;
        return Objects.equals(this.id, inlineResponse20010DataVideo.id) &&
                Objects.equals(this.streamId, inlineResponse20010DataVideo.streamId) &&
                Objects.equals(this.title, inlineResponse20010DataVideo.title) &&
                Objects.equals(this.avatar, inlineResponse20010DataVideo.avatar) &&
                Objects.equals(this.nick, inlineResponse20010DataVideo.nick) &&
                Objects.equals(this.nickEn, inlineResponse20010DataVideo.nickEn) &&
                Objects.equals(this.cover, inlineResponse20010DataVideo.cover) &&
                Objects.equals(this.watched, inlineResponse20010DataVideo.watched) &&
                Objects.equals(this.subscriptionRequired, inlineResponse20010DataVideo.subscriptionRequired) &&
                Objects.equals(this.hasSubscribed, inlineResponse20010DataVideo.hasSubscribed) &&
                Objects.equals(this.duration, inlineResponse20010DataVideo.duration) &&
                Objects.equals(this.weight, inlineResponse20010DataVideo.weight) &&
                Objects.equals(this.momentsUid, inlineResponse20010DataVideo.momentsUid) &&
                Objects.equals(this.sessionId, inlineResponse20010DataVideo.sessionId) &&
                Objects.equals(this.endedAtFormat, inlineResponse20010DataVideo.endedAtFormat) &&
                Objects.equals(this.endedAtType, inlineResponse20010DataVideo.endedAtType) &&
                Objects.equals(this.tier, inlineResponse20010DataVideo.tier) &&
                Objects.equals(this.tag, inlineResponse20010DataVideo.tag);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, streamId, title, avatar, nick, nickEn, cover, watched, subscriptionRequired, hasSubscribed, duration, weight, momentsUid, sessionId, endedAtFormat, endedAtType, tier, tag);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20010DataVideo {\n");
        sb.append("      id: ").append(toIndentedString(id)).append("\n");
        sb.append("      streamId: ").append(toIndentedString(streamId)).append("\n");
        sb.append("      title: ").append(toIndentedString(title)).append("\n");
        sb.append("      avatar: ").append(toIndentedString(avatar)).append("\n");
        sb.append("      nick: ").append(toIndentedString(nick)).append("\n");
        sb.append("      nickEn: ").append(toIndentedString(nickEn)).append("\n");
        sb.append("      cover: ").append(toIndentedString(cover)).append("\n");
        sb.append("      watched: ").append(toIndentedString(watched)).append("\n");
        sb.append("      subscriptionRequired: ").append(toIndentedString(subscriptionRequired)).append("\n");
        sb.append("      hasSubscribed: ").append(toIndentedString(hasSubscribed)).append("\n");
        sb.append("      duration: ").append(toIndentedString(duration)).append("\n");
        sb.append("      weight: ").append(toIndentedString(weight)).append("\n");
        sb.append("      momentsUid: ").append(toIndentedString(momentsUid)).append("\n");
        sb.append("      sessionId: ").append(toIndentedString(sessionId)).append("\n");
        sb.append("      endedAtFormat: ").append(toIndentedString(endedAtFormat)).append("\n");
        sb.append("      endedAtType: ").append(toIndentedString(endedAtType)).append("\n");
        sb.append("      tier: ").append(toIndentedString(tier)).append("\n");
        sb.append("      tag: ").append(toIndentedString(tag)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

