/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * InlineObject5
 */
public class InlineObject5 {
    public static final String SERIALIZED_NAME_BIZ_UID = "biz_uid";
    @SerializedName(SERIALIZED_NAME_BIZ_UID)
    private String bizUid;


    public InlineObject5 bizUid(String bizUid) {
        
        this.bizUid = bizUid;
        return this;
    }

     /**
     * Counterparty UID (encrypted)
     * @return bizUid
    **/
    public String getBizUid() {
        return bizUid;
    }


    public void setBizUid(String bizUid) {
        this.bizUid = bizUid;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineObject5 inlineObject5 = (InlineObject5) o;
        return Objects.equals(this.bizUid, inlineObject5.bizUid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bizUid);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineObject5 {\n");
        sb.append("      bizUid: ").append(toIndentedString(bizUid)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

