/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.InlineResponse20014DataMerchantInfo;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * InlineResponse20014Data
 */
public class InlineResponse20014Data {
    public static final String SERIALIZED_NAME_IS_SELF = "is_self";
    @SerializedName(SERIALIZED_NAME_IS_SELF)
    private Boolean isSelf;

    public static final String SERIALIZED_NAME_USER_TIMEST = "user_timest";
    @SerializedName(SERIALIZED_NAME_USER_TIMEST)
    private String userTimest;

    public static final String SERIALIZED_NAME_COUNTERPARTIES_NUM = "counterparties_num";
    @SerializedName(SERIALIZED_NAME_COUNTERPARTIES_NUM)
    private Integer counterpartiesNum;

    public static final String SERIALIZED_NAME_EMAIL_VERIFIED = "email_verified";
    @SerializedName(SERIALIZED_NAME_EMAIL_VERIFIED)
    private String emailVerified;

    public static final String SERIALIZED_NAME_VERIFIED = "verified";
    @SerializedName(SERIALIZED_NAME_VERIFIED)
    private String verified;

    public static final String SERIALIZED_NAME_HAS_PHONE = "has_phone";
    @SerializedName(SERIALIZED_NAME_HAS_PHONE)
    private String hasPhone;

    public static final String SERIALIZED_NAME_USER_NAME = "user_name";
    @SerializedName(SERIALIZED_NAME_USER_NAME)
    private String userName;

    public static final String SERIALIZED_NAME_USER_NOTE = "user_note";
    @SerializedName(SERIALIZED_NAME_USER_NOTE)
    private String userNote;

    public static final String SERIALIZED_NAME_COMPLETE_TRANSACTIONS = "complete_transactions";
    @SerializedName(SERIALIZED_NAME_COMPLETE_TRANSACTIONS)
    private String completeTransactions;

    public static final String SERIALIZED_NAME_PAID_TRANSACTIONS = "paid_transactions";
    @SerializedName(SERIALIZED_NAME_PAID_TRANSACTIONS)
    private String paidTransactions;

    public static final String SERIALIZED_NAME_ACCEPTED_TRANSACTIONS = "accepted_transactions";
    @SerializedName(SERIALIZED_NAME_ACCEPTED_TRANSACTIONS)
    private String acceptedTransactions;

    public static final String SERIALIZED_NAME_TRANSACTIONS_USED_TIME = "transactions_used_time";
    @SerializedName(SERIALIZED_NAME_TRANSACTIONS_USED_TIME)
    private String transactionsUsedTime;

    public static final String SERIALIZED_NAME_CANCELLED_USED_TIME_MONTH = "cancelled_used_time_month";
    @SerializedName(SERIALIZED_NAME_CANCELLED_USED_TIME_MONTH)
    private String cancelledUsedTimeMonth;

    public static final String SERIALIZED_NAME_COMPLETE_TRANSACTIONS_MONTH = "complete_transactions_month";
    @SerializedName(SERIALIZED_NAME_COMPLETE_TRANSACTIONS_MONTH)
    private String completeTransactionsMonth;

    public static final String SERIALIZED_NAME_COMPLETE_RATE_MONTH = "complete_rate_month";
    @SerializedName(SERIALIZED_NAME_COMPLETE_RATE_MONTH)
    private BigDecimal completeRateMonth;

    public static final String SERIALIZED_NAME_ORDERS_BUY_RATE_MONTH = "orders_buy_rate_month";
    @SerializedName(SERIALIZED_NAME_ORDERS_BUY_RATE_MONTH)
    private BigDecimal ordersBuyRateMonth;

    public static final String SERIALIZED_NAME_IS_BLACK = "is_black";
    @SerializedName(SERIALIZED_NAME_IS_BLACK)
    private Integer isBlack;

    public static final String SERIALIZED_NAME_IS_FOLLOW = "is_follow";
    @SerializedName(SERIALIZED_NAME_IS_FOLLOW)
    private Integer isFollow;

    public static final String SERIALIZED_NAME_HAVE_TRADED = "have_traded";
    @SerializedName(SERIALIZED_NAME_HAVE_TRADED)
    private Integer haveTraded;

    public static final String SERIALIZED_NAME_BIZ_UID = "biz_uid";
    @SerializedName(SERIALIZED_NAME_BIZ_UID)
    private String bizUid;

    public static final String SERIALIZED_NAME_BLUE_VIP = "blue_vip";
    @SerializedName(SERIALIZED_NAME_BLUE_VIP)
    private Integer blueVip;

    public static final String SERIALIZED_NAME_WORK_STATUS = "work_status";
    @SerializedName(SERIALIZED_NAME_WORK_STATUS)
    private Integer workStatus;

    public static final String SERIALIZED_NAME_REGISTRATION_DAYS = "registration_days";
    @SerializedName(SERIALIZED_NAME_REGISTRATION_DAYS)
    private Integer registrationDays;

    public static final String SERIALIZED_NAME_FIRST_TRADE_DAYS = "first_trade_days";
    @SerializedName(SERIALIZED_NAME_FIRST_TRADE_DAYS)
    private Integer firstTradeDays;

    public static final String SERIALIZED_NAME_NEED_REPLENISH = "need_replenish";
    @SerializedName(SERIALIZED_NAME_NEED_REPLENISH)
    private Integer needReplenish;

    public static final String SERIALIZED_NAME_MERCHANT_INFO = "merchant_info";
    @SerializedName(SERIALIZED_NAME_MERCHANT_INFO)
    private InlineResponse20014DataMerchantInfo merchantInfo;

    public static final String SERIALIZED_NAME_ONLINE_STATUS = "online_status";
    @SerializedName(SERIALIZED_NAME_ONLINE_STATUS)
    private Integer onlineStatus;

    public static final String SERIALIZED_NAME_WORK_HOURS = "work_hours";
    @SerializedName(SERIALIZED_NAME_WORK_HOURS)
    private Object workHours;

    public static final String SERIALIZED_NAME_TRANSACTIONS_MONTH = "transactions_month";
    @SerializedName(SERIALIZED_NAME_TRANSACTIONS_MONTH)
    private BigDecimal transactionsMonth;

    public static final String SERIALIZED_NAME_TRANSACTIONS_ALL = "transactions_all";
    @SerializedName(SERIALIZED_NAME_TRANSACTIONS_ALL)
    private BigDecimal transactionsAll;

    public static final String SERIALIZED_NAME_TRADE_VERSATILE = "trade_versatile";
    @SerializedName(SERIALIZED_NAME_TRADE_VERSATILE)
    private Boolean tradeVersatile;


    public InlineResponse20014Data isSelf(Boolean isSelf) {
        
        this.isSelf = isSelf;
        return this;
    }

     /**
     * Whether self
     * @return isSelf
    **/
    @javax.annotation.Nullable
    public Boolean getIsSelf() {
        return isSelf;
    }


    public void setIsSelf(Boolean isSelf) {
        this.isSelf = isSelf;
    }

    public InlineResponse20014Data userTimest(String userTimest) {
        
        this.userTimest = userTimest;
        return this;
    }

     /**
     * User registration time (formatted string)
     * @return userTimest
    **/
    @javax.annotation.Nullable
    public String getUserTimest() {
        return userTimest;
    }


    public void setUserTimest(String userTimest) {
        this.userTimest = userTimest;
    }

    public InlineResponse20014Data counterpartiesNum(Integer counterpartiesNum) {
        
        this.counterpartiesNum = counterpartiesNum;
        return this;
    }

     /**
     * Number of counterparties
     * @return counterpartiesNum
    **/
    @javax.annotation.Nullable
    public Integer getCounterpartiesNum() {
        return counterpartiesNum;
    }


    public void setCounterpartiesNum(Integer counterpartiesNum) {
        this.counterpartiesNum = counterpartiesNum;
    }

    public InlineResponse20014Data emailVerified(String emailVerified) {
        
        this.emailVerified = emailVerified;
        return this;
    }

     /**
     * Whether email is verified
     * @return emailVerified
    **/
    @javax.annotation.Nullable
    public String getEmailVerified() {
        return emailVerified;
    }


    public void setEmailVerified(String emailVerified) {
        this.emailVerified = emailVerified;
    }

    public InlineResponse20014Data verified(String verified) {
        
        this.verified = verified;
        return this;
    }

     /**
     * Whether KYC verification is completed
     * @return verified
    **/
    @javax.annotation.Nullable
    public String getVerified() {
        return verified;
    }


    public void setVerified(String verified) {
        this.verified = verified;
    }

    public InlineResponse20014Data hasPhone(String hasPhone) {
        
        this.hasPhone = hasPhone;
        return this;
    }

     /**
     * Whether phone is bound
     * @return hasPhone
    **/
    @javax.annotation.Nullable
    public String getHasPhone() {
        return hasPhone;
    }


    public void setHasPhone(String hasPhone) {
        this.hasPhone = hasPhone;
    }

    public InlineResponse20014Data userName(String userName) {
        
        this.userName = userName;
        return this;
    }

     /**
     * Username
     * @return userName
    **/
    @javax.annotation.Nullable
    public String getUserName() {
        return userName;
    }


    public void setUserName(String userName) {
        this.userName = userName;
    }

    public InlineResponse20014Data userNote(String userNote) {
        
        this.userNote = userNote;
        return this;
    }

     /**
     * User note information
     * @return userNote
    **/
    @javax.annotation.Nullable
    public String getUserNote() {
        return userNote;
    }


    public void setUserNote(String userNote) {
        this.userNote = userNote;
    }

    public InlineResponse20014Data completeTransactions(String completeTransactions) {
        
        this.completeTransactions = completeTransactions;
        return this;
    }

     /**
     * Total completed orders
     * @return completeTransactions
    **/
    @javax.annotation.Nullable
    public String getCompleteTransactions() {
        return completeTransactions;
    }


    public void setCompleteTransactions(String completeTransactions) {
        this.completeTransactions = completeTransactions;
    }

    public InlineResponse20014Data paidTransactions(String paidTransactions) {
        
        this.paidTransactions = paidTransactions;
        return this;
    }

     /**
     * Number of completed buy orders
     * @return paidTransactions
    **/
    @javax.annotation.Nullable
    public String getPaidTransactions() {
        return paidTransactions;
    }


    public void setPaidTransactions(String paidTransactions) {
        this.paidTransactions = paidTransactions;
    }

    public InlineResponse20014Data acceptedTransactions(String acceptedTransactions) {
        
        this.acceptedTransactions = acceptedTransactions;
        return this;
    }

     /**
     * Number of completed sell orders
     * @return acceptedTransactions
    **/
    @javax.annotation.Nullable
    public String getAcceptedTransactions() {
        return acceptedTransactions;
    }


    public void setAcceptedTransactions(String acceptedTransactions) {
        this.acceptedTransactions = acceptedTransactions;
    }

    public InlineResponse20014Data transactionsUsedTime(String transactionsUsedTime) {
        
        this.transactionsUsedTime = transactionsUsedTime;
        return this;
    }

     /**
     * Average time to confirm receipt
     * @return transactionsUsedTime
    **/
    @javax.annotation.Nullable
    public String getTransactionsUsedTime() {
        return transactionsUsedTime;
    }


    public void setTransactionsUsedTime(String transactionsUsedTime) {
        this.transactionsUsedTime = transactionsUsedTime;
    }

    public InlineResponse20014Data cancelledUsedTimeMonth(String cancelledUsedTimeMonth) {
        
        this.cancelledUsedTimeMonth = cancelledUsedTimeMonth;
        return this;
    }

     /**
     * Cancellation time in last 30 days
     * @return cancelledUsedTimeMonth
    **/
    @javax.annotation.Nullable
    public String getCancelledUsedTimeMonth() {
        return cancelledUsedTimeMonth;
    }


    public void setCancelledUsedTimeMonth(String cancelledUsedTimeMonth) {
        this.cancelledUsedTimeMonth = cancelledUsedTimeMonth;
    }

    public InlineResponse20014Data completeTransactionsMonth(String completeTransactionsMonth) {
        
        this.completeTransactionsMonth = completeTransactionsMonth;
        return this;
    }

     /**
     * Number of completed orders in last 30 days
     * @return completeTransactionsMonth
    **/
    @javax.annotation.Nullable
    public String getCompleteTransactionsMonth() {
        return completeTransactionsMonth;
    }


    public void setCompleteTransactionsMonth(String completeTransactionsMonth) {
        this.completeTransactionsMonth = completeTransactionsMonth;
    }

    public InlineResponse20014Data completeRateMonth(BigDecimal completeRateMonth) {
        
        this.completeRateMonth = completeRateMonth;
        return this;
    }

     /**
     * Completion rate in last 30 days
     * @return completeRateMonth
    **/
    @javax.annotation.Nullable
    public BigDecimal getCompleteRateMonth() {
        return completeRateMonth;
    }


    public void setCompleteRateMonth(BigDecimal completeRateMonth) {
        this.completeRateMonth = completeRateMonth;
    }

    public InlineResponse20014Data ordersBuyRateMonth(BigDecimal ordersBuyRateMonth) {
        
        this.ordersBuyRateMonth = ordersBuyRateMonth;
        return this;
    }

     /**
     * Buy order ratio in last 30 days
     * @return ordersBuyRateMonth
    **/
    @javax.annotation.Nullable
    public BigDecimal getOrdersBuyRateMonth() {
        return ordersBuyRateMonth;
    }


    public void setOrdersBuyRateMonth(BigDecimal ordersBuyRateMonth) {
        this.ordersBuyRateMonth = ordersBuyRateMonth;
    }

    public InlineResponse20014Data isBlack(Integer isBlack) {
        
        this.isBlack = isBlack;
        return this;
    }

     /**
     * Whether blocked
     * @return isBlack
    **/
    @javax.annotation.Nullable
    public Integer getIsBlack() {
        return isBlack;
    }


    public void setIsBlack(Integer isBlack) {
        this.isBlack = isBlack;
    }

    public InlineResponse20014Data isFollow(Integer isFollow) {
        
        this.isFollow = isFollow;
        return this;
    }

     /**
     * Whether following
     * @return isFollow
    **/
    @javax.annotation.Nullable
    public Integer getIsFollow() {
        return isFollow;
    }


    public void setIsFollow(Integer isFollow) {
        this.isFollow = isFollow;
    }

    public InlineResponse20014Data haveTraded(Integer haveTraded) {
        
        this.haveTraded = haveTraded;
        return this;
    }

     /**
     * Whether traded with self
     * @return haveTraded
    **/
    @javax.annotation.Nullable
    public Integer getHaveTraded() {
        return haveTraded;
    }


    public void setHaveTraded(Integer haveTraded) {
        this.haveTraded = haveTraded;
    }

    public InlineResponse20014Data bizUid(String bizUid) {
        
        this.bizUid = bizUid;
        return this;
    }

     /**
     * Encrypted UID
     * @return bizUid
    **/
    @javax.annotation.Nullable
    public String getBizUid() {
        return bizUid;
    }


    public void setBizUid(String bizUid) {
        this.bizUid = bizUid;
    }

    public InlineResponse20014Data blueVip(Integer blueVip) {
        
        this.blueVip = blueVip;
        return this;
    }

     /**
     * Blue V Crown Shield
     * @return blueVip
    **/
    @javax.annotation.Nullable
    public Integer getBlueVip() {
        return blueVip;
    }


    public void setBlueVip(Integer blueVip) {
        this.blueVip = blueVip;
    }

    public InlineResponse20014Data workStatus(Integer workStatus) {
        
        this.workStatus = workStatus;
        return this;
    }

     /**
     * Merchant work status
     * @return workStatus
    **/
    @javax.annotation.Nullable
    public Integer getWorkStatus() {
        return workStatus;
    }


    public void setWorkStatus(Integer workStatus) {
        this.workStatus = workStatus;
    }

    public InlineResponse20014Data registrationDays(Integer registrationDays) {
        
        this.registrationDays = registrationDays;
        return this;
    }

     /**
     * Registration days
     * @return registrationDays
    **/
    @javax.annotation.Nullable
    public Integer getRegistrationDays() {
        return registrationDays;
    }


    public void setRegistrationDays(Integer registrationDays) {
        this.registrationDays = registrationDays;
    }

    public InlineResponse20014Data firstTradeDays(Integer firstTradeDays) {
        
        this.firstTradeDays = firstTradeDays;
        return this;
    }

     /**
     * Days since first trade
     * @return firstTradeDays
    **/
    @javax.annotation.Nullable
    public Integer getFirstTradeDays() {
        return firstTradeDays;
    }


    public void setFirstTradeDays(Integer firstTradeDays) {
        this.firstTradeDays = firstTradeDays;
    }

    public InlineResponse20014Data needReplenish(Integer needReplenish) {
        
        this.needReplenish = needReplenish;
        return this;
    }

     /**
     * Whether margin replenishment is needed
     * @return needReplenish
    **/
    @javax.annotation.Nullable
    public Integer getNeedReplenish() {
        return needReplenish;
    }


    public void setNeedReplenish(Integer needReplenish) {
        this.needReplenish = needReplenish;
    }

    public InlineResponse20014Data merchantInfo(InlineResponse20014DataMerchantInfo merchantInfo) {
        
        this.merchantInfo = merchantInfo;
        return this;
    }

     /**
     * Get merchantInfo
     * @return merchantInfo
    **/
    @javax.annotation.Nullable
    public InlineResponse20014DataMerchantInfo getMerchantInfo() {
        return merchantInfo;
    }


    public void setMerchantInfo(InlineResponse20014DataMerchantInfo merchantInfo) {
        this.merchantInfo = merchantInfo;
    }

    public InlineResponse20014Data onlineStatus(Integer onlineStatus) {
        
        this.onlineStatus = onlineStatus;
        return this;
    }

     /**
     * Merchant online status
     * @return onlineStatus
    **/
    @javax.annotation.Nullable
    public Integer getOnlineStatus() {
        return onlineStatus;
    }


    public void setOnlineStatus(Integer onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    public InlineResponse20014Data workHours(Object workHours) {
        
        this.workHours = workHours;
        return this;
    }

     /**
     * Merchant online status details
     * @return workHours
    **/
    @javax.annotation.Nullable
    public Object getWorkHours() {
        return workHours;
    }


    public void setWorkHours(Object workHours) {
        this.workHours = workHours;
    }

    public InlineResponse20014Data transactionsMonth(BigDecimal transactionsMonth) {
        
        this.transactionsMonth = transactionsMonth;
        return this;
    }

     /**
     * 30-day transaction volume
     * @return transactionsMonth
    **/
    @javax.annotation.Nullable
    public BigDecimal getTransactionsMonth() {
        return transactionsMonth;
    }


    public void setTransactionsMonth(BigDecimal transactionsMonth) {
        this.transactionsMonth = transactionsMonth;
    }

    public InlineResponse20014Data transactionsAll(BigDecimal transactionsAll) {
        
        this.transactionsAll = transactionsAll;
        return this;
    }

     /**
     * Total transaction volume
     * @return transactionsAll
    **/
    @javax.annotation.Nullable
    public BigDecimal getTransactionsAll() {
        return transactionsAll;
    }


    public void setTransactionsAll(BigDecimal transactionsAll) {
        this.transactionsAll = transactionsAll;
    }

    public InlineResponse20014Data tradeVersatile(Boolean tradeVersatile) {
        
        this.tradeVersatile = tradeVersatile;
        return this;
    }

     /**
     * Single user or composite user
     * @return tradeVersatile
    **/
    @javax.annotation.Nullable
    public Boolean getTradeVersatile() {
        return tradeVersatile;
    }


    public void setTradeVersatile(Boolean tradeVersatile) {
        this.tradeVersatile = tradeVersatile;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20014Data inlineResponse20014Data = (InlineResponse20014Data) o;
        return Objects.equals(this.isSelf, inlineResponse20014Data.isSelf) &&
                Objects.equals(this.userTimest, inlineResponse20014Data.userTimest) &&
                Objects.equals(this.counterpartiesNum, inlineResponse20014Data.counterpartiesNum) &&
                Objects.equals(this.emailVerified, inlineResponse20014Data.emailVerified) &&
                Objects.equals(this.verified, inlineResponse20014Data.verified) &&
                Objects.equals(this.hasPhone, inlineResponse20014Data.hasPhone) &&
                Objects.equals(this.userName, inlineResponse20014Data.userName) &&
                Objects.equals(this.userNote, inlineResponse20014Data.userNote) &&
                Objects.equals(this.completeTransactions, inlineResponse20014Data.completeTransactions) &&
                Objects.equals(this.paidTransactions, inlineResponse20014Data.paidTransactions) &&
                Objects.equals(this.acceptedTransactions, inlineResponse20014Data.acceptedTransactions) &&
                Objects.equals(this.transactionsUsedTime, inlineResponse20014Data.transactionsUsedTime) &&
                Objects.equals(this.cancelledUsedTimeMonth, inlineResponse20014Data.cancelledUsedTimeMonth) &&
                Objects.equals(this.completeTransactionsMonth, inlineResponse20014Data.completeTransactionsMonth) &&
                Objects.equals(this.completeRateMonth, inlineResponse20014Data.completeRateMonth) &&
                Objects.equals(this.ordersBuyRateMonth, inlineResponse20014Data.ordersBuyRateMonth) &&
                Objects.equals(this.isBlack, inlineResponse20014Data.isBlack) &&
                Objects.equals(this.isFollow, inlineResponse20014Data.isFollow) &&
                Objects.equals(this.haveTraded, inlineResponse20014Data.haveTraded) &&
                Objects.equals(this.bizUid, inlineResponse20014Data.bizUid) &&
                Objects.equals(this.blueVip, inlineResponse20014Data.blueVip) &&
                Objects.equals(this.workStatus, inlineResponse20014Data.workStatus) &&
                Objects.equals(this.registrationDays, inlineResponse20014Data.registrationDays) &&
                Objects.equals(this.firstTradeDays, inlineResponse20014Data.firstTradeDays) &&
                Objects.equals(this.needReplenish, inlineResponse20014Data.needReplenish) &&
                Objects.equals(this.merchantInfo, inlineResponse20014Data.merchantInfo) &&
                Objects.equals(this.onlineStatus, inlineResponse20014Data.onlineStatus) &&
                Objects.equals(this.workHours, inlineResponse20014Data.workHours) &&
                Objects.equals(this.transactionsMonth, inlineResponse20014Data.transactionsMonth) &&
                Objects.equals(this.transactionsAll, inlineResponse20014Data.transactionsAll) &&
                Objects.equals(this.tradeVersatile, inlineResponse20014Data.tradeVersatile);
    }

    @Override
    public int hashCode() {
        return Objects.hash(isSelf, userTimest, counterpartiesNum, emailVerified, verified, hasPhone, userName, userNote, completeTransactions, paidTransactions, acceptedTransactions, transactionsUsedTime, cancelledUsedTimeMonth, completeTransactionsMonth, completeRateMonth, ordersBuyRateMonth, isBlack, isFollow, haveTraded, bizUid, blueVip, workStatus, registrationDays, firstTradeDays, needReplenish, merchantInfo, onlineStatus, workHours, transactionsMonth, transactionsAll, tradeVersatile);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20014Data {\n");
        sb.append("      isSelf: ").append(toIndentedString(isSelf)).append("\n");
        sb.append("      userTimest: ").append(toIndentedString(userTimest)).append("\n");
        sb.append("      counterpartiesNum: ").append(toIndentedString(counterpartiesNum)).append("\n");
        sb.append("      emailVerified: ").append(toIndentedString(emailVerified)).append("\n");
        sb.append("      verified: ").append(toIndentedString(verified)).append("\n");
        sb.append("      hasPhone: ").append(toIndentedString(hasPhone)).append("\n");
        sb.append("      userName: ").append(toIndentedString(userName)).append("\n");
        sb.append("      userNote: ").append(toIndentedString(userNote)).append("\n");
        sb.append("      completeTransactions: ").append(toIndentedString(completeTransactions)).append("\n");
        sb.append("      paidTransactions: ").append(toIndentedString(paidTransactions)).append("\n");
        sb.append("      acceptedTransactions: ").append(toIndentedString(acceptedTransactions)).append("\n");
        sb.append("      transactionsUsedTime: ").append(toIndentedString(transactionsUsedTime)).append("\n");
        sb.append("      cancelledUsedTimeMonth: ").append(toIndentedString(cancelledUsedTimeMonth)).append("\n");
        sb.append("      completeTransactionsMonth: ").append(toIndentedString(completeTransactionsMonth)).append("\n");
        sb.append("      completeRateMonth: ").append(toIndentedString(completeRateMonth)).append("\n");
        sb.append("      ordersBuyRateMonth: ").append(toIndentedString(ordersBuyRateMonth)).append("\n");
        sb.append("      isBlack: ").append(toIndentedString(isBlack)).append("\n");
        sb.append("      isFollow: ").append(toIndentedString(isFollow)).append("\n");
        sb.append("      haveTraded: ").append(toIndentedString(haveTraded)).append("\n");
        sb.append("      bizUid: ").append(toIndentedString(bizUid)).append("\n");
        sb.append("      blueVip: ").append(toIndentedString(blueVip)).append("\n");
        sb.append("      workStatus: ").append(toIndentedString(workStatus)).append("\n");
        sb.append("      registrationDays: ").append(toIndentedString(registrationDays)).append("\n");
        sb.append("      firstTradeDays: ").append(toIndentedString(firstTradeDays)).append("\n");
        sb.append("      needReplenish: ").append(toIndentedString(needReplenish)).append("\n");
        sb.append("      merchantInfo: ").append(toIndentedString(merchantInfo)).append("\n");
        sb.append("      onlineStatus: ").append(toIndentedString(onlineStatus)).append("\n");
        sb.append("      workHours: ").append(toIndentedString(workHours)).append("\n");
        sb.append("      transactionsMonth: ").append(toIndentedString(transactionsMonth)).append("\n");
        sb.append("      transactionsAll: ").append(toIndentedString(transactionsAll)).append("\n");
        sb.append("      tradeVersatile: ").append(toIndentedString(tradeVersatile)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

