/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.InlineResponse20017DataList;
import io.gate.gateapi.models.InlineResponse20017DataTransTime;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20017Data
 */
public class InlineResponse20017Data {
    public static final String SERIALIZED_NAME_LIST = "list";
    @SerializedName(SERIALIZED_NAME_LIST)
    private List<InlineResponse20017DataList> list = new ArrayList<>();

    public static final String SERIALIZED_NAME_TRANS_TIME = "trans_time";
    @SerializedName(SERIALIZED_NAME_TRANS_TIME)
    private List<InlineResponse20017DataTransTime> transTime = new ArrayList<>();

    public static final String SERIALIZED_NAME_COUNT = "count";
    @SerializedName(SERIALIZED_NAME_COUNT)
    private Integer count;

    public static final String SERIALIZED_NAME_EXPORTED_NUM = "exported_num";
    @SerializedName(SERIALIZED_NAME_EXPORTED_NUM)
    private Integer exportedNum;


    public InlineResponse20017Data list(List<InlineResponse20017DataList> list) {
        
        this.list = list;
        return this;
    }

    public InlineResponse20017Data addListItem(InlineResponse20017DataList listItem) {
        this.list.add(listItem);
        return this;
    }

     /**
     * Get list
     * @return list
    **/
    public List<InlineResponse20017DataList> getList() {
        return list;
    }


    public void setList(List<InlineResponse20017DataList> list) {
        this.list = list;
    }

    public InlineResponse20017Data transTime(List<InlineResponse20017DataTransTime> transTime) {
        
        this.transTime = transTime;
        return this;
    }

    public InlineResponse20017Data addTransTimeItem(InlineResponse20017DataTransTime transTimeItem) {
        this.transTime.add(transTimeItem);
        return this;
    }

     /**
     * Countdown time
     * @return transTime
    **/
    public List<InlineResponse20017DataTransTime> getTransTime() {
        return transTime;
    }


    public void setTransTime(List<InlineResponse20017DataTransTime> transTime) {
        this.transTime = transTime;
    }

    public InlineResponse20017Data count(Integer count) {
        
        this.count = count;
        return this;
    }

     /**
     * Number of orders
     * @return count
    **/
    public Integer getCount() {
        return count;
    }


    public void setCount(Integer count) {
        this.count = count;
    }

    public InlineResponse20017Data exportedNum(Integer exportedNum) {
        
        this.exportedNum = exportedNum;
        return this;
    }

     /**
     * Export count
     * @return exportedNum
    **/
    public Integer getExportedNum() {
        return exportedNum;
    }


    public void setExportedNum(Integer exportedNum) {
        this.exportedNum = exportedNum;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20017Data inlineResponse20017Data = (InlineResponse20017Data) o;
        return Objects.equals(this.list, inlineResponse20017Data.list) &&
                Objects.equals(this.transTime, inlineResponse20017Data.transTime) &&
                Objects.equals(this.count, inlineResponse20017Data.count) &&
                Objects.equals(this.exportedNum, inlineResponse20017Data.exportedNum);
    }

    @Override
    public int hashCode() {
        return Objects.hash(list, transTime, count, exportedNum);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20017Data {\n");
        sb.append("      list: ").append(toIndentedString(list)).append("\n");
        sb.append("      transTime: ").append(toIndentedString(transTime)).append("\n");
        sb.append("      count: ").append(toIndentedString(count)).append("\n");
        sb.append("      exportedNum: ").append(toIndentedString(exportedNum)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

