/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.InlineResponse20010DataLive;
import io.gate.gateapi.models.InlineResponse20010DataVideo;
import java.io.IOException;

/**
 * InlineResponse20010DataList
 */
public class InlineResponse20010DataList {
    public static final String SERIALIZED_NAME_CONTENT_TYPE = "content_type";
    @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
    private String contentType;

    public static final String SERIALIZED_NAME_LIVE = "live";
    @SerializedName(SERIALIZED_NAME_LIVE)
    private InlineResponse20010DataLive live;

    public static final String SERIALIZED_NAME_VIDEO = "video";
    @SerializedName(SERIALIZED_NAME_VIDEO)
    private InlineResponse20010DataVideo video;


    public InlineResponse20010DataList contentType(String contentType) {
        
        this.contentType = contentType;
        return this;
    }

     /**
     * Content type: streaming &#x3D; live broadcast, video &#x3D; replay video
     * @return contentType
    **/
    @javax.annotation.Nullable
    public String getContentType() {
        return contentType;
    }


    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public InlineResponse20010DataList live(InlineResponse20010DataLive live) {
        
        this.live = live;
        return this;
    }

     /**
     * Get live
     * @return live
    **/
    @javax.annotation.Nullable
    public InlineResponse20010DataLive getLive() {
        return live;
    }


    public void setLive(InlineResponse20010DataLive live) {
        this.live = live;
    }

    public InlineResponse20010DataList video(InlineResponse20010DataVideo video) {
        
        this.video = video;
        return this;
    }

     /**
     * Get video
     * @return video
    **/
    @javax.annotation.Nullable
    public InlineResponse20010DataVideo getVideo() {
        return video;
    }


    public void setVideo(InlineResponse20010DataVideo video) {
        this.video = video;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20010DataList inlineResponse20010DataList = (InlineResponse20010DataList) o;
        return Objects.equals(this.contentType, inlineResponse20010DataList.contentType) &&
                Objects.equals(this.live, inlineResponse20010DataList.live) &&
                Objects.equals(this.video, inlineResponse20010DataList.video);
    }

    @Override
    public int hashCode() {
        return Objects.hash(contentType, live, video);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20010DataList {\n");
        sb.append("      contentType: ").append(toIndentedString(contentType)).append("\n");
        sb.append("      live: ").append(toIndentedString(live)).append("\n");
        sb.append("      video: ").append(toIndentedString(video)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

