/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20018Data
 */
public class InlineResponse20018Data {
    public static final String SERIALIZED_NAME_IS_SELL = "is_sell";
    @SerializedName(SERIALIZED_NAME_IS_SELL)
    private Integer isSell;

    public static final String SERIALIZED_NAME_TXID = "txid";
    @SerializedName(SERIALIZED_NAME_TXID)
    private Integer txid;

    public static final String SERIALIZED_NAME_ORDERID = "orderid";
    @SerializedName(SERIALIZED_NAME_ORDERID)
    private Integer orderid;

    public static final String SERIALIZED_NAME_TIMEST = "timest";
    @SerializedName(SERIALIZED_NAME_TIMEST)
    private Integer timest;

    public static final String SERIALIZED_NAME_LAST_PAY_TIME = "last_pay_time";
    @SerializedName(SERIALIZED_NAME_LAST_PAY_TIME)
    private Integer lastPayTime;

    public static final String SERIALIZED_NAME_REMAIN_PAY_TIME = "remain_pay_time";
    @SerializedName(SERIALIZED_NAME_REMAIN_PAY_TIME)
    private Integer remainPayTime;

    public static final String SERIALIZED_NAME_CURRENCY_TYPE = "currencyType";
    @SerializedName(SERIALIZED_NAME_CURRENCY_TYPE)
    private String currencyType;

    public static final String SERIALIZED_NAME_WANT_TYPE = "want_type";
    @SerializedName(SERIALIZED_NAME_WANT_TYPE)
    private String wantType;

    public static final String SERIALIZED_NAME_RATE = "rate";
    @SerializedName(SERIALIZED_NAME_RATE)
    private String rate;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;

    public static final String SERIALIZED_NAME_TOTAL = "total";
    @SerializedName(SERIALIZED_NAME_TOTAL)
    private String total;

    public static final String SERIALIZED_NAME_STATUS = "status";
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;

    public static final String SERIALIZED_NAME_REASON_ID = "reason_id";
    @SerializedName(SERIALIZED_NAME_REASON_ID)
    private String reasonId;

    public static final String SERIALIZED_NAME_REASON_DESC = "reason_desc";
    @SerializedName(SERIALIZED_NAME_REASON_DESC)
    private String reasonDesc;

    public static final String SERIALIZED_NAME_TOAST_ID = "toast_id";
    @SerializedName(SERIALIZED_NAME_TOAST_ID)
    private Integer toastId;

    public static final String SERIALIZED_NAME_CANCEL_TIME = "cancel_time";
    @SerializedName(SERIALIZED_NAME_CANCEL_TIME)
    private String cancelTime;

    public static final String SERIALIZED_NAME_SELLER_CONFIRM = "seller_confirm";
    @SerializedName(SERIALIZED_NAME_SELLER_CONFIRM)
    private Integer sellerConfirm;

    public static final String SERIALIZED_NAME_IN_APPEAL = "in_appeal";
    @SerializedName(SERIALIZED_NAME_IN_APPEAL)
    private Integer inAppeal;

    public static final String SERIALIZED_NAME_DISPUTE_TIME = "dispute_time";
    @SerializedName(SERIALIZED_NAME_DISPUTE_TIME)
    private Integer disputeTime;

    public static final String SERIALIZED_NAME_CANCELABLE = "cancelable";
    @SerializedName(SERIALIZED_NAME_CANCELABLE)
    private Integer cancelable;

    public static final String SERIALIZED_NAME_HIDE_PAYMENT = "hide_payment";
    @SerializedName(SERIALIZED_NAME_HIDE_PAYMENT)
    private Integer hidePayment;

    public static final String SERIALIZED_NAME_TRADE_TIPS = "trade_tips";
    @SerializedName(SERIALIZED_NAME_TRADE_TIPS)
    private String tradeTips;

    public static final String SERIALIZED_NAME_SHOW_BANK = "show_bank";
    @SerializedName(SERIALIZED_NAME_SHOW_BANK)
    private String showBank;

    public static final String SERIALIZED_NAME_BANKNAME = "bankname";
    @SerializedName(SERIALIZED_NAME_BANKNAME)
    private String bankname;

    public static final String SERIALIZED_NAME_BANKBRANCH = "bankbranch";
    @SerializedName(SERIALIZED_NAME_BANKBRANCH)
    private String bankbranch;

    public static final String SERIALIZED_NAME_BANKID = "bankid";
    @SerializedName(SERIALIZED_NAME_BANKID)
    private String bankid;

    public static final String SERIALIZED_NAME_BANK_HOLDER_REALNAME = "bank_holder_realname";
    @SerializedName(SERIALIZED_NAME_BANK_HOLDER_REALNAME)
    private String bankHolderRealname;

    public static final String SERIALIZED_NAME_SHOW_ALI = "show_ali";
    @SerializedName(SERIALIZED_NAME_SHOW_ALI)
    private String showAli;

    public static final String SERIALIZED_NAME_ALINAME = "aliname";
    @SerializedName(SERIALIZED_NAME_ALINAME)
    private String aliname;

    public static final String SERIALIZED_NAME_IS_ALICODE = "is_alicode";
    @SerializedName(SERIALIZED_NAME_IS_ALICODE)
    private Integer isAlicode;

    public static final String SERIALIZED_NAME_SHOW_WECHAT = "show_wechat";
    @SerializedName(SERIALIZED_NAME_SHOW_WECHAT)
    private String showWechat;

    public static final String SERIALIZED_NAME_WENAME = "wename";
    @SerializedName(SERIALIZED_NAME_WENAME)
    private String wename;

    public static final String SERIALIZED_NAME_SHOW_OTHERS = "show_others";
    @SerializedName(SERIALIZED_NAME_SHOW_OTHERS)
    private String showOthers;

    public static final String SERIALIZED_NAME_PAY_OTHERS = "pay_others";
    @SerializedName(SERIALIZED_NAME_PAY_OTHERS)
    private List<String> payOthers = new ArrayList<>();

    public static final String SERIALIZED_NAME_SEL_PAYTYPE = "sel_paytype";
    @SerializedName(SERIALIZED_NAME_SEL_PAYTYPE)
    private String selPaytype;

    public static final String SERIALIZED_NAME_ITS_UID = "its_uid";
    @SerializedName(SERIALIZED_NAME_ITS_UID)
    private String itsUid;

    public static final String SERIALIZED_NAME_ITS_IS_BLUE_VIP = "its_is_blue_vip";
    @SerializedName(SERIALIZED_NAME_ITS_IS_BLUE_VIP)
    private Integer itsIsBlueVip;

    public static final String SERIALIZED_NAME_ITS_TIER = "its_tier";
    @SerializedName(SERIALIZED_NAME_ITS_TIER)
    private Integer itsTier;

    public static final String SERIALIZED_NAME_ITS_AVATAR = "its_avatar";
    @SerializedName(SERIALIZED_NAME_ITS_AVATAR)
    private String itsAvatar;

    public static final String SERIALIZED_NAME_ITS_NICKNAME = "its_nickname";
    @SerializedName(SERIALIZED_NAME_ITS_NICKNAME)
    private String itsNickname;

    public static final String SERIALIZED_NAME_ITS_REALNAME = "its_realname";
    @SerializedName(SERIALIZED_NAME_ITS_REALNAME)
    private String itsRealname;

    public static final String SERIALIZED_NAME_IS_FOLLOW = "is_follow";
    @SerializedName(SERIALIZED_NAME_IS_FOLLOW)
    private Integer isFollow;

    public static final String SERIALIZED_NAME_IS_BLACK = "is_black";
    @SerializedName(SERIALIZED_NAME_IS_BLACK)
    private Integer isBlack;

    public static final String SERIALIZED_NAME_HAVE_TRADED = "have_traded";
    @SerializedName(SERIALIZED_NAME_HAVE_TRADED)
    private Integer haveTraded;

    public static final String SERIALIZED_NAME_APPEAL_UNREAD = "appeal_unread";
    @SerializedName(SERIALIZED_NAME_APPEAL_UNREAD)
    private Integer appealUnread;

    public static final String SERIALIZED_NAME_APPEAL_ALLOW_CANCEL = "appeal_allow_cancel";
    @SerializedName(SERIALIZED_NAME_APPEAL_ALLOW_CANCEL)
    private Integer appealAllowCancel;

    public static final String SERIALIZED_NAME_APPEAL_VERDICT_HAS_OPEN = "appeal_verdict_has_open";
    @SerializedName(SERIALIZED_NAME_APPEAL_VERDICT_HAS_OPEN)
    private String appealVerdictHasOpen;

    public static final String SERIALIZED_NAME_IM_UNREAD = "im_unread";
    @SerializedName(SERIALIZED_NAME_IM_UNREAD)
    private Integer imUnread;

    public static final String SERIALIZED_NAME_MESSAGE = "message";
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    private String message;

    public static final String SERIALIZED_NAME_SCORE = "score";
    @SerializedName(SERIALIZED_NAME_SCORE)
    private String score;

    public static final String SERIALIZED_NAME_PAYMENT_VOUCHER_URL = "payment_voucher_url";
    @SerializedName(SERIALIZED_NAME_PAYMENT_VOUCHER_URL)
    private List<String> paymentVoucherUrl = new ArrayList<>();

    public static final String SERIALIZED_NAME_COMPLETE_NUMBER = "complete_number";
    @SerializedName(SERIALIZED_NAME_COMPLETE_NUMBER)
    private Integer completeNumber;

    public static final String SERIALIZED_NAME_COMPLETE_RATE_MONTH = "complete_rate_month";
    @SerializedName(SERIALIZED_NAME_COMPLETE_RATE_MONTH)
    private String completeRateMonth;

    public static final String SERIALIZED_NAME_CHECK_JOURNAL_ACCOUNT = "check_journal_account";
    @SerializedName(SERIALIZED_NAME_CHECK_JOURNAL_ACCOUNT)
    private Boolean checkJournalAccount;

    public static final String SERIALIZED_NAME_SHOW_JOURNAL_ACCOUNT = "show_journal_account";
    @SerializedName(SERIALIZED_NAME_SHOW_JOURNAL_ACCOUNT)
    private Boolean showJournalAccount;

    public static final String SERIALIZED_NAME_IS_FREEZE_GUARANTEE = "is_freeze_guarantee";
    @SerializedName(SERIALIZED_NAME_IS_FREEZE_GUARANTEE)
    private Integer isFreezeGuarantee;

    public static final String SERIALIZED_NAME_USDT_LEFT_GUARANTEE = "usdt_left_guarantee";
    @SerializedName(SERIALIZED_NAME_USDT_LEFT_GUARANTEE)
    private String usdtLeftGuarantee;

    public static final String SERIALIZED_NAME_GUARANTEE_CURR_TYPE = "guarantee_curr_type";
    @SerializedName(SERIALIZED_NAME_GUARANTEE_CURR_TYPE)
    private String guaranteeCurrType;

    public static final String SERIALIZED_NAME_TIMEST_PAID = "timest_paid";
    @SerializedName(SERIALIZED_NAME_TIMEST_PAID)
    private Integer timestPaid;

    public static final String SERIALIZED_NAME_STATE = "state";
    @SerializedName(SERIALIZED_NAME_STATE)
    private String state;

    public static final String SERIALIZED_NAME_RELEASE_COIN_SWITCH = "release_coin_switch";
    @SerializedName(SERIALIZED_NAME_RELEASE_COIN_SWITCH)
    private Integer releaseCoinSwitch;

    public static final String SERIALIZED_NAME_OWN_REALNAME = "own_realname";
    @SerializedName(SERIALIZED_NAME_OWN_REALNAME)
    private String ownRealname;

    public static final String SERIALIZED_NAME_CONFIRMATION_USE_TIME_MONTH = "confirmation_use_time_month";
    @SerializedName(SERIALIZED_NAME_CONFIRMATION_USE_TIME_MONTH)
    private Integer confirmationUseTimeMonth;

    public static final String SERIALIZED_NAME_IS_RISK_USER = "is_risk_user";
    @SerializedName(SERIALIZED_NAME_IS_RISK_USER)
    private Integer isRiskUser;

    public static final String SERIALIZED_NAME_IS_XT = "is_xt";
    @SerializedName(SERIALIZED_NAME_IS_XT)
    private Integer isXt;

    public static final String SERIALIZED_NAME_ORDER_TYPE = "order_type";
    @SerializedName(SERIALIZED_NAME_ORDER_TYPE)
    private Integer orderType;

    public static final String SERIALIZED_NAME_SYMBOL = "symbol";
    @SerializedName(SERIALIZED_NAME_SYMBOL)
    private String symbol;

    public static final String SERIALIZED_NAME_IS_SHOW_RECEIVE = "is_show_receive";
    @SerializedName(SERIALIZED_NAME_IS_SHOW_RECEIVE)
    private Integer isShowReceive;

    public static final String SERIALIZED_NAME_IS_TAKER = "is_taker";
    @SerializedName(SERIALIZED_NAME_IS_TAKER)
    private Integer isTaker;

    public static final String SERIALIZED_NAME_IS_ONLINE = "is_online";
    @SerializedName(SERIALIZED_NAME_IS_ONLINE)
    private Integer isOnline;

    public static final String SERIALIZED_NAME_SHOW_SELLER_CONTACT_INFO = "show_seller_contact_info";
    @SerializedName(SERIALIZED_NAME_SHOW_SELLER_CONTACT_INFO)
    private Boolean showSellerContactInfo;

    public static final String SERIALIZED_NAME_SUPPORTED_PAY_TYPES = "supported_pay_types";
    @SerializedName(SERIALIZED_NAME_SUPPORTED_PAY_TYPES)
    private List<String> supportedPayTypes = new ArrayList<>();


    public InlineResponse20018Data isSell(Integer isSell) {
        
        this.isSell = isSell;
        return this;
    }

     /**
     * Whether sell order
     * @return isSell
    **/
    public Integer getIsSell() {
        return isSell;
    }


    public void setIsSell(Integer isSell) {
        this.isSell = isSell;
    }

    public InlineResponse20018Data txid(Integer txid) {
        
        this.txid = txid;
        return this;
    }

     /**
     * Order ID
     * @return txid
    **/
    public Integer getTxid() {
        return txid;
    }


    public void setTxid(Integer txid) {
        this.txid = txid;
    }

    public InlineResponse20018Data orderid(Integer orderid) {
        
        this.orderid = orderid;
        return this;
    }

     /**
     * Order ID
     * @return orderid
    **/
    public Integer getOrderid() {
        return orderid;
    }


    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    public InlineResponse20018Data timest(Integer timest) {
        
        this.timest = timest;
        return this;
    }

     /**
     * Order creation timestamp
     * @return timest
    **/
    public Integer getTimest() {
        return timest;
    }


    public void setTimest(Integer timest) {
        this.timest = timest;
    }

    public InlineResponse20018Data lastPayTime(Integer lastPayTime) {
        
        this.lastPayTime = lastPayTime;
        return this;
    }

     /**
     * Payment deadline
     * @return lastPayTime
    **/
    public Integer getLastPayTime() {
        return lastPayTime;
    }


    public void setLastPayTime(Integer lastPayTime) {
        this.lastPayTime = lastPayTime;
    }

    public InlineResponse20018Data remainPayTime(Integer remainPayTime) {
        
        this.remainPayTime = remainPayTime;
        return this;
    }

     /**
     * Remaining payment time
     * @return remainPayTime
    **/
    public Integer getRemainPayTime() {
        return remainPayTime;
    }


    public void setRemainPayTime(Integer remainPayTime) {
        this.remainPayTime = remainPayTime;
    }

    public InlineResponse20018Data currencyType(String currencyType) {
        
        this.currencyType = currencyType;
        return this;
    }

     /**
     * Cryptocurrency type
     * @return currencyType
    **/
    public String getCurrencyType() {
        return currencyType;
    }


    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType;
    }

    public InlineResponse20018Data wantType(String wantType) {
        
        this.wantType = wantType;
        return this;
    }

     /**
     * Fiat currency type
     * @return wantType
    **/
    public String getWantType() {
        return wantType;
    }


    public void setWantType(String wantType) {
        this.wantType = wantType;
    }

    public InlineResponse20018Data rate(String rate) {
        
        this.rate = rate;
        return this;
    }

     /**
     * Price
     * @return rate
    **/
    public String getRate() {
        return rate;
    }


    public void setRate(String rate) {
        this.rate = rate;
    }

    public InlineResponse20018Data amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * Size
     * @return amount
    **/
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }

    public InlineResponse20018Data total(String total) {
        
        this.total = total;
        return this;
    }

     /**
     * Fiat amount
     * @return total
    **/
    public String getTotal() {
        return total;
    }


    public void setTotal(String total) {
        this.total = total;
    }

    public InlineResponse20018Data status(String status) {
        
        this.status = status;
        return this;
    }

     /**
     * Order Status
     * @return status
    **/
    public String getStatus() {
        return status;
    }


    public void setStatus(String status) {
        this.status = status;
    }

    public InlineResponse20018Data reasonId(String reasonId) {
        
        this.reasonId = reasonId;
        return this;
    }

     /**
     * Cancellation reason ID
     * @return reasonId
    **/
    public String getReasonId() {
        return reasonId;
    }


    public void setReasonId(String reasonId) {
        this.reasonId = reasonId;
    }

    public InlineResponse20018Data reasonDesc(String reasonDesc) {
        
        this.reasonDesc = reasonDesc;
        return this;
    }

     /**
     * Cancellation reason
     * @return reasonDesc
    **/
    public String getReasonDesc() {
        return reasonDesc;
    }


    public void setReasonDesc(String reasonDesc) {
        this.reasonDesc = reasonDesc;
    }

    public InlineResponse20018Data toastId(Integer toastId) {
        
        this.toastId = toastId;
        return this;
    }

     /**
     * Popup ID
     * @return toastId
    **/
    public Integer getToastId() {
        return toastId;
    }


    public void setToastId(Integer toastId) {
        this.toastId = toastId;
    }

    public InlineResponse20018Data cancelTime(String cancelTime) {
        
        this.cancelTime = cancelTime;
        return this;
    }

     /**
     * Cancellation time
     * @return cancelTime
    **/
    public String getCancelTime() {
        return cancelTime;
    }


    public void setCancelTime(String cancelTime) {
        this.cancelTime = cancelTime;
    }

    public InlineResponse20018Data sellerConfirm(Integer sellerConfirm) {
        
        this.sellerConfirm = sellerConfirm;
        return this;
    }

     /**
     * Whether seller confirmed the reason
     * @return sellerConfirm
    **/
    public Integer getSellerConfirm() {
        return sellerConfirm;
    }


    public void setSellerConfirm(Integer sellerConfirm) {
        this.sellerConfirm = sellerConfirm;
    }

    public InlineResponse20018Data inAppeal(Integer inAppeal) {
        
        this.inAppeal = inAppeal;
        return this;
    }

     /**
     * Whether in dispute
     * @return inAppeal
    **/
    public Integer getInAppeal() {
        return inAppeal;
    }


    public void setInAppeal(Integer inAppeal) {
        this.inAppeal = inAppeal;
    }

    public InlineResponse20018Data disputeTime(Integer disputeTime) {
        
        this.disputeTime = disputeTime;
        return this;
    }

     /**
     * Appeal time limit
     * @return disputeTime
    **/
    public Integer getDisputeTime() {
        return disputeTime;
    }


    public void setDisputeTime(Integer disputeTime) {
        this.disputeTime = disputeTime;
    }

    public InlineResponse20018Data cancelable(Integer cancelable) {
        
        this.cancelable = cancelable;
        return this;
    }

     /**
     * Whether order cancellation is allowed
     * @return cancelable
    **/
    public Integer getCancelable() {
        return cancelable;
    }


    public void setCancelable(Integer cancelable) {
        this.cancelable = cancelable;
    }

    public InlineResponse20018Data hidePayment(Integer hidePayment) {
        
        this.hidePayment = hidePayment;
        return this;
    }

     /**
     * Whether to hide payment method
     * @return hidePayment
    **/
    public Integer getHidePayment() {
        return hidePayment;
    }


    public void setHidePayment(Integer hidePayment) {
        this.hidePayment = hidePayment;
    }

    public InlineResponse20018Data tradeTips(String tradeTips) {
        
        this.tradeTips = tradeTips;
        return this;
    }

     /**
     * Trading terms
     * @return tradeTips
    **/
    public String getTradeTips() {
        return tradeTips;
    }


    public void setTradeTips(String tradeTips) {
        this.tradeTips = tradeTips;
    }

    public InlineResponse20018Data showBank(String showBank) {
        
        this.showBank = showBank;
        return this;
    }

     /**
     * Whether to display bank
     * @return showBank
    **/
    public String getShowBank() {
        return showBank;
    }


    public void setShowBank(String showBank) {
        this.showBank = showBank;
    }

    public InlineResponse20018Data bankname(String bankname) {
        
        this.bankname = bankname;
        return this;
    }

     /**
     * Bank name
     * @return bankname
    **/
    public String getBankname() {
        return bankname;
    }


    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    public InlineResponse20018Data bankbranch(String bankbranch) {
        
        this.bankbranch = bankbranch;
        return this;
    }

     /**
     * Bank branch name
     * @return bankbranch
    **/
    public String getBankbranch() {
        return bankbranch;
    }


    public void setBankbranch(String bankbranch) {
        this.bankbranch = bankbranch;
    }

    public InlineResponse20018Data bankid(String bankid) {
        
        this.bankid = bankid;
        return this;
    }

     /**
     * Bank ID
     * @return bankid
    **/
    public String getBankid() {
        return bankid;
    }


    public void setBankid(String bankid) {
        this.bankid = bankid;
    }

    public InlineResponse20018Data bankHolderRealname(String bankHolderRealname) {
        
        this.bankHolderRealname = bankHolderRealname;
        return this;
    }

     /**
     * Bank cardholder name
     * @return bankHolderRealname
    **/
    public String getBankHolderRealname() {
        return bankHolderRealname;
    }


    public void setBankHolderRealname(String bankHolderRealname) {
        this.bankHolderRealname = bankHolderRealname;
    }

    public InlineResponse20018Data showAli(String showAli) {
        
        this.showAli = showAli;
        return this;
    }

     /**
     * Whether to display Alipay
     * @return showAli
    **/
    public String getShowAli() {
        return showAli;
    }


    public void setShowAli(String showAli) {
        this.showAli = showAli;
    }

    public InlineResponse20018Data aliname(String aliname) {
        
        this.aliname = aliname;
        return this;
    }

     /**
     * Alipay account name
     * @return aliname
    **/
    public String getAliname() {
        return aliname;
    }


    public void setAliname(String aliname) {
        this.aliname = aliname;
    }

    public InlineResponse20018Data isAlicode(Integer isAlicode) {
        
        this.isAlicode = isAlicode;
        return this;
    }

     /**
     * Whether Alipay QR code exists
     * @return isAlicode
    **/
    public Integer getIsAlicode() {
        return isAlicode;
    }


    public void setIsAlicode(Integer isAlicode) {
        this.isAlicode = isAlicode;
    }

    public InlineResponse20018Data showWechat(String showWechat) {
        
        this.showWechat = showWechat;
        return this;
    }

     /**
     * Whether to display WeChat
     * @return showWechat
    **/
    public String getShowWechat() {
        return showWechat;
    }


    public void setShowWechat(String showWechat) {
        this.showWechat = showWechat;
    }

    public InlineResponse20018Data wename(String wename) {
        
        this.wename = wename;
        return this;
    }

     /**
     * WeChat account name
     * @return wename
    **/
    public String getWename() {
        return wename;
    }


    public void setWename(String wename) {
        this.wename = wename;
    }

    public InlineResponse20018Data showOthers(String showOthers) {
        
        this.showOthers = showOthers;
        return this;
    }

     /**
     * Whether to display other payment methods
     * @return showOthers
    **/
    public String getShowOthers() {
        return showOthers;
    }


    public void setShowOthers(String showOthers) {
        this.showOthers = showOthers;
    }

    public InlineResponse20018Data payOthers(List<String> payOthers) {
        
        this.payOthers = payOthers;
        return this;
    }

    public InlineResponse20018Data addPayOthersItem(String payOthersItem) {
        this.payOthers.add(payOthersItem);
        return this;
    }

     /**
     * Other payment methods
     * @return payOthers
    **/
    public List<String> getPayOthers() {
        return payOthers;
    }


    public void setPayOthers(List<String> payOthers) {
        this.payOthers = payOthers;
    }

    public InlineResponse20018Data selPaytype(String selPaytype) {
        
        this.selPaytype = selPaytype;
        return this;
    }

     /**
     * Payment type
     * @return selPaytype
    **/
    public String getSelPaytype() {
        return selPaytype;
    }


    public void setSelPaytype(String selPaytype) {
        this.selPaytype = selPaytype;
    }

    public InlineResponse20018Data itsUid(String itsUid) {
        
        this.itsUid = itsUid;
        return this;
    }

     /**
     * Counterparty UID
     * @return itsUid
    **/
    public String getItsUid() {
        return itsUid;
    }


    public void setItsUid(String itsUid) {
        this.itsUid = itsUid;
    }

    public InlineResponse20018Data itsIsBlueVip(Integer itsIsBlueVip) {
        
        this.itsIsBlueVip = itsIsBlueVip;
        return this;
    }

     /**
     * Whether counterparty is Blue V
     * @return itsIsBlueVip
    **/
    public Integer getItsIsBlueVip() {
        return itsIsBlueVip;
    }


    public void setItsIsBlueVip(Integer itsIsBlueVip) {
        this.itsIsBlueVip = itsIsBlueVip;
    }

    public InlineResponse20018Data itsTier(Integer itsTier) {
        
        this.itsTier = itsTier;
        return this;
    }

     /**
     * Counterparty VIP tier
     * @return itsTier
    **/
    public Integer getItsTier() {
        return itsTier;
    }


    public void setItsTier(Integer itsTier) {
        this.itsTier = itsTier;
    }

    public InlineResponse20018Data itsAvatar(String itsAvatar) {
        
        this.itsAvatar = itsAvatar;
        return this;
    }

     /**
     * Counterparty avatar
     * @return itsAvatar
    **/
    public String getItsAvatar() {
        return itsAvatar;
    }


    public void setItsAvatar(String itsAvatar) {
        this.itsAvatar = itsAvatar;
    }

    public InlineResponse20018Data itsNickname(String itsNickname) {
        
        this.itsNickname = itsNickname;
        return this;
    }

     /**
     * Counterparty nickname
     * @return itsNickname
    **/
    public String getItsNickname() {
        return itsNickname;
    }


    public void setItsNickname(String itsNickname) {
        this.itsNickname = itsNickname;
    }

    public InlineResponse20018Data itsRealname(String itsRealname) {
        
        this.itsRealname = itsRealname;
        return this;
    }

     /**
     * Counterparty username
     * @return itsRealname
    **/
    public String getItsRealname() {
        return itsRealname;
    }


    public void setItsRealname(String itsRealname) {
        this.itsRealname = itsRealname;
    }

    public InlineResponse20018Data isFollow(Integer isFollow) {
        
        this.isFollow = isFollow;
        return this;
    }

     /**
     * Whether following
     * @return isFollow
    **/
    public Integer getIsFollow() {
        return isFollow;
    }


    public void setIsFollow(Integer isFollow) {
        this.isFollow = isFollow;
    }

    public InlineResponse20018Data isBlack(Integer isBlack) {
        
        this.isBlack = isBlack;
        return this;
    }

     /**
     * Whether blocked
     * @return isBlack
    **/
    public Integer getIsBlack() {
        return isBlack;
    }


    public void setIsBlack(Integer isBlack) {
        this.isBlack = isBlack;
    }

    public InlineResponse20018Data haveTraded(Integer haveTraded) {
        
        this.haveTraded = haveTraded;
        return this;
    }

     /**
     * Whether traded before
     * @return haveTraded
    **/
    public Integer getHaveTraded() {
        return haveTraded;
    }


    public void setHaveTraded(Integer haveTraded) {
        this.haveTraded = haveTraded;
    }

    public InlineResponse20018Data appealUnread(Integer appealUnread) {
        
        this.appealUnread = appealUnread;
        return this;
    }

     /**
     * Unread appeals
     * @return appealUnread
    **/
    public Integer getAppealUnread() {
        return appealUnread;
    }


    public void setAppealUnread(Integer appealUnread) {
        this.appealUnread = appealUnread;
    }

    public InlineResponse20018Data appealAllowCancel(Integer appealAllowCancel) {
        
        this.appealAllowCancel = appealAllowCancel;
        return this;
    }

     /**
     * Whether appeal cancellation is allowed
     * @return appealAllowCancel
    **/
    public Integer getAppealAllowCancel() {
        return appealAllowCancel;
    }


    public void setAppealAllowCancel(Integer appealAllowCancel) {
        this.appealAllowCancel = appealAllowCancel;
    }

    public InlineResponse20018Data appealVerdictHasOpen(String appealVerdictHasOpen) {
        
        this.appealVerdictHasOpen = appealVerdictHasOpen;
        return this;
    }

     /**
     * Appeal result (including pending appeals)
     * @return appealVerdictHasOpen
    **/
    public String getAppealVerdictHasOpen() {
        return appealVerdictHasOpen;
    }


    public void setAppealVerdictHasOpen(String appealVerdictHasOpen) {
        this.appealVerdictHasOpen = appealVerdictHasOpen;
    }

    public InlineResponse20018Data imUnread(Integer imUnread) {
        
        this.imUnread = imUnread;
        return this;
    }

     /**
     * IM unread
     * @return imUnread
    **/
    public Integer getImUnread() {
        return imUnread;
    }


    public void setImUnread(Integer imUnread) {
        this.imUnread = imUnread;
    }

    public InlineResponse20018Data message(String message) {
        
        this.message = message;
        return this;
    }

     /**
     * Review content
     * @return message
    **/
    public String getMessage() {
        return message;
    }


    public void setMessage(String message) {
        this.message = message;
    }

    public InlineResponse20018Data score(String score) {
        
        this.score = score;
        return this;
    }

     /**
     * Rating
     * @return score
    **/
    public String getScore() {
        return score;
    }


    public void setScore(String score) {
        this.score = score;
    }

    public InlineResponse20018Data paymentVoucherUrl(List<String> paymentVoucherUrl) {
        
        this.paymentVoucherUrl = paymentVoucherUrl;
        return this;
    }

    public InlineResponse20018Data addPaymentVoucherUrlItem(String paymentVoucherUrlItem) {
        this.paymentVoucherUrl.add(paymentVoucherUrlItem);
        return this;
    }

     /**
     * Payment voucher
     * @return paymentVoucherUrl
    **/
    public List<String> getPaymentVoucherUrl() {
        return paymentVoucherUrl;
    }


    public void setPaymentVoucherUrl(List<String> paymentVoucherUrl) {
        this.paymentVoucherUrl = paymentVoucherUrl;
    }

    public InlineResponse20018Data completeNumber(Integer completeNumber) {
        
        this.completeNumber = completeNumber;
        return this;
    }

     /**
     * Counterparty transaction volume
     * @return completeNumber
    **/
    public Integer getCompleteNumber() {
        return completeNumber;
    }


    public void setCompleteNumber(Integer completeNumber) {
        this.completeNumber = completeNumber;
    }

    public InlineResponse20018Data completeRateMonth(String completeRateMonth) {
        
        this.completeRateMonth = completeRateMonth;
        return this;
    }

     /**
     * Counterparty completion rate
     * @return completeRateMonth
    **/
    public String getCompleteRateMonth() {
        return completeRateMonth;
    }


    public void setCompleteRateMonth(String completeRateMonth) {
        this.completeRateMonth = completeRateMonth;
    }

    public InlineResponse20018Data checkJournalAccount(Boolean checkJournalAccount) {
        
        this.checkJournalAccount = checkJournalAccount;
        return this;
    }

     /**
     * Whether transaction record is verified
     * @return checkJournalAccount
    **/
    public Boolean getCheckJournalAccount() {
        return checkJournalAccount;
    }


    public void setCheckJournalAccount(Boolean checkJournalAccount) {
        this.checkJournalAccount = checkJournalAccount;
    }

    public InlineResponse20018Data showJournalAccount(Boolean showJournalAccount) {
        
        this.showJournalAccount = showJournalAccount;
        return this;
    }

     /**
     * Whether to display transaction records
     * @return showJournalAccount
    **/
    public Boolean getShowJournalAccount() {
        return showJournalAccount;
    }


    public void setShowJournalAccount(Boolean showJournalAccount) {
        this.showJournalAccount = showJournalAccount;
    }

    public InlineResponse20018Data isFreezeGuarantee(Integer isFreezeGuarantee) {
        
        this.isFreezeGuarantee = isFreezeGuarantee;
        return this;
    }

     /**
     * Whether margin is frozen
     * @return isFreezeGuarantee
    **/
    public Integer getIsFreezeGuarantee() {
        return isFreezeGuarantee;
    }


    public void setIsFreezeGuarantee(Integer isFreezeGuarantee) {
        this.isFreezeGuarantee = isFreezeGuarantee;
    }

    public InlineResponse20018Data usdtLeftGuarantee(String usdtLeftGuarantee) {
        
        this.usdtLeftGuarantee = usdtLeftGuarantee;
        return this;
    }

     /**
     * Remaining USDT margin
     * @return usdtLeftGuarantee
    **/
    public String getUsdtLeftGuarantee() {
        return usdtLeftGuarantee;
    }


    public void setUsdtLeftGuarantee(String usdtLeftGuarantee) {
        this.usdtLeftGuarantee = usdtLeftGuarantee;
    }

    public InlineResponse20018Data guaranteeCurrType(String guaranteeCurrType) {
        
        this.guaranteeCurrType = guaranteeCurrType;
        return this;
    }

     /**
     * Margin currency type
     * @return guaranteeCurrType
    **/
    public String getGuaranteeCurrType() {
        return guaranteeCurrType;
    }


    public void setGuaranteeCurrType(String guaranteeCurrType) {
        this.guaranteeCurrType = guaranteeCurrType;
    }

    public InlineResponse20018Data timestPaid(Integer timestPaid) {
        
        this.timestPaid = timestPaid;
        return this;
    }

     /**
     * Payment time
     * @return timestPaid
    **/
    public Integer getTimestPaid() {
        return timestPaid;
    }


    public void setTimestPaid(Integer timestPaid) {
        this.timestPaid = timestPaid;
    }

    public InlineResponse20018Data state(String state) {
        
        this.state = state;
        return this;
    }

     /**
     * Order Status
     * @return state
    **/
    public String getState() {
        return state;
    }


    public void setState(String state) {
        this.state = state;
    }

    public InlineResponse20018Data releaseCoinSwitch(Integer releaseCoinSwitch) {
        
        this.releaseCoinSwitch = releaseCoinSwitch;
        return this;
    }

     /**
     * Coin release switch configuration
     * @return releaseCoinSwitch
    **/
    public Integer getReleaseCoinSwitch() {
        return releaseCoinSwitch;
    }


    public void setReleaseCoinSwitch(Integer releaseCoinSwitch) {
        this.releaseCoinSwitch = releaseCoinSwitch;
    }

    public InlineResponse20018Data ownRealname(String ownRealname) {
        
        this.ownRealname = ownRealname;
        return this;
    }

     /**
     * Username
     * @return ownRealname
    **/
    public String getOwnRealname() {
        return ownRealname;
    }


    public void setOwnRealname(String ownRealname) {
        this.ownRealname = ownRealname;
    }

    public InlineResponse20018Data confirmationUseTimeMonth(Integer confirmationUseTimeMonth) {
        
        this.confirmationUseTimeMonth = confirmationUseTimeMonth;
        return this;
    }

     /**
     * Average confirmation time in last 30 days
     * @return confirmationUseTimeMonth
    **/
    public Integer getConfirmationUseTimeMonth() {
        return confirmationUseTimeMonth;
    }


    public void setConfirmationUseTimeMonth(Integer confirmationUseTimeMonth) {
        this.confirmationUseTimeMonth = confirmationUseTimeMonth;
    }

    public InlineResponse20018Data isRiskUser(Integer isRiskUser) {
        
        this.isRiskUser = isRiskUser;
        return this;
    }

     /**
     * Whether risk user
     * @return isRiskUser
    **/
    public Integer getIsRiskUser() {
        return isRiskUser;
    }


    public void setIsRiskUser(Integer isRiskUser) {
        this.isRiskUser = isRiskUser;
    }

    public InlineResponse20018Data isXt(Integer isXt) {
        
        this.isXt = isXt;
        return this;
    }

     /**
     * Whether XT order
     * @return isXt
    **/
    public Integer getIsXt() {
        return isXt;
    }


    public void setIsXt(Integer isXt) {
        this.isXt = isXt;
    }

    public InlineResponse20018Data orderType(Integer orderType) {
        
        this.orderType = orderType;
        return this;
    }

     /**
     * Order Type
     * @return orderType
    **/
    public Integer getOrderType() {
        return orderType;
    }


    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    public InlineResponse20018Data symbol(String symbol) {
        
        this.symbol = symbol;
        return this;
    }

     /**
     * Fiat currency symbol
     * @return symbol
    **/
    public String getSymbol() {
        return symbol;
    }


    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public InlineResponse20018Data isShowReceive(Integer isShowReceive) {
        
        this.isShowReceive = isShowReceive;
        return this;
    }

     /**
     * Whether to show confirm receipt during appeal
     * @return isShowReceive
    **/
    public Integer getIsShowReceive() {
        return isShowReceive;
    }


    public void setIsShowReceive(Integer isShowReceive) {
        this.isShowReceive = isShowReceive;
    }

    public InlineResponse20018Data isTaker(Integer isTaker) {
        
        this.isTaker = isTaker;
        return this;
    }

     /**
     * Whether regular user
     * @return isTaker
    **/
    public Integer getIsTaker() {
        return isTaker;
    }


    public void setIsTaker(Integer isTaker) {
        this.isTaker = isTaker;
    }

    public InlineResponse20018Data isOnline(Integer isOnline) {
        
        this.isOnline = isOnline;
        return this;
    }

     /**
     * Merchant online status
     * @return isOnline
    **/
    public Integer getIsOnline() {
        return isOnline;
    }


    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    public InlineResponse20018Data showSellerContactInfo(Boolean showSellerContactInfo) {
        
        this.showSellerContactInfo = showSellerContactInfo;
        return this;
    }

     /**
     * Whether to display seller contact information
     * @return showSellerContactInfo
    **/
    public Boolean getShowSellerContactInfo() {
        return showSellerContactInfo;
    }


    public void setShowSellerContactInfo(Boolean showSellerContactInfo) {
        this.showSellerContactInfo = showSellerContactInfo;
    }

    public InlineResponse20018Data supportedPayTypes(List<String> supportedPayTypes) {
        
        this.supportedPayTypes = supportedPayTypes;
        return this;
    }

    public InlineResponse20018Data addSupportedPayTypesItem(String supportedPayTypesItem) {
        this.supportedPayTypes.add(supportedPayTypesItem);
        return this;
    }

     /**
     * Payment methods supported by current order
     * @return supportedPayTypes
    **/
    public List<String> getSupportedPayTypes() {
        return supportedPayTypes;
    }


    public void setSupportedPayTypes(List<String> supportedPayTypes) {
        this.supportedPayTypes = supportedPayTypes;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20018Data inlineResponse20018Data = (InlineResponse20018Data) o;
        return Objects.equals(this.isSell, inlineResponse20018Data.isSell) &&
                Objects.equals(this.txid, inlineResponse20018Data.txid) &&
                Objects.equals(this.orderid, inlineResponse20018Data.orderid) &&
                Objects.equals(this.timest, inlineResponse20018Data.timest) &&
                Objects.equals(this.lastPayTime, inlineResponse20018Data.lastPayTime) &&
                Objects.equals(this.remainPayTime, inlineResponse20018Data.remainPayTime) &&
                Objects.equals(this.currencyType, inlineResponse20018Data.currencyType) &&
                Objects.equals(this.wantType, inlineResponse20018Data.wantType) &&
                Objects.equals(this.rate, inlineResponse20018Data.rate) &&
                Objects.equals(this.amount, inlineResponse20018Data.amount) &&
                Objects.equals(this.total, inlineResponse20018Data.total) &&
                Objects.equals(this.status, inlineResponse20018Data.status) &&
                Objects.equals(this.reasonId, inlineResponse20018Data.reasonId) &&
                Objects.equals(this.reasonDesc, inlineResponse20018Data.reasonDesc) &&
                Objects.equals(this.toastId, inlineResponse20018Data.toastId) &&
                Objects.equals(this.cancelTime, inlineResponse20018Data.cancelTime) &&
                Objects.equals(this.sellerConfirm, inlineResponse20018Data.sellerConfirm) &&
                Objects.equals(this.inAppeal, inlineResponse20018Data.inAppeal) &&
                Objects.equals(this.disputeTime, inlineResponse20018Data.disputeTime) &&
                Objects.equals(this.cancelable, inlineResponse20018Data.cancelable) &&
                Objects.equals(this.hidePayment, inlineResponse20018Data.hidePayment) &&
                Objects.equals(this.tradeTips, inlineResponse20018Data.tradeTips) &&
                Objects.equals(this.showBank, inlineResponse20018Data.showBank) &&
                Objects.equals(this.bankname, inlineResponse20018Data.bankname) &&
                Objects.equals(this.bankbranch, inlineResponse20018Data.bankbranch) &&
                Objects.equals(this.bankid, inlineResponse20018Data.bankid) &&
                Objects.equals(this.bankHolderRealname, inlineResponse20018Data.bankHolderRealname) &&
                Objects.equals(this.showAli, inlineResponse20018Data.showAli) &&
                Objects.equals(this.aliname, inlineResponse20018Data.aliname) &&
                Objects.equals(this.isAlicode, inlineResponse20018Data.isAlicode) &&
                Objects.equals(this.showWechat, inlineResponse20018Data.showWechat) &&
                Objects.equals(this.wename, inlineResponse20018Data.wename) &&
                Objects.equals(this.showOthers, inlineResponse20018Data.showOthers) &&
                Objects.equals(this.payOthers, inlineResponse20018Data.payOthers) &&
                Objects.equals(this.selPaytype, inlineResponse20018Data.selPaytype) &&
                Objects.equals(this.itsUid, inlineResponse20018Data.itsUid) &&
                Objects.equals(this.itsIsBlueVip, inlineResponse20018Data.itsIsBlueVip) &&
                Objects.equals(this.itsTier, inlineResponse20018Data.itsTier) &&
                Objects.equals(this.itsAvatar, inlineResponse20018Data.itsAvatar) &&
                Objects.equals(this.itsNickname, inlineResponse20018Data.itsNickname) &&
                Objects.equals(this.itsRealname, inlineResponse20018Data.itsRealname) &&
                Objects.equals(this.isFollow, inlineResponse20018Data.isFollow) &&
                Objects.equals(this.isBlack, inlineResponse20018Data.isBlack) &&
                Objects.equals(this.haveTraded, inlineResponse20018Data.haveTraded) &&
                Objects.equals(this.appealUnread, inlineResponse20018Data.appealUnread) &&
                Objects.equals(this.appealAllowCancel, inlineResponse20018Data.appealAllowCancel) &&
                Objects.equals(this.appealVerdictHasOpen, inlineResponse20018Data.appealVerdictHasOpen) &&
                Objects.equals(this.imUnread, inlineResponse20018Data.imUnread) &&
                Objects.equals(this.message, inlineResponse20018Data.message) &&
                Objects.equals(this.score, inlineResponse20018Data.score) &&
                Objects.equals(this.paymentVoucherUrl, inlineResponse20018Data.paymentVoucherUrl) &&
                Objects.equals(this.completeNumber, inlineResponse20018Data.completeNumber) &&
                Objects.equals(this.completeRateMonth, inlineResponse20018Data.completeRateMonth) &&
                Objects.equals(this.checkJournalAccount, inlineResponse20018Data.checkJournalAccount) &&
                Objects.equals(this.showJournalAccount, inlineResponse20018Data.showJournalAccount) &&
                Objects.equals(this.isFreezeGuarantee, inlineResponse20018Data.isFreezeGuarantee) &&
                Objects.equals(this.usdtLeftGuarantee, inlineResponse20018Data.usdtLeftGuarantee) &&
                Objects.equals(this.guaranteeCurrType, inlineResponse20018Data.guaranteeCurrType) &&
                Objects.equals(this.timestPaid, inlineResponse20018Data.timestPaid) &&
                Objects.equals(this.state, inlineResponse20018Data.state) &&
                Objects.equals(this.releaseCoinSwitch, inlineResponse20018Data.releaseCoinSwitch) &&
                Objects.equals(this.ownRealname, inlineResponse20018Data.ownRealname) &&
                Objects.equals(this.confirmationUseTimeMonth, inlineResponse20018Data.confirmationUseTimeMonth) &&
                Objects.equals(this.isRiskUser, inlineResponse20018Data.isRiskUser) &&
                Objects.equals(this.isXt, inlineResponse20018Data.isXt) &&
                Objects.equals(this.orderType, inlineResponse20018Data.orderType) &&
                Objects.equals(this.symbol, inlineResponse20018Data.symbol) &&
                Objects.equals(this.isShowReceive, inlineResponse20018Data.isShowReceive) &&
                Objects.equals(this.isTaker, inlineResponse20018Data.isTaker) &&
                Objects.equals(this.isOnline, inlineResponse20018Data.isOnline) &&
                Objects.equals(this.showSellerContactInfo, inlineResponse20018Data.showSellerContactInfo) &&
                Objects.equals(this.supportedPayTypes, inlineResponse20018Data.supportedPayTypes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(isSell, txid, orderid, timest, lastPayTime, remainPayTime, currencyType, wantType, rate, amount, total, status, reasonId, reasonDesc, toastId, cancelTime, sellerConfirm, inAppeal, disputeTime, cancelable, hidePayment, tradeTips, showBank, bankname, bankbranch, bankid, bankHolderRealname, showAli, aliname, isAlicode, showWechat, wename, showOthers, payOthers, selPaytype, itsUid, itsIsBlueVip, itsTier, itsAvatar, itsNickname, itsRealname, isFollow, isBlack, haveTraded, appealUnread, appealAllowCancel, appealVerdictHasOpen, imUnread, message, score, paymentVoucherUrl, completeNumber, completeRateMonth, checkJournalAccount, showJournalAccount, isFreezeGuarantee, usdtLeftGuarantee, guaranteeCurrType, timestPaid, state, releaseCoinSwitch, ownRealname, confirmationUseTimeMonth, isRiskUser, isXt, orderType, symbol, isShowReceive, isTaker, isOnline, showSellerContactInfo, supportedPayTypes);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20018Data {\n");
        sb.append("      isSell: ").append(toIndentedString(isSell)).append("\n");
        sb.append("      txid: ").append(toIndentedString(txid)).append("\n");
        sb.append("      orderid: ").append(toIndentedString(orderid)).append("\n");
        sb.append("      timest: ").append(toIndentedString(timest)).append("\n");
        sb.append("      lastPayTime: ").append(toIndentedString(lastPayTime)).append("\n");
        sb.append("      remainPayTime: ").append(toIndentedString(remainPayTime)).append("\n");
        sb.append("      currencyType: ").append(toIndentedString(currencyType)).append("\n");
        sb.append("      wantType: ").append(toIndentedString(wantType)).append("\n");
        sb.append("      rate: ").append(toIndentedString(rate)).append("\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("      total: ").append(toIndentedString(total)).append("\n");
        sb.append("      status: ").append(toIndentedString(status)).append("\n");
        sb.append("      reasonId: ").append(toIndentedString(reasonId)).append("\n");
        sb.append("      reasonDesc: ").append(toIndentedString(reasonDesc)).append("\n");
        sb.append("      toastId: ").append(toIndentedString(toastId)).append("\n");
        sb.append("      cancelTime: ").append(toIndentedString(cancelTime)).append("\n");
        sb.append("      sellerConfirm: ").append(toIndentedString(sellerConfirm)).append("\n");
        sb.append("      inAppeal: ").append(toIndentedString(inAppeal)).append("\n");
        sb.append("      disputeTime: ").append(toIndentedString(disputeTime)).append("\n");
        sb.append("      cancelable: ").append(toIndentedString(cancelable)).append("\n");
        sb.append("      hidePayment: ").append(toIndentedString(hidePayment)).append("\n");
        sb.append("      tradeTips: ").append(toIndentedString(tradeTips)).append("\n");
        sb.append("      showBank: ").append(toIndentedString(showBank)).append("\n");
        sb.append("      bankname: ").append(toIndentedString(bankname)).append("\n");
        sb.append("      bankbranch: ").append(toIndentedString(bankbranch)).append("\n");
        sb.append("      bankid: ").append(toIndentedString(bankid)).append("\n");
        sb.append("      bankHolderRealname: ").append(toIndentedString(bankHolderRealname)).append("\n");
        sb.append("      showAli: ").append(toIndentedString(showAli)).append("\n");
        sb.append("      aliname: ").append(toIndentedString(aliname)).append("\n");
        sb.append("      isAlicode: ").append(toIndentedString(isAlicode)).append("\n");
        sb.append("      showWechat: ").append(toIndentedString(showWechat)).append("\n");
        sb.append("      wename: ").append(toIndentedString(wename)).append("\n");
        sb.append("      showOthers: ").append(toIndentedString(showOthers)).append("\n");
        sb.append("      payOthers: ").append(toIndentedString(payOthers)).append("\n");
        sb.append("      selPaytype: ").append(toIndentedString(selPaytype)).append("\n");
        sb.append("      itsUid: ").append(toIndentedString(itsUid)).append("\n");
        sb.append("      itsIsBlueVip: ").append(toIndentedString(itsIsBlueVip)).append("\n");
        sb.append("      itsTier: ").append(toIndentedString(itsTier)).append("\n");
        sb.append("      itsAvatar: ").append(toIndentedString(itsAvatar)).append("\n");
        sb.append("      itsNickname: ").append(toIndentedString(itsNickname)).append("\n");
        sb.append("      itsRealname: ").append(toIndentedString(itsRealname)).append("\n");
        sb.append("      isFollow: ").append(toIndentedString(isFollow)).append("\n");
        sb.append("      isBlack: ").append(toIndentedString(isBlack)).append("\n");
        sb.append("      haveTraded: ").append(toIndentedString(haveTraded)).append("\n");
        sb.append("      appealUnread: ").append(toIndentedString(appealUnread)).append("\n");
        sb.append("      appealAllowCancel: ").append(toIndentedString(appealAllowCancel)).append("\n");
        sb.append("      appealVerdictHasOpen: ").append(toIndentedString(appealVerdictHasOpen)).append("\n");
        sb.append("      imUnread: ").append(toIndentedString(imUnread)).append("\n");
        sb.append("      message: ").append(toIndentedString(message)).append("\n");
        sb.append("      score: ").append(toIndentedString(score)).append("\n");
        sb.append("      paymentVoucherUrl: ").append(toIndentedString(paymentVoucherUrl)).append("\n");
        sb.append("      completeNumber: ").append(toIndentedString(completeNumber)).append("\n");
        sb.append("      completeRateMonth: ").append(toIndentedString(completeRateMonth)).append("\n");
        sb.append("      checkJournalAccount: ").append(toIndentedString(checkJournalAccount)).append("\n");
        sb.append("      showJournalAccount: ").append(toIndentedString(showJournalAccount)).append("\n");
        sb.append("      isFreezeGuarantee: ").append(toIndentedString(isFreezeGuarantee)).append("\n");
        sb.append("      usdtLeftGuarantee: ").append(toIndentedString(usdtLeftGuarantee)).append("\n");
        sb.append("      guaranteeCurrType: ").append(toIndentedString(guaranteeCurrType)).append("\n");
        sb.append("      timestPaid: ").append(toIndentedString(timestPaid)).append("\n");
        sb.append("      state: ").append(toIndentedString(state)).append("\n");
        sb.append("      releaseCoinSwitch: ").append(toIndentedString(releaseCoinSwitch)).append("\n");
        sb.append("      ownRealname: ").append(toIndentedString(ownRealname)).append("\n");
        sb.append("      confirmationUseTimeMonth: ").append(toIndentedString(confirmationUseTimeMonth)).append("\n");
        sb.append("      isRiskUser: ").append(toIndentedString(isRiskUser)).append("\n");
        sb.append("      isXt: ").append(toIndentedString(isXt)).append("\n");
        sb.append("      orderType: ").append(toIndentedString(orderType)).append("\n");
        sb.append("      symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("      isShowReceive: ").append(toIndentedString(isShowReceive)).append("\n");
        sb.append("      isTaker: ").append(toIndentedString(isTaker)).append("\n");
        sb.append("      isOnline: ").append(toIndentedString(isOnline)).append("\n");
        sb.append("      showSellerContactInfo: ").append(toIndentedString(showSellerContactInfo)).append("\n");
        sb.append("      supportedPayTypes: ").append(toIndentedString(supportedPayTypes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

