/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.InlineResponse2007DataList;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2007Data
 */
public class InlineResponse2007Data {
    public static final String SERIALIZED_NAME_TOTAL = "total";
    @SerializedName(SERIALIZED_NAME_TOTAL)
    private Integer total;

    public static final String SERIALIZED_NAME_PAGE_SIZE = "page_size";
    @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
    private Integer pageSize;

    public static final String SERIALIZED_NAME_PAGE_NUMBER = "page_number";
    @SerializedName(SERIALIZED_NAME_PAGE_NUMBER)
    private Integer pageNumber;

    public static final String SERIALIZED_NAME_TOTAL_PAGE = "total_page";
    @SerializedName(SERIALIZED_NAME_TOTAL_PAGE)
    private Integer totalPage;

    public static final String SERIALIZED_NAME_LIST = "list";
    @SerializedName(SERIALIZED_NAME_LIST)
    private List<InlineResponse2007DataList> list = new ArrayList<>();


    public InlineResponse2007Data total(Integer total) {
        
        this.total = total;
        return this;
    }

     /**
     * Get total
     * @return total
    **/
    public Integer getTotal() {
        return total;
    }


    public void setTotal(Integer total) {
        this.total = total;
    }

    public InlineResponse2007Data pageSize(Integer pageSize) {
        
        this.pageSize = pageSize;
        return this;
    }

     /**
     * Get pageSize
     * @return pageSize
    **/
    public Integer getPageSize() {
        return pageSize;
    }


    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    public InlineResponse2007Data pageNumber(Integer pageNumber) {
        
        this.pageNumber = pageNumber;
        return this;
    }

     /**
     * Get pageNumber
     * @return pageNumber
    **/
    public Integer getPageNumber() {
        return pageNumber;
    }


    public void setPageNumber(Integer pageNumber) {
        this.pageNumber = pageNumber;
    }

    public InlineResponse2007Data totalPage(Integer totalPage) {
        
        this.totalPage = totalPage;
        return this;
    }

     /**
     * Get totalPage
     * @return totalPage
    **/
    public Integer getTotalPage() {
        return totalPage;
    }


    public void setTotalPage(Integer totalPage) {
        this.totalPage = totalPage;
    }

    public InlineResponse2007Data list(List<InlineResponse2007DataList> list) {
        
        this.list = list;
        return this;
    }

    public InlineResponse2007Data addListItem(InlineResponse2007DataList listItem) {
        this.list.add(listItem);
        return this;
    }

     /**
     * Get list
     * @return list
    **/
    public List<InlineResponse2007DataList> getList() {
        return list;
    }


    public void setList(List<InlineResponse2007DataList> list) {
        this.list = list;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2007Data inlineResponse2007Data = (InlineResponse2007Data) o;
        return Objects.equals(this.total, inlineResponse2007Data.total) &&
                Objects.equals(this.pageSize, inlineResponse2007Data.pageSize) &&
                Objects.equals(this.pageNumber, inlineResponse2007Data.pageNumber) &&
                Objects.equals(this.totalPage, inlineResponse2007Data.totalPage) &&
                Objects.equals(this.list, inlineResponse2007Data.list);
    }

    @Override
    public int hashCode() {
        return Objects.hash(total, pageSize, pageNumber, totalPage, list);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse2007Data {\n");
        sb.append("      total: ").append(toIndentedString(total)).append("\n");
        sb.append("      pageSize: ").append(toIndentedString(pageSize)).append("\n");
        sb.append("      pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
        sb.append("      totalPage: ").append(toIndentedString(totalPage)).append("\n");
        sb.append("      list: ").append(toIndentedString(list)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

