/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * InlineResponse2005Data
 */
public class InlineResponse2005Data {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private String id;

    public static final String SERIALIZED_NAME_BANK_ACCOUNT_NAME = "bank_account_name";
    @SerializedName(SERIALIZED_NAME_BANK_ACCOUNT_NAME)
    private String bankAccountName;

    public static final String SERIALIZED_NAME_BANK_NAME = "bank_name";
    @SerializedName(SERIALIZED_NAME_BANK_NAME)
    private String bankName;

    public static final String SERIALIZED_NAME_BANK_COUNTRY = "bank_country";
    @SerializedName(SERIALIZED_NAME_BANK_COUNTRY)
    private String bankCountry;

    public static final String SERIALIZED_NAME_BANK_ADDRESS = "bank_address";
    @SerializedName(SERIALIZED_NAME_BANK_ADDRESS)
    private String bankAddress;

    public static final String SERIALIZED_NAME_BANK_CODE = "bank_code";
    @SerializedName(SERIALIZED_NAME_BANK_CODE)
    private String bankCode;

    public static final String SERIALIZED_NAME_BRANCH_CODE = "branch_code";
    @SerializedName(SERIALIZED_NAME_BRANCH_CODE)
    private String branchCode;


    public InlineResponse2005Data id(String id) {
        
        this.id = id;
        return this;
    }

     /**
     * Bank ID (required for order placement)
     * @return id
    **/
    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id;
    }

    public InlineResponse2005Data bankAccountName(String bankAccountName) {
        
        this.bankAccountName = bankAccountName;
        return this;
    }

     /**
     * Get bankAccountName
     * @return bankAccountName
    **/
    public String getBankAccountName() {
        return bankAccountName;
    }


    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    public InlineResponse2005Data bankName(String bankName) {
        
        this.bankName = bankName;
        return this;
    }

     /**
     * Get bankName
     * @return bankName
    **/
    public String getBankName() {
        return bankName;
    }


    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public InlineResponse2005Data bankCountry(String bankCountry) {
        
        this.bankCountry = bankCountry;
        return this;
    }

     /**
     * Get bankCountry
     * @return bankCountry
    **/
    public String getBankCountry() {
        return bankCountry;
    }


    public void setBankCountry(String bankCountry) {
        this.bankCountry = bankCountry;
    }

    public InlineResponse2005Data bankAddress(String bankAddress) {
        
        this.bankAddress = bankAddress;
        return this;
    }

     /**
     * Get bankAddress
     * @return bankAddress
    **/
    public String getBankAddress() {
        return bankAddress;
    }


    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress;
    }

    public InlineResponse2005Data bankCode(String bankCode) {
        
        this.bankCode = bankCode;
        return this;
    }

     /**
     * Get bankCode
     * @return bankCode
    **/
    public String getBankCode() {
        return bankCode;
    }


    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    public InlineResponse2005Data branchCode(String branchCode) {
        
        this.branchCode = branchCode;
        return this;
    }

     /**
     * Get branchCode
     * @return branchCode
    **/
    public String getBranchCode() {
        return branchCode;
    }


    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2005Data inlineResponse2005Data = (InlineResponse2005Data) o;
        return Objects.equals(this.id, inlineResponse2005Data.id) &&
                Objects.equals(this.bankAccountName, inlineResponse2005Data.bankAccountName) &&
                Objects.equals(this.bankName, inlineResponse2005Data.bankName) &&
                Objects.equals(this.bankCountry, inlineResponse2005Data.bankCountry) &&
                Objects.equals(this.bankAddress, inlineResponse2005Data.bankAddress) &&
                Objects.equals(this.bankCode, inlineResponse2005Data.bankCode) &&
                Objects.equals(this.branchCode, inlineResponse2005Data.branchCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, bankAccountName, bankName, bankCountry, bankAddress, bankCode, branchCode);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse2005Data {\n");
        sb.append("      id: ").append(toIndentedString(id)).append("\n");
        sb.append("      bankAccountName: ").append(toIndentedString(bankAccountName)).append("\n");
        sb.append("      bankName: ").append(toIndentedString(bankName)).append("\n");
        sb.append("      bankCountry: ").append(toIndentedString(bankCountry)).append("\n");
        sb.append("      bankAddress: ").append(toIndentedString(bankAddress)).append("\n");
        sb.append("      bankCode: ").append(toIndentedString(bankCode)).append("\n");
        sb.append("      branchCode: ").append(toIndentedString(branchCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

