/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * InlineResponse20023Data
 */
public class InlineResponse20023Data {
    public static final String SERIALIZED_NAME_INDEX = "index";
    @SerializedName(SERIALIZED_NAME_INDEX)
    private Integer index;

    public static final String SERIALIZED_NAME_ASSET = "asset";
    @SerializedName(SERIALIZED_NAME_ASSET)
    private String asset;

    public static final String SERIALIZED_NAME_FIAT_UNIT = "fiat_unit";
    @SerializedName(SERIALIZED_NAME_FIAT_UNIT)
    private String fiatUnit;

    public static final String SERIALIZED_NAME_ADV_NO = "adv_no";
    @SerializedName(SERIALIZED_NAME_ADV_NO)
    private Integer advNo;

    public static final String SERIALIZED_NAME_PRICE = "price";
    @SerializedName(SERIALIZED_NAME_PRICE)
    private String price;

    public static final String SERIALIZED_NAME_MAX_SINGLE_TRANS_AMOUNT = "max_single_trans_amount";
    @SerializedName(SERIALIZED_NAME_MAX_SINGLE_TRANS_AMOUNT)
    private String maxSingleTransAmount;

    public static final String SERIALIZED_NAME_MIN_SINGLE_TRANS_AMOUNT = "min_single_trans_amount";
    @SerializedName(SERIALIZED_NAME_MIN_SINGLE_TRANS_AMOUNT)
    private String minSingleTransAmount;

    public static final String SERIALIZED_NAME_NICK_NAME = "nick_name";
    @SerializedName(SERIALIZED_NAME_NICK_NAME)
    private String nickName;


    public InlineResponse20023Data index(Integer index) {
        
        this.index = index;
        return this;
    }

     /**
     * Serial number
     * @return index
    **/
    @javax.annotation.Nullable
    public Integer getIndex() {
        return index;
    }


    public void setIndex(Integer index) {
        this.index = index;
    }

    public InlineResponse20023Data asset(String asset) {
        
        this.asset = asset;
        return this;
    }

     /**
     * Cryptocurrency
     * @return asset
    **/
    @javax.annotation.Nullable
    public String getAsset() {
        return asset;
    }


    public void setAsset(String asset) {
        this.asset = asset;
    }

    public InlineResponse20023Data fiatUnit(String fiatUnit) {
        
        this.fiatUnit = fiatUnit;
        return this;
    }

     /**
     * Fiat currency
     * @return fiatUnit
    **/
    @javax.annotation.Nullable
    public String getFiatUnit() {
        return fiatUnit;
    }


    public void setFiatUnit(String fiatUnit) {
        this.fiatUnit = fiatUnit;
    }

    public InlineResponse20023Data advNo(Integer advNo) {
        
        this.advNo = advNo;
        return this;
    }

     /**
     * Ad ID
     * @return advNo
    **/
    @javax.annotation.Nullable
    public Integer getAdvNo() {
        return advNo;
    }


    public void setAdvNo(Integer advNo) {
        this.advNo = advNo;
    }

    public InlineResponse20023Data price(String price) {
        
        this.price = price;
        return this;
    }

     /**
     * Price
     * @return price
    **/
    @javax.annotation.Nullable
    public String getPrice() {
        return price;
    }


    public void setPrice(String price) {
        this.price = price;
    }

    public InlineResponse20023Data maxSingleTransAmount(String maxSingleTransAmount) {
        
        this.maxSingleTransAmount = maxSingleTransAmount;
        return this;
    }

     /**
     * Maximum Cryptocurrency Amount
     * @return maxSingleTransAmount
    **/
    @javax.annotation.Nullable
    public String getMaxSingleTransAmount() {
        return maxSingleTransAmount;
    }


    public void setMaxSingleTransAmount(String maxSingleTransAmount) {
        this.maxSingleTransAmount = maxSingleTransAmount;
    }

    public InlineResponse20023Data minSingleTransAmount(String minSingleTransAmount) {
        
        this.minSingleTransAmount = minSingleTransAmount;
        return this;
    }

     /**
     * Minimum Cryptocurrency Amount
     * @return minSingleTransAmount
    **/
    @javax.annotation.Nullable
    public String getMinSingleTransAmount() {
        return minSingleTransAmount;
    }


    public void setMinSingleTransAmount(String minSingleTransAmount) {
        this.minSingleTransAmount = minSingleTransAmount;
    }

    public InlineResponse20023Data nickName(String nickName) {
        
        this.nickName = nickName;
        return this;
    }

     /**
     * Advertiser Nickname
     * @return nickName
    **/
    @javax.annotation.Nullable
    public String getNickName() {
        return nickName;
    }


    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20023Data inlineResponse20023Data = (InlineResponse20023Data) o;
        return Objects.equals(this.index, inlineResponse20023Data.index) &&
                Objects.equals(this.asset, inlineResponse20023Data.asset) &&
                Objects.equals(this.fiatUnit, inlineResponse20023Data.fiatUnit) &&
                Objects.equals(this.advNo, inlineResponse20023Data.advNo) &&
                Objects.equals(this.price, inlineResponse20023Data.price) &&
                Objects.equals(this.maxSingleTransAmount, inlineResponse20023Data.maxSingleTransAmount) &&
                Objects.equals(this.minSingleTransAmount, inlineResponse20023Data.minSingleTransAmount) &&
                Objects.equals(this.nickName, inlineResponse20023Data.nickName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(index, asset, fiatUnit, advNo, price, maxSingleTransAmount, minSingleTransAmount, nickName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20023Data {\n");
        sb.append("      index: ").append(toIndentedString(index)).append("\n");
        sb.append("      asset: ").append(toIndentedString(asset)).append("\n");
        sb.append("      fiatUnit: ").append(toIndentedString(fiatUnit)).append("\n");
        sb.append("      advNo: ").append(toIndentedString(advNo)).append("\n");
        sb.append("      price: ").append(toIndentedString(price)).append("\n");
        sb.append("      maxSingleTransAmount: ").append(toIndentedString(maxSingleTransAmount)).append("\n");
        sb.append("      minSingleTransAmount: ").append(toIndentedString(minSingleTransAmount)).append("\n");
        sb.append("      nickName: ").append(toIndentedString(nickName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

