/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * InlineResponse2001
 */
public class InlineResponse2001 {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";
    @SerializedName(SERIALIZED_NAME_SYMBOL)
    private String symbol;

    public static final String SERIALIZED_NAME_LAST_PRICE = "last_price";
    @SerializedName(SERIALIZED_NAME_LAST_PRICE)
    private String lastPrice;

    public static final String SERIALIZED_NAME_OPEN24H = "open_24h";
    @SerializedName(SERIALIZED_NAME_OPEN24H)
    private String open24h;

    public static final String SERIALIZED_NAME_LOW24H = "low_24h";
    @SerializedName(SERIALIZED_NAME_LOW24H)
    private String low24h;

    public static final String SERIALIZED_NAME_HIGH24H = "high_24h";
    @SerializedName(SERIALIZED_NAME_HIGH24H)
    private String high24h;

    public static final String SERIALIZED_NAME_VOLUME24H_BASE = "volume_24h_base";
    @SerializedName(SERIALIZED_NAME_VOLUME24H_BASE)
    private String volume24hBase;

    public static final String SERIALIZED_NAME_VOLUME24H_QUOTE = "volume_24h_quote";
    @SerializedName(SERIALIZED_NAME_VOLUME24H_QUOTE)
    private String volume24hQuote;

    public static final String SERIALIZED_NAME_MARK_PRICE = "mark_price";
    @SerializedName(SERIALIZED_NAME_MARK_PRICE)
    private String markPrice;

    public static final String SERIALIZED_NAME_INDEX_PRICE = "index_price";
    @SerializedName(SERIALIZED_NAME_INDEX_PRICE)
    private String indexPrice;

    public static final String SERIALIZED_NAME_OPEN_INTEREST = "open_interest";
    @SerializedName(SERIALIZED_NAME_OPEN_INTEREST)
    private String openInterest;

    public static final String SERIALIZED_NAME_OPEN_INTEREST_QUOTE = "open_interest_quote";
    @SerializedName(SERIALIZED_NAME_OPEN_INTEREST_QUOTE)
    private String openInterestQuote;

    public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
    @SerializedName(SERIALIZED_NAME_TIMESTAMP)
    private String timestamp;


    public InlineResponse2001 symbol(String symbol) {
        
        this.symbol = symbol;
        return this;
    }

     /**
     * Trading Pair
     * @return symbol
    **/
    public String getSymbol() {
        return symbol;
    }


    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public InlineResponse2001 lastPrice(String lastPrice) {
        
        this.lastPrice = lastPrice;
        return this;
    }

     /**
     * Last price
     * @return lastPrice
    **/
    @javax.annotation.Nullable
    public String getLastPrice() {
        return lastPrice;
    }


    public void setLastPrice(String lastPrice) {
        this.lastPrice = lastPrice;
    }

    public InlineResponse2001 open24h(String open24h) {
        
        this.open24h = open24h;
        return this;
    }

     /**
     * 24-hour opening price
     * @return open24h
    **/
    @javax.annotation.Nullable
    public String getOpen24h() {
        return open24h;
    }


    public void setOpen24h(String open24h) {
        this.open24h = open24h;
    }

    public InlineResponse2001 low24h(String low24h) {
        
        this.low24h = low24h;
        return this;
    }

     /**
     * 24h Low
     * @return low24h
    **/
    @javax.annotation.Nullable
    public String getLow24h() {
        return low24h;
    }


    public void setLow24h(String low24h) {
        this.low24h = low24h;
    }

    public InlineResponse2001 high24h(String high24h) {
        
        this.high24h = high24h;
        return this;
    }

     /**
     * 24h High
     * @return high24h
    **/
    @javax.annotation.Nullable
    public String getHigh24h() {
        return high24h;
    }


    public void setHigh24h(String high24h) {
        this.high24h = high24h;
    }

    public InlineResponse2001 volume24hBase(String volume24hBase) {
        
        this.volume24hBase = volume24hBase;
        return this;
    }

     /**
     * 24-hour trading volume in base currency
     * @return volume24hBase
    **/
    @javax.annotation.Nullable
    public String getVolume24hBase() {
        return volume24hBase;
    }


    public void setVolume24hBase(String volume24hBase) {
        this.volume24hBase = volume24hBase;
    }

    public InlineResponse2001 volume24hQuote(String volume24hQuote) {
        
        this.volume24hQuote = volume24hQuote;
        return this;
    }

     /**
     * 24-hour trading volume in quote currency
     * @return volume24hQuote
    **/
    @javax.annotation.Nullable
    public String getVolume24hQuote() {
        return volume24hQuote;
    }


    public void setVolume24hQuote(String volume24hQuote) {
        this.volume24hQuote = volume24hQuote;
    }

    public InlineResponse2001 markPrice(String markPrice) {
        
        this.markPrice = markPrice;
        return this;
    }

     /**
     * Mark price
     * @return markPrice
    **/
    @javax.annotation.Nullable
    public String getMarkPrice() {
        return markPrice;
    }


    public void setMarkPrice(String markPrice) {
        this.markPrice = markPrice;
    }

    public InlineResponse2001 indexPrice(String indexPrice) {
        
        this.indexPrice = indexPrice;
        return this;
    }

     /**
     * Index price
     * @return indexPrice
    **/
    @javax.annotation.Nullable
    public String getIndexPrice() {
        return indexPrice;
    }


    public void setIndexPrice(String indexPrice) {
        this.indexPrice = indexPrice;
    }

    public InlineResponse2001 openInterest(String openInterest) {
        
        this.openInterest = openInterest;
        return this;
    }

     /**
     * Open interest
     * @return openInterest
    **/
    @javax.annotation.Nullable
    public String getOpenInterest() {
        return openInterest;
    }


    public void setOpenInterest(String openInterest) {
        this.openInterest = openInterest;
    }

    public InlineResponse2001 openInterestQuote(String openInterestQuote) {
        
        this.openInterestQuote = openInterestQuote;
        return this;
    }

     /**
     * Open interest (in quote currency)
     * @return openInterestQuote
    **/
    @javax.annotation.Nullable
    public String getOpenInterestQuote() {
        return openInterestQuote;
    }


    public void setOpenInterestQuote(String openInterestQuote) {
        this.openInterestQuote = openInterestQuote;
    }

    public InlineResponse2001 timestamp(String timestamp) {
        
        this.timestamp = timestamp;
        return this;
    }

     /**
     * Update timestamp
     * @return timestamp
    **/
    public String getTimestamp() {
        return timestamp;
    }


    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
        return Objects.equals(this.symbol, inlineResponse2001.symbol) &&
                Objects.equals(this.lastPrice, inlineResponse2001.lastPrice) &&
                Objects.equals(this.open24h, inlineResponse2001.open24h) &&
                Objects.equals(this.low24h, inlineResponse2001.low24h) &&
                Objects.equals(this.high24h, inlineResponse2001.high24h) &&
                Objects.equals(this.volume24hBase, inlineResponse2001.volume24hBase) &&
                Objects.equals(this.volume24hQuote, inlineResponse2001.volume24hQuote) &&
                Objects.equals(this.markPrice, inlineResponse2001.markPrice) &&
                Objects.equals(this.indexPrice, inlineResponse2001.indexPrice) &&
                Objects.equals(this.openInterest, inlineResponse2001.openInterest) &&
                Objects.equals(this.openInterestQuote, inlineResponse2001.openInterestQuote) &&
                Objects.equals(this.timestamp, inlineResponse2001.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, lastPrice, open24h, low24h, high24h, volume24hBase, volume24hQuote, markPrice, indexPrice, openInterest, openInterestQuote, timestamp);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse2001 {\n");
        sb.append("      symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("      lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
        sb.append("      open24h: ").append(toIndentedString(open24h)).append("\n");
        sb.append("      low24h: ").append(toIndentedString(low24h)).append("\n");
        sb.append("      high24h: ").append(toIndentedString(high24h)).append("\n");
        sb.append("      volume24hBase: ").append(toIndentedString(volume24hBase)).append("\n");
        sb.append("      volume24hQuote: ").append(toIndentedString(volume24hQuote)).append("\n");
        sb.append("      markPrice: ").append(toIndentedString(markPrice)).append("\n");
        sb.append("      indexPrice: ").append(toIndentedString(indexPrice)).append("\n");
        sb.append("      openInterest: ").append(toIndentedString(openInterest)).append("\n");
        sb.append("      openInterestQuote: ").append(toIndentedString(openInterestQuote)).append("\n");
        sb.append("      timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

