/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * LaunchPoolV4RewardRecord
 */
public class LaunchPoolV4RewardRecord {
    public static final String SERIALIZED_NAME_REWARD_TIMEST = "reward_timest";
    @SerializedName(SERIALIZED_NAME_REWARD_TIMEST)
    private String rewardTimest;

    public static final String SERIALIZED_NAME_COIN = "coin";
    @SerializedName(SERIALIZED_NAME_COIN)
    private String coin;

    public static final String SERIALIZED_NAME_VALID_MORTGAGE_AMOUNT = "valid_mortgage_amount";
    @SerializedName(SERIALIZED_NAME_VALID_MORTGAGE_AMOUNT)
    private String validMortgageAmount;

    public static final String SERIALIZED_NAME_AMOUNT_BASE = "amount_base";
    @SerializedName(SERIALIZED_NAME_AMOUNT_BASE)
    private String amountBase;

    public static final String SERIALIZED_NAME_AMOUNT_EXT = "amount_ext";
    @SerializedName(SERIALIZED_NAME_AMOUNT_EXT)
    private String amountExt;


    public LaunchPoolV4RewardRecord rewardTimest(String rewardTimest) {
        
        this.rewardTimest = rewardTimest;
        return this;
    }

     /**
     * Reward date
     * @return rewardTimest
    **/
    public String getRewardTimest() {
        return rewardTimest;
    }


    public void setRewardTimest(String rewardTimest) {
        this.rewardTimest = rewardTimest;
    }

    public LaunchPoolV4RewardRecord coin(String coin) {
        
        this.coin = coin;
        return this;
    }

     /**
     * Reward currency
     * @return coin
    **/
    public String getCoin() {
        return coin;
    }


    public void setCoin(String coin) {
        this.coin = coin;
    }

    public LaunchPoolV4RewardRecord validMortgageAmount(String validMortgageAmount) {
        
        this.validMortgageAmount = validMortgageAmount;
        return this;
    }

     /**
     * Active pledge count
     * @return validMortgageAmount
    **/
    public String getValidMortgageAmount() {
        return validMortgageAmount;
    }


    public void setValidMortgageAmount(String validMortgageAmount) {
        this.validMortgageAmount = validMortgageAmount;
    }

    public LaunchPoolV4RewardRecord amountBase(String amountBase) {
        
        this.amountBase = amountBase;
        return this;
    }

     /**
     * Base airdrop
     * @return amountBase
    **/
    public String getAmountBase() {
        return amountBase;
    }


    public void setAmountBase(String amountBase) {
        this.amountBase = amountBase;
    }

    public LaunchPoolV4RewardRecord amountExt(String amountExt) {
        
        this.amountExt = amountExt;
        return this;
    }

     /**
     * Bonus airdrop
     * @return amountExt
    **/
    public String getAmountExt() {
        return amountExt;
    }


    public void setAmountExt(String amountExt) {
        this.amountExt = amountExt;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LaunchPoolV4RewardRecord launchPoolV4RewardRecord = (LaunchPoolV4RewardRecord) o;
        return Objects.equals(this.rewardTimest, launchPoolV4RewardRecord.rewardTimest) &&
                Objects.equals(this.coin, launchPoolV4RewardRecord.coin) &&
                Objects.equals(this.validMortgageAmount, launchPoolV4RewardRecord.validMortgageAmount) &&
                Objects.equals(this.amountBase, launchPoolV4RewardRecord.amountBase) &&
                Objects.equals(this.amountExt, launchPoolV4RewardRecord.amountExt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rewardTimest, coin, validMortgageAmount, amountBase, amountExt);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LaunchPoolV4RewardRecord {\n");
        sb.append("      rewardTimest: ").append(toIndentedString(rewardTimest)).append("\n");
        sb.append("      coin: ").append(toIndentedString(coin)).append("\n");
        sb.append("      validMortgageAmount: ").append(toIndentedString(validMortgageAmount)).append("\n");
        sb.append("      amountBase: ").append(toIndentedString(amountBase)).append("\n");
        sb.append("      amountExt: ").append(toIndentedString(amountExt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

