/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ListActivitiesResponseDataList
 */
public class ListActivitiesResponseDataList {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;

    public static final String SERIALIZED_NAME_TYPE_ID = "type_id";
    @SerializedName(SERIALIZED_NAME_TYPE_ID)
    private Integer typeId;

    public static final String SERIALIZED_NAME_TYPE_NAME = "type_name";
    @SerializedName(SERIALIZED_NAME_TYPE_NAME)
    private String typeName;

    public static final String SERIALIZED_NAME_COMPETITION_NAME = "competition_name";
    @SerializedName(SERIALIZED_NAME_COMPETITION_NAME)
    private String competitionName;

    public static final String SERIALIZED_NAME_START_AT = "start_at";
    @SerializedName(SERIALIZED_NAME_START_AT)
    private Integer startAt;

    public static final String SERIALIZED_NAME_END_AT = "end_at";
    @SerializedName(SERIALIZED_NAME_END_AT)
    private Integer endAt;

    public static final String SERIALIZED_NAME_IMG = "img";
    @SerializedName(SERIALIZED_NAME_IMG)
    private String img;

    public static final String SERIALIZED_NAME_IMG_DARK = "img_dark";
    @SerializedName(SERIALIZED_NAME_IMG_DARK)
    private String imgDark;

    public static final String SERIALIZED_NAME_URL = "url";
    @SerializedName(SERIALIZED_NAME_URL)
    private String url;

    public static final String SERIALIZED_NAME_HOT = "hot";
    @SerializedName(SERIALIZED_NAME_HOT)
    private Integer hot;

    public static final String SERIALIZED_NAME_MASTER_ONE_LINE = "master_one_line";
    @SerializedName(SERIALIZED_NAME_MASTER_ONE_LINE)
    private String masterOneLine;

    public static final String SERIALIZED_NAME_MASTER_TWO_LINE = "master_two_line";
    @SerializedName(SERIALIZED_NAME_MASTER_TWO_LINE)
    private String masterTwoLine;

    public static final String SERIALIZED_NAME_SLAVE_ONE_LINE = "slave_one_line";
    @SerializedName(SERIALIZED_NAME_SLAVE_ONE_LINE)
    private String slaveOneLine;

    public static final String SERIALIZED_NAME_SLAVE_TWO_LINE = "slave_two_line";
    @SerializedName(SERIALIZED_NAME_SLAVE_TWO_LINE)
    private String slaveTwoLine;

    public static final String SERIALIZED_NAME_COMPETITION_TITLE = "competition_title";
    @SerializedName(SERIALIZED_NAME_COMPETITION_TITLE)
    private String competitionTitle;

    public static final String SERIALIZED_NAME_TOP_ID = "top_id";
    @SerializedName(SERIALIZED_NAME_TOP_ID)
    private Integer topId;

    public static final String SERIALIZED_NAME_PARENT_ID = "parent_id";
    @SerializedName(SERIALIZED_NAME_PARENT_ID)
    private Integer parentId;

    public static final String SERIALIZED_NAME_NEW_IMG = "new_img";
    @SerializedName(SERIALIZED_NAME_NEW_IMG)
    private String newImg;

    public static final String SERIALIZED_NAME_NEW_IMG_DARK = "new_img_dark";
    @SerializedName(SERIALIZED_NAME_NEW_IMG_DARK)
    private String newImgDark;

    public static final String SERIALIZED_NAME_TAG = "tag";
    @SerializedName(SERIALIZED_NAME_TAG)
    private List<String> tag = new ArrayList<>();


    public ListActivitiesResponseDataList id(Integer id) {
        
        this.id = id;
        return this;
    }

     /**
     * Activity ID
     * @return id
    **/
    public Integer getId() {
        return id;
    }


    public void setId(Integer id) {
        this.id = id;
    }

    public ListActivitiesResponseDataList typeId(Integer typeId) {
        
        this.typeId = typeId;
        return this;
    }

     /**
     * Activity type ID
     * @return typeId
    **/
    public Integer getTypeId() {
        return typeId;
    }


    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    public ListActivitiesResponseDataList typeName(String typeName) {
        
        this.typeName = typeName;
        return this;
    }

     /**
     * Activity type name
     * @return typeName
    **/
    public String getTypeName() {
        return typeName;
    }


    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public ListActivitiesResponseDataList competitionName(String competitionName) {
        
        this.competitionName = competitionName;
        return this;
    }

     /**
     * Activity name
     * @return competitionName
    **/
    public String getCompetitionName() {
        return competitionName;
    }


    public void setCompetitionName(String competitionName) {
        this.competitionName = competitionName;
    }

    public ListActivitiesResponseDataList startAt(Integer startAt) {
        
        this.startAt = startAt;
        return this;
    }

     /**
     * Activity start time (Unix timestamp, in seconds)
     * @return startAt
    **/
    public Integer getStartAt() {
        return startAt;
    }


    public void setStartAt(Integer startAt) {
        this.startAt = startAt;
    }

    public ListActivitiesResponseDataList endAt(Integer endAt) {
        
        this.endAt = endAt;
        return this;
    }

     /**
     * Activity end time (Unix timestamp, in seconds)
     * @return endAt
    **/
    public Integer getEndAt() {
        return endAt;
    }


    public void setEndAt(Integer endAt) {
        this.endAt = endAt;
    }

    public ListActivitiesResponseDataList img(String img) {
        
        this.img = img;
        return this;
    }

     /**
     * Activity image URL (light mode)
     * @return img
    **/
    public String getImg() {
        return img;
    }


    public void setImg(String img) {
        this.img = img;
    }

    public ListActivitiesResponseDataList imgDark(String imgDark) {
        
        this.imgDark = imgDark;
        return this;
    }

     /**
     * Activity image URL (dark mode)
     * @return imgDark
    **/
    public String getImgDark() {
        return imgDark;
    }


    public void setImgDark(String imgDark) {
        this.imgDark = imgDark;
    }

    public ListActivitiesResponseDataList url(String url) {
        
        this.url = url;
        return this;
    }

     /**
     * Activity redirect link
     * @return url
    **/
    public String getUrl() {
        return url;
    }


    public void setUrl(String url) {
        this.url = url;
    }

    public ListActivitiesResponseDataList hot(Integer hot) {
        
        this.hot = hot;
        return this;
    }

     /**
     * Popularity score
     * @return hot
    **/
    public Integer getHot() {
        return hot;
    }


    public void setHot(Integer hot) {
        this.hot = hot;
    }

    public ListActivitiesResponseDataList masterOneLine(String masterOneLine) {
        
        this.masterOneLine = masterOneLine;
        return this;
    }

     /**
     * Main title first line
     * @return masterOneLine
    **/
    public String getMasterOneLine() {
        return masterOneLine;
    }


    public void setMasterOneLine(String masterOneLine) {
        this.masterOneLine = masterOneLine;
    }

    public ListActivitiesResponseDataList masterTwoLine(String masterTwoLine) {
        
        this.masterTwoLine = masterTwoLine;
        return this;
    }

     /**
     * Main title second line
     * @return masterTwoLine
    **/
    public String getMasterTwoLine() {
        return masterTwoLine;
    }


    public void setMasterTwoLine(String masterTwoLine) {
        this.masterTwoLine = masterTwoLine;
    }

    public ListActivitiesResponseDataList slaveOneLine(String slaveOneLine) {
        
        this.slaveOneLine = slaveOneLine;
        return this;
    }

     /**
     * Subtitle first line
     * @return slaveOneLine
    **/
    public String getSlaveOneLine() {
        return slaveOneLine;
    }


    public void setSlaveOneLine(String slaveOneLine) {
        this.slaveOneLine = slaveOneLine;
    }

    public ListActivitiesResponseDataList slaveTwoLine(String slaveTwoLine) {
        
        this.slaveTwoLine = slaveTwoLine;
        return this;
    }

     /**
     * Subtitle second line
     * @return slaveTwoLine
    **/
    public String getSlaveTwoLine() {
        return slaveTwoLine;
    }


    public void setSlaveTwoLine(String slaveTwoLine) {
        this.slaveTwoLine = slaveTwoLine;
    }

    public ListActivitiesResponseDataList competitionTitle(String competitionTitle) {
        
        this.competitionTitle = competitionTitle;
        return this;
    }

     /**
     * Activity title
     * @return competitionTitle
    **/
    public String getCompetitionTitle() {
        return competitionTitle;
    }


    public void setCompetitionTitle(String competitionTitle) {
        this.competitionTitle = competitionTitle;
    }

    public ListActivitiesResponseDataList topId(Integer topId) {
        
        this.topId = topId;
        return this;
    }

     /**
     * Pin ID, 0 means not pinned
     * @return topId
    **/
    public Integer getTopId() {
        return topId;
    }


    public void setTopId(Integer topId) {
        this.topId = topId;
    }

    public ListActivitiesResponseDataList parentId(Integer parentId) {
        
        this.parentId = parentId;
        return this;
    }

     /**
     * Parent activity ID, 0 means no parent activity
     * @return parentId
    **/
    public Integer getParentId() {
        return parentId;
    }


    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public ListActivitiesResponseDataList newImg(String newImg) {
        
        this.newImg = newImg;
        return this;
    }

     /**
     * New activity image URL (light mode)
     * @return newImg
    **/
    public String getNewImg() {
        return newImg;
    }


    public void setNewImg(String newImg) {
        this.newImg = newImg;
    }

    public ListActivitiesResponseDataList newImgDark(String newImgDark) {
        
        this.newImgDark = newImgDark;
        return this;
    }

     /**
     * New activity image URL (dark mode)
     * @return newImgDark
    **/
    public String getNewImgDark() {
        return newImgDark;
    }


    public void setNewImgDark(String newImgDark) {
        this.newImgDark = newImgDark;
    }

    public ListActivitiesResponseDataList tag(List<String> tag) {
        
        this.tag = tag;
        return this;
    }

    public ListActivitiesResponseDataList addTagItem(String tagItem) {
        this.tag.add(tagItem);
        return this;
    }

     /**
     * Activity tag list
     * @return tag
    **/
    public List<String> getTag() {
        return tag;
    }


    public void setTag(List<String> tag) {
        this.tag = tag;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListActivitiesResponseDataList listActivitiesResponseDataList = (ListActivitiesResponseDataList) o;
        return Objects.equals(this.id, listActivitiesResponseDataList.id) &&
                Objects.equals(this.typeId, listActivitiesResponseDataList.typeId) &&
                Objects.equals(this.typeName, listActivitiesResponseDataList.typeName) &&
                Objects.equals(this.competitionName, listActivitiesResponseDataList.competitionName) &&
                Objects.equals(this.startAt, listActivitiesResponseDataList.startAt) &&
                Objects.equals(this.endAt, listActivitiesResponseDataList.endAt) &&
                Objects.equals(this.img, listActivitiesResponseDataList.img) &&
                Objects.equals(this.imgDark, listActivitiesResponseDataList.imgDark) &&
                Objects.equals(this.url, listActivitiesResponseDataList.url) &&
                Objects.equals(this.hot, listActivitiesResponseDataList.hot) &&
                Objects.equals(this.masterOneLine, listActivitiesResponseDataList.masterOneLine) &&
                Objects.equals(this.masterTwoLine, listActivitiesResponseDataList.masterTwoLine) &&
                Objects.equals(this.slaveOneLine, listActivitiesResponseDataList.slaveOneLine) &&
                Objects.equals(this.slaveTwoLine, listActivitiesResponseDataList.slaveTwoLine) &&
                Objects.equals(this.competitionTitle, listActivitiesResponseDataList.competitionTitle) &&
                Objects.equals(this.topId, listActivitiesResponseDataList.topId) &&
                Objects.equals(this.parentId, listActivitiesResponseDataList.parentId) &&
                Objects.equals(this.newImg, listActivitiesResponseDataList.newImg) &&
                Objects.equals(this.newImgDark, listActivitiesResponseDataList.newImgDark) &&
                Objects.equals(this.tag, listActivitiesResponseDataList.tag);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, typeId, typeName, competitionName, startAt, endAt, img, imgDark, url, hot, masterOneLine, masterTwoLine, slaveOneLine, slaveTwoLine, competitionTitle, topId, parentId, newImg, newImgDark, tag);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ListActivitiesResponseDataList {\n");
        sb.append("      id: ").append(toIndentedString(id)).append("\n");
        sb.append("      typeId: ").append(toIndentedString(typeId)).append("\n");
        sb.append("      typeName: ").append(toIndentedString(typeName)).append("\n");
        sb.append("      competitionName: ").append(toIndentedString(competitionName)).append("\n");
        sb.append("      startAt: ").append(toIndentedString(startAt)).append("\n");
        sb.append("      endAt: ").append(toIndentedString(endAt)).append("\n");
        sb.append("      img: ").append(toIndentedString(img)).append("\n");
        sb.append("      imgDark: ").append(toIndentedString(imgDark)).append("\n");
        sb.append("      url: ").append(toIndentedString(url)).append("\n");
        sb.append("      hot: ").append(toIndentedString(hot)).append("\n");
        sb.append("      masterOneLine: ").append(toIndentedString(masterOneLine)).append("\n");
        sb.append("      masterTwoLine: ").append(toIndentedString(masterTwoLine)).append("\n");
        sb.append("      slaveOneLine: ").append(toIndentedString(slaveOneLine)).append("\n");
        sb.append("      slaveTwoLine: ").append(toIndentedString(slaveTwoLine)).append("\n");
        sb.append("      competitionTitle: ").append(toIndentedString(competitionTitle)).append("\n");
        sb.append("      topId: ").append(toIndentedString(topId)).append("\n");
        sb.append("      parentId: ").append(toIndentedString(parentId)).append("\n");
        sb.append("      newImg: ").append(toIndentedString(newImg)).append("\n");
        sb.append("      newImgDark: ").append(toIndentedString(newImgDark)).append("\n");
        sb.append("      tag: ").append(toIndentedString(tag)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

