/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.OrderBook2Data;
import java.io.IOException;

/**
 * OrderBook2
 */
public class OrderBook2 {
    public static final String SERIALIZED_NAME_DATA = "data";
    @SerializedName(SERIALIZED_NAME_DATA)
    private OrderBook2Data data;

    public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
    @SerializedName(SERIALIZED_NAME_TIMESTAMP)
    private Long timestamp;


    public OrderBook2 data(OrderBook2Data data) {
        
        this.data = data;
        return this;
    }

     /**
     * Get data
     * @return data
    **/
    @javax.annotation.Nullable
    public OrderBook2Data getData() {
        return data;
    }


    public void setData(OrderBook2Data data) {
        this.data = data;
    }

    public OrderBook2 timestamp(Long timestamp) {
        
        this.timestamp = timestamp;
        return this;
    }

     /**
     * Get timestamp
     * @return timestamp
    **/
    @javax.annotation.Nullable
    public Long getTimestamp() {
        return timestamp;
    }


    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderBook2 orderBook2 = (OrderBook2) o;
        return Objects.equals(this.data, orderBook2.data) &&
                Objects.equals(this.timestamp, orderBook2.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(data, timestamp);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderBook2 {\n");
        sb.append("      data: ").append(toIndentedString(data)).append("\n");
        sb.append("      timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

