/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * P2pAdDetail
 */
public class P2pAdDetail {
    public static final String SERIALIZED_NAME_RATE = "rate";
    @SerializedName(SERIALIZED_NAME_RATE)
    private String rate;

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;

    public static final String SERIALIZED_NAME_MIN_AMOUNT = "min_amount";
    @SerializedName(SERIALIZED_NAME_MIN_AMOUNT)
    private String minAmount;

    public static final String SERIALIZED_NAME_MAX_AMOUNT = "max_amount";
    @SerializedName(SERIALIZED_NAME_MAX_AMOUNT)
    private String maxAmount;

    public static final String SERIALIZED_NAME_TOTAL = "total";
    @SerializedName(SERIALIZED_NAME_TOTAL)
    private String total;

    public static final String SERIALIZED_NAME_PAY_ALI = "pay_ali";
    @SerializedName(SERIALIZED_NAME_PAY_ALI)
    private Integer payAli;

    public static final String SERIALIZED_NAME_PAY_BANK = "pay_bank";
    @SerializedName(SERIALIZED_NAME_PAY_BANK)
    private Integer payBank;

    public static final String SERIALIZED_NAME_PAY_PAYPAL = "pay_paypal";
    @SerializedName(SERIALIZED_NAME_PAY_PAYPAL)
    private Integer payPaypal;

    public static final String SERIALIZED_NAME_PAY_WECHAT = "pay_wechat";
    @SerializedName(SERIALIZED_NAME_PAY_WECHAT)
    private Integer payWechat;

    public static final String SERIALIZED_NAME_PAY_TYPE_NUM = "pay_type_num";
    @SerializedName(SERIALIZED_NAME_PAY_TYPE_NUM)
    private String payTypeNum;

    public static final String SERIALIZED_NAME_PAY_TYPE_JSON = "pay_type_json";
    @SerializedName(SERIALIZED_NAME_PAY_TYPE_JSON)
    private String payTypeJson;

    public static final String SERIALIZED_NAME_LOCKED_AMOUNT = "locked_amount";
    @SerializedName(SERIALIZED_NAME_LOCKED_AMOUNT)
    private String lockedAmount;

    public static final String SERIALIZED_NAME_ORDERID = "orderid";
    @SerializedName(SERIALIZED_NAME_ORDERID)
    private Integer orderid;

    public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
    @SerializedName(SERIALIZED_NAME_TIMESTAMP)
    private Integer timestamp;

    public static final String SERIALIZED_NAME_CURRENCY_TYPE = "currencyType";
    @SerializedName(SERIALIZED_NAME_CURRENCY_TYPE)
    private String currencyType;

    public static final String SERIALIZED_NAME_WANT_TYPE = "want_type";
    @SerializedName(SERIALIZED_NAME_WANT_TYPE)
    private String wantType;

    public static final String SERIALIZED_NAME_HIDE_RATE = "hide_rate";
    @SerializedName(SERIALIZED_NAME_HIDE_RATE)
    private String hideRate;

    public static final String SERIALIZED_NAME_TRADE_TIPS = "trade_tips";
    @SerializedName(SERIALIZED_NAME_TRADE_TIPS)
    private String tradeTips;

    public static final String SERIALIZED_NAME_AUTO_REPLY = "auto_reply";
    @SerializedName(SERIALIZED_NAME_AUTO_REPLY)
    private String autoReply;

    public static final String SERIALIZED_NAME_NEW_HAND = "new_hand";
    @SerializedName(SERIALIZED_NAME_NEW_HAND)
    private String newHand;

    public static final String SERIALIZED_NAME_RATE_REF_ID = "rate_ref_id";
    @SerializedName(SERIALIZED_NAME_RATE_REF_ID)
    private Integer rateRefId;

    public static final String SERIALIZED_NAME_RATE_OFFSET = "rate_offset";
    @SerializedName(SERIALIZED_NAME_RATE_OFFSET)
    private BigDecimal rateOffset;

    public static final String SERIALIZED_NAME_STATUS = "status";
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;

    public static final String SERIALIZED_NAME_RATE_FIXED = "rate_fixed";
    @SerializedName(SERIALIZED_NAME_RATE_FIXED)
    private Integer rateFixed;

    public static final String SERIALIZED_NAME_FLOAT_TREND = "float_trend";
    @SerializedName(SERIALIZED_NAME_FLOAT_TREND)
    private Integer floatTrend;

    public static final String SERIALIZED_NAME_EXPIRE_MIN = "expire_min";
    @SerializedName(SERIALIZED_NAME_EXPIRE_MIN)
    private Integer expireMin;

    public static final String SERIALIZED_NAME_TIER_LIMIT = "tier_limit";
    @SerializedName(SERIALIZED_NAME_TIER_LIMIT)
    private Integer tierLimit;

    public static final String SERIALIZED_NAME_REG_TIME_LIMIT = "reg_time_limit";
    @SerializedName(SERIALIZED_NAME_REG_TIME_LIMIT)
    private Integer regTimeLimit;

    public static final String SERIALIZED_NAME_ADVERTISERS_LIMIT = "advertisers_limit";
    @SerializedName(SERIALIZED_NAME_ADVERTISERS_LIMIT)
    private Integer advertisersLimit;

    public static final String SERIALIZED_NAME_VERIFIED_LIMIT = "verified_limit";
    @SerializedName(SERIALIZED_NAME_VERIFIED_LIMIT)
    private Integer verifiedLimit;

    public static final String SERIALIZED_NAME_MIN_COMPLETED_LIMIT = "min_completed_limit";
    @SerializedName(SERIALIZED_NAME_MIN_COMPLETED_LIMIT)
    private Integer minCompletedLimit;

    public static final String SERIALIZED_NAME_MAX_COMPLETED_LIMIT = "max_completed_limit";
    @SerializedName(SERIALIZED_NAME_MAX_COMPLETED_LIMIT)
    private Integer maxCompletedLimit;

    public static final String SERIALIZED_NAME_USER_ORDERS_LIMIT = "user_orders_limit";
    @SerializedName(SERIALIZED_NAME_USER_ORDERS_LIMIT)
    private Integer userOrdersLimit;

    public static final String SERIALIZED_NAME_COMPLETED_RATE_LIMIT = "completed_rate_limit";
    @SerializedName(SERIALIZED_NAME_COMPLETED_RATE_LIMIT)
    private BigDecimal completedRateLimit;

    public static final String SERIALIZED_NAME_USER_COUNTRY_LIMIT = "user_country_limit";
    @SerializedName(SERIALIZED_NAME_USER_COUNTRY_LIMIT)
    private Integer userCountryLimit;

    public static final String SERIALIZED_NAME_LIMIT_COUNTRY_CN = "limit_country_cn";
    @SerializedName(SERIALIZED_NAME_LIMIT_COUNTRY_CN)
    private String limitCountryCn;

    public static final String SERIALIZED_NAME_LIMIT_COUNTRY_EN = "limit_country_en";
    @SerializedName(SERIALIZED_NAME_LIMIT_COUNTRY_EN)
    private String limitCountryEn;

    public static final String SERIALIZED_NAME_IS_HEDGE = "is_hedge";
    @SerializedName(SERIALIZED_NAME_IS_HEDGE)
    private Integer isHedge;

    public static final String SERIALIZED_NAME_HIDE_PAYMENT = "hide_payment";
    @SerializedName(SERIALIZED_NAME_HIDE_PAYMENT)
    private Integer hidePayment;

    public static final String SERIALIZED_NAME_FEE = "fee";
    @SerializedName(SERIALIZED_NAME_FEE)
    private Integer fee;


    public P2pAdDetail rate(String rate) {
        
        this.rate = rate;
        return this;
    }

     /**
     * Price
     * @return rate
    **/
    @javax.annotation.Nullable
    public String getRate() {
        return rate;
    }


    public void setRate(String rate) {
        this.rate = rate;
    }

    public P2pAdDetail type(String type) {
        
        this.type = type;
        return this;
    }

     /**
     * Buy/Sell order
     * @return type
    **/
    @javax.annotation.Nullable
    public String getType() {
        return type;
    }


    public void setType(String type) {
        this.type = type;
    }

    public P2pAdDetail amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * Cryptocurrency amount
     * @return amount
    **/
    @javax.annotation.Nullable
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }

    public P2pAdDetail minAmount(String minAmount) {
        
        this.minAmount = minAmount;
        return this;
    }

     /**
     * Minimum limit
     * @return minAmount
    **/
    @javax.annotation.Nullable
    public String getMinAmount() {
        return minAmount;
    }


    public void setMinAmount(String minAmount) {
        this.minAmount = minAmount;
    }

    public P2pAdDetail maxAmount(String maxAmount) {
        
        this.maxAmount = maxAmount;
        return this;
    }

     /**
     * Maximum limit
     * @return maxAmount
    **/
    @javax.annotation.Nullable
    public String getMaxAmount() {
        return maxAmount;
    }


    public void setMaxAmount(String maxAmount) {
        this.maxAmount = maxAmount;
    }

    public P2pAdDetail total(String total) {
        
        this.total = total;
        return this;
    }

     /**
     * Fiat amount
     * @return total
    **/
    @javax.annotation.Nullable
    public String getTotal() {
        return total;
    }


    public void setTotal(String total) {
        this.total = total;
    }

    public P2pAdDetail payAli(Integer payAli) {
        
        this.payAli = payAli;
        return this;
    }

     /**
     * Whether Alipay payment is supported
     * @return payAli
    **/
    @javax.annotation.Nullable
    public Integer getPayAli() {
        return payAli;
    }


    public void setPayAli(Integer payAli) {
        this.payAli = payAli;
    }

    public P2pAdDetail payBank(Integer payBank) {
        
        this.payBank = payBank;
        return this;
    }

     /**
     * Whether bank payment is supported
     * @return payBank
    **/
    @javax.annotation.Nullable
    public Integer getPayBank() {
        return payBank;
    }


    public void setPayBank(Integer payBank) {
        this.payBank = payBank;
    }

    public P2pAdDetail payPaypal(Integer payPaypal) {
        
        this.payPaypal = payPaypal;
        return this;
    }

     /**
     * Whether PayPal payment is supported
     * @return payPaypal
    **/
    @javax.annotation.Nullable
    public Integer getPayPaypal() {
        return payPaypal;
    }


    public void setPayPaypal(Integer payPaypal) {
        this.payPaypal = payPaypal;
    }

    public P2pAdDetail payWechat(Integer payWechat) {
        
        this.payWechat = payWechat;
        return this;
    }

     /**
     * Whether WeChat payment is supported
     * @return payWechat
    **/
    @javax.annotation.Nullable
    public Integer getPayWechat() {
        return payWechat;
    }


    public void setPayWechat(Integer payWechat) {
        this.payWechat = payWechat;
    }

    public P2pAdDetail payTypeNum(String payTypeNum) {
        
        this.payTypeNum = payTypeNum;
        return this;
    }

     /**
     * Payment method ID list
     * @return payTypeNum
    **/
    @javax.annotation.Nullable
    public String getPayTypeNum() {
        return payTypeNum;
    }


    public void setPayTypeNum(String payTypeNum) {
        this.payTypeNum = payTypeNum;
    }

    public P2pAdDetail payTypeJson(String payTypeJson) {
        
        this.payTypeJson = payTypeJson;
        return this;
    }

     /**
     * Payment method list
     * @return payTypeJson
    **/
    @javax.annotation.Nullable
    public String getPayTypeJson() {
        return payTypeJson;
    }


    public void setPayTypeJson(String payTypeJson) {
        this.payTypeJson = payTypeJson;
    }

    public P2pAdDetail lockedAmount(String lockedAmount) {
        
        this.lockedAmount = lockedAmount;
        return this;
    }

     /**
     * Locked amount
     * @return lockedAmount
    **/
    @javax.annotation.Nullable
    public String getLockedAmount() {
        return lockedAmount;
    }


    public void setLockedAmount(String lockedAmount) {
        this.lockedAmount = lockedAmount;
    }

    public P2pAdDetail orderid(Integer orderid) {
        
        this.orderid = orderid;
        return this;
    }

     /**
     * Order ID
     * @return orderid
    **/
    @javax.annotation.Nullable
    public Integer getOrderid() {
        return orderid;
    }


    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    public P2pAdDetail timestamp(Integer timestamp) {
        
        this.timestamp = timestamp;
        return this;
    }

     /**
     * Created time
     * @return timestamp
    **/
    @javax.annotation.Nullable
    public Integer getTimestamp() {
        return timestamp;
    }


    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }

    public P2pAdDetail currencyType(String currencyType) {
        
        this.currencyType = currencyType;
        return this;
    }

     /**
     * Cryptocurrency type
     * @return currencyType
    **/
    @javax.annotation.Nullable
    public String getCurrencyType() {
        return currencyType;
    }


    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType;
    }

    public P2pAdDetail wantType(String wantType) {
        
        this.wantType = wantType;
        return this;
    }

     /**
     * Fiat type
     * @return wantType
    **/
    @javax.annotation.Nullable
    public String getWantType() {
        return wantType;
    }


    public void setWantType(String wantType) {
        this.wantType = wantType;
    }

    public P2pAdDetail hideRate(String hideRate) {
        
        this.hideRate = hideRate;
        return this;
    }

     /**
     * Hidden price
     * @return hideRate
    **/
    @javax.annotation.Nullable
    public String getHideRate() {
        return hideRate;
    }


    public void setHideRate(String hideRate) {
        this.hideRate = hideRate;
    }

    public P2pAdDetail tradeTips(String tradeTips) {
        
        this.tradeTips = tradeTips;
        return this;
    }

     /**
     * Trading terms
     * @return tradeTips
    **/
    @javax.annotation.Nullable
    public String getTradeTips() {
        return tradeTips;
    }


    public void setTradeTips(String tradeTips) {
        this.tradeTips = tradeTips;
    }

    public P2pAdDetail autoReply(String autoReply) {
        
        this.autoReply = autoReply;
        return this;
    }

     /**
     * Auto reply
     * @return autoReply
    **/
    @javax.annotation.Nullable
    public String getAutoReply() {
        return autoReply;
    }


    public void setAutoReply(String autoReply) {
        this.autoReply = autoReply;
    }

    public P2pAdDetail newHand(String newHand) {
        
        this.newHand = newHand;
        return this;
    }

     /**
     * Merchant-friendly order
     * @return newHand
    **/
    @javax.annotation.Nullable
    public String getNewHand() {
        return newHand;
    }


    public void setNewHand(String newHand) {
        this.newHand = newHand;
    }

    public P2pAdDetail rateRefId(Integer rateRefId) {
        
        this.rateRefId = rateRefId;
        return this;
    }

     /**
     * Floating price reference ID: 1&#x3D;Platform reference price, 3&#x3D;Spot reference price (≤0 means fixed price, &gt;0 means floating price)
     * @return rateRefId
    **/
    @javax.annotation.Nullable
    public Integer getRateRefId() {
        return rateRefId;
    }


    public void setRateRefId(Integer rateRefId) {
        this.rateRefId = rateRefId;
    }

    public P2pAdDetail rateOffset(BigDecimal rateOffset) {
        
        this.rateOffset = rateOffset;
        return this;
    }

     /**
     * Floating ratio (absolute value)
     * @return rateOffset
    **/
    @javax.annotation.Nullable
    public BigDecimal getRateOffset() {
        return rateOffset;
    }


    public void setRateOffset(BigDecimal rateOffset) {
        this.rateOffset = rateOffset;
    }

    public P2pAdDetail status(String status) {
        
        this.status = status;
        return this;
    }

     /**
     * Status
     * @return status
    **/
    @javax.annotation.Nullable
    public String getStatus() {
        return status;
    }


    public void setStatus(String status) {
        this.status = status;
    }

    public P2pAdDetail rateFixed(Integer rateFixed) {
        
        this.rateFixed = rateFixed;
        return this;
    }

     /**
     * 0&#x3D;Floating, 1&#x3D;Fixed
     * @return rateFixed
    **/
    @javax.annotation.Nullable
    public Integer getRateFixed() {
        return rateFixed;
    }


    public void setRateFixed(Integer rateFixed) {
        this.rateFixed = rateFixed;
    }

    public P2pAdDetail floatTrend(Integer floatTrend) {
        
        this.floatTrend = floatTrend;
        return this;
    }

     /**
     * 0&#x3D;Upward float, 1&#x3D;Downward float
     * @return floatTrend
    **/
    @javax.annotation.Nullable
    public Integer getFloatTrend() {
        return floatTrend;
    }


    public void setFloatTrend(Integer floatTrend) {
        this.floatTrend = floatTrend;
    }

    public P2pAdDetail expireMin(Integer expireMin) {
        
        this.expireMin = expireMin;
        return this;
    }

     /**
     * Timeout (minutes)
     * @return expireMin
    **/
    @javax.annotation.Nullable
    public Integer getExpireMin() {
        return expireMin;
    }


    public void setExpireMin(Integer expireMin) {
        this.expireMin = expireMin;
    }

    public P2pAdDetail tierLimit(Integer tierLimit) {
        
        this.tierLimit = tierLimit;
        return this;
    }

     /**
     * Tier limit
     * @return tierLimit
    **/
    @javax.annotation.Nullable
    public Integer getTierLimit() {
        return tierLimit;
    }


    public void setTierLimit(Integer tierLimit) {
        this.tierLimit = tierLimit;
    }

    public P2pAdDetail regTimeLimit(Integer regTimeLimit) {
        
        this.regTimeLimit = regTimeLimit;
        return this;
    }

     /**
     * Registration time limit
     * @return regTimeLimit
    **/
    @javax.annotation.Nullable
    public Integer getRegTimeLimit() {
        return regTimeLimit;
    }


    public void setRegTimeLimit(Integer regTimeLimit) {
        this.regTimeLimit = regTimeLimit;
    }

    public P2pAdDetail advertisersLimit(Integer advertisersLimit) {
        
        this.advertisersLimit = advertisersLimit;
        return this;
    }

     /**
     * Do not trade with advertisers, advertiser limit: 0&#x3D;No limit, 1&#x3D;Limit
     * @return advertisersLimit
    **/
    @javax.annotation.Nullable
    public Integer getAdvertisersLimit() {
        return advertisersLimit;
    }


    public void setAdvertisersLimit(Integer advertisersLimit) {
        this.advertisersLimit = advertisersLimit;
    }

    public P2pAdDetail verifiedLimit(Integer verifiedLimit) {
        
        this.verifiedLimit = verifiedLimit;
        return this;
    }

     /**
     * kyclimit
     * @return verifiedLimit
    **/
    @javax.annotation.Nullable
    public Integer getVerifiedLimit() {
        return verifiedLimit;
    }


    public void setVerifiedLimit(Integer verifiedLimit) {
        this.verifiedLimit = verifiedLimit;
    }

    public P2pAdDetail minCompletedLimit(Integer minCompletedLimit) {
        
        this.minCompletedLimit = minCompletedLimit;
        return this;
    }

     /**
     * Minimum limit of completed orders
     * @return minCompletedLimit
    **/
    @javax.annotation.Nullable
    public Integer getMinCompletedLimit() {
        return minCompletedLimit;
    }


    public void setMinCompletedLimit(Integer minCompletedLimit) {
        this.minCompletedLimit = minCompletedLimit;
    }

    public P2pAdDetail maxCompletedLimit(Integer maxCompletedLimit) {
        
        this.maxCompletedLimit = maxCompletedLimit;
        return this;
    }

     /**
     * Maximum limit of completed orders
     * @return maxCompletedLimit
    **/
    @javax.annotation.Nullable
    public Integer getMaxCompletedLimit() {
        return maxCompletedLimit;
    }


    public void setMaxCompletedLimit(Integer maxCompletedLimit) {
        this.maxCompletedLimit = maxCompletedLimit;
    }

    public P2pAdDetail userOrdersLimit(Integer userOrdersLimit) {
        
        this.userOrdersLimit = userOrdersLimit;
        return this;
    }

     /**
     * Order count limit
     * @return userOrdersLimit
    **/
    @javax.annotation.Nullable
    public Integer getUserOrdersLimit() {
        return userOrdersLimit;
    }


    public void setUserOrdersLimit(Integer userOrdersLimit) {
        this.userOrdersLimit = userOrdersLimit;
    }

    public P2pAdDetail completedRateLimit(BigDecimal completedRateLimit) {
        
        this.completedRateLimit = completedRateLimit;
        return this;
    }

     /**
     * 30-day completion rate limit
     * @return completedRateLimit
    **/
    @javax.annotation.Nullable
    public BigDecimal getCompletedRateLimit() {
        return completedRateLimit;
    }


    public void setCompletedRateLimit(BigDecimal completedRateLimit) {
        this.completedRateLimit = completedRateLimit;
    }

    public P2pAdDetail userCountryLimit(Integer userCountryLimit) {
        
        this.userCountryLimit = userCountryLimit;
        return this;
    }

     /**
     * KYC nationality restriction
     * @return userCountryLimit
    **/
    @javax.annotation.Nullable
    public Integer getUserCountryLimit() {
        return userCountryLimit;
    }


    public void setUserCountryLimit(Integer userCountryLimit) {
        this.userCountryLimit = userCountryLimit;
    }

    public P2pAdDetail limitCountryCn(String limitCountryCn) {
        
        this.limitCountryCn = limitCountryCn;
        return this;
    }

     /**
     * Restricted nationality (Chinese)
     * @return limitCountryCn
    **/
    @javax.annotation.Nullable
    public String getLimitCountryCn() {
        return limitCountryCn;
    }


    public void setLimitCountryCn(String limitCountryCn) {
        this.limitCountryCn = limitCountryCn;
    }

    public P2pAdDetail limitCountryEn(String limitCountryEn) {
        
        this.limitCountryEn = limitCountryEn;
        return this;
    }

     /**
     * Restricted nationality (English)
     * @return limitCountryEn
    **/
    @javax.annotation.Nullable
    public String getLimitCountryEn() {
        return limitCountryEn;
    }


    public void setLimitCountryEn(String limitCountryEn) {
        this.limitCountryEn = limitCountryEn;
    }

    public P2pAdDetail isHedge(Integer isHedge) {
        
        this.isHedge = isHedge;
        return this;
    }

     /**
     * Whether auto delegation
     * @return isHedge
    **/
    @javax.annotation.Nullable
    public Integer getIsHedge() {
        return isHedge;
    }


    public void setIsHedge(Integer isHedge) {
        this.isHedge = isHedge;
    }

    public P2pAdDetail hidePayment(Integer hidePayment) {
        
        this.hidePayment = hidePayment;
        return this;
    }

     /**
     * Whether to hide payment method
     * @return hidePayment
    **/
    @javax.annotation.Nullable
    public Integer getHidePayment() {
        return hidePayment;
    }


    public void setHidePayment(Integer hidePayment) {
        this.hidePayment = hidePayment;
    }

    public P2pAdDetail fee(Integer fee) {
        
        this.fee = fee;
        return this;
    }

     /**
     * fee
     * @return fee
    **/
    @javax.annotation.Nullable
    public Integer getFee() {
        return fee;
    }


    public void setFee(Integer fee) {
        this.fee = fee;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        P2pAdDetail p2pAdDetail = (P2pAdDetail) o;
        return Objects.equals(this.rate, p2pAdDetail.rate) &&
                Objects.equals(this.type, p2pAdDetail.type) &&
                Objects.equals(this.amount, p2pAdDetail.amount) &&
                Objects.equals(this.minAmount, p2pAdDetail.minAmount) &&
                Objects.equals(this.maxAmount, p2pAdDetail.maxAmount) &&
                Objects.equals(this.total, p2pAdDetail.total) &&
                Objects.equals(this.payAli, p2pAdDetail.payAli) &&
                Objects.equals(this.payBank, p2pAdDetail.payBank) &&
                Objects.equals(this.payPaypal, p2pAdDetail.payPaypal) &&
                Objects.equals(this.payWechat, p2pAdDetail.payWechat) &&
                Objects.equals(this.payTypeNum, p2pAdDetail.payTypeNum) &&
                Objects.equals(this.payTypeJson, p2pAdDetail.payTypeJson) &&
                Objects.equals(this.lockedAmount, p2pAdDetail.lockedAmount) &&
                Objects.equals(this.orderid, p2pAdDetail.orderid) &&
                Objects.equals(this.timestamp, p2pAdDetail.timestamp) &&
                Objects.equals(this.currencyType, p2pAdDetail.currencyType) &&
                Objects.equals(this.wantType, p2pAdDetail.wantType) &&
                Objects.equals(this.hideRate, p2pAdDetail.hideRate) &&
                Objects.equals(this.tradeTips, p2pAdDetail.tradeTips) &&
                Objects.equals(this.autoReply, p2pAdDetail.autoReply) &&
                Objects.equals(this.newHand, p2pAdDetail.newHand) &&
                Objects.equals(this.rateRefId, p2pAdDetail.rateRefId) &&
                Objects.equals(this.rateOffset, p2pAdDetail.rateOffset) &&
                Objects.equals(this.status, p2pAdDetail.status) &&
                Objects.equals(this.rateFixed, p2pAdDetail.rateFixed) &&
                Objects.equals(this.floatTrend, p2pAdDetail.floatTrend) &&
                Objects.equals(this.expireMin, p2pAdDetail.expireMin) &&
                Objects.equals(this.tierLimit, p2pAdDetail.tierLimit) &&
                Objects.equals(this.regTimeLimit, p2pAdDetail.regTimeLimit) &&
                Objects.equals(this.advertisersLimit, p2pAdDetail.advertisersLimit) &&
                Objects.equals(this.verifiedLimit, p2pAdDetail.verifiedLimit) &&
                Objects.equals(this.minCompletedLimit, p2pAdDetail.minCompletedLimit) &&
                Objects.equals(this.maxCompletedLimit, p2pAdDetail.maxCompletedLimit) &&
                Objects.equals(this.userOrdersLimit, p2pAdDetail.userOrdersLimit) &&
                Objects.equals(this.completedRateLimit, p2pAdDetail.completedRateLimit) &&
                Objects.equals(this.userCountryLimit, p2pAdDetail.userCountryLimit) &&
                Objects.equals(this.limitCountryCn, p2pAdDetail.limitCountryCn) &&
                Objects.equals(this.limitCountryEn, p2pAdDetail.limitCountryEn) &&
                Objects.equals(this.isHedge, p2pAdDetail.isHedge) &&
                Objects.equals(this.hidePayment, p2pAdDetail.hidePayment) &&
                Objects.equals(this.fee, p2pAdDetail.fee);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rate, type, amount, minAmount, maxAmount, total, payAli, payBank, payPaypal, payWechat, payTypeNum, payTypeJson, lockedAmount, orderid, timestamp, currencyType, wantType, hideRate, tradeTips, autoReply, newHand, rateRefId, rateOffset, status, rateFixed, floatTrend, expireMin, tierLimit, regTimeLimit, advertisersLimit, verifiedLimit, minCompletedLimit, maxCompletedLimit, userOrdersLimit, completedRateLimit, userCountryLimit, limitCountryCn, limitCountryEn, isHedge, hidePayment, fee);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class P2pAdDetail {\n");
        sb.append("      rate: ").append(toIndentedString(rate)).append("\n");
        sb.append("      type: ").append(toIndentedString(type)).append("\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("      minAmount: ").append(toIndentedString(minAmount)).append("\n");
        sb.append("      maxAmount: ").append(toIndentedString(maxAmount)).append("\n");
        sb.append("      total: ").append(toIndentedString(total)).append("\n");
        sb.append("      payAli: ").append(toIndentedString(payAli)).append("\n");
        sb.append("      payBank: ").append(toIndentedString(payBank)).append("\n");
        sb.append("      payPaypal: ").append(toIndentedString(payPaypal)).append("\n");
        sb.append("      payWechat: ").append(toIndentedString(payWechat)).append("\n");
        sb.append("      payTypeNum: ").append(toIndentedString(payTypeNum)).append("\n");
        sb.append("      payTypeJson: ").append(toIndentedString(payTypeJson)).append("\n");
        sb.append("      lockedAmount: ").append(toIndentedString(lockedAmount)).append("\n");
        sb.append("      orderid: ").append(toIndentedString(orderid)).append("\n");
        sb.append("      timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("      currencyType: ").append(toIndentedString(currencyType)).append("\n");
        sb.append("      wantType: ").append(toIndentedString(wantType)).append("\n");
        sb.append("      hideRate: ").append(toIndentedString(hideRate)).append("\n");
        sb.append("      tradeTips: ").append(toIndentedString(tradeTips)).append("\n");
        sb.append("      autoReply: ").append(toIndentedString(autoReply)).append("\n");
        sb.append("      newHand: ").append(toIndentedString(newHand)).append("\n");
        sb.append("      rateRefId: ").append(toIndentedString(rateRefId)).append("\n");
        sb.append("      rateOffset: ").append(toIndentedString(rateOffset)).append("\n");
        sb.append("      status: ").append(toIndentedString(status)).append("\n");
        sb.append("      rateFixed: ").append(toIndentedString(rateFixed)).append("\n");
        sb.append("      floatTrend: ").append(toIndentedString(floatTrend)).append("\n");
        sb.append("      expireMin: ").append(toIndentedString(expireMin)).append("\n");
        sb.append("      tierLimit: ").append(toIndentedString(tierLimit)).append("\n");
        sb.append("      regTimeLimit: ").append(toIndentedString(regTimeLimit)).append("\n");
        sb.append("      advertisersLimit: ").append(toIndentedString(advertisersLimit)).append("\n");
        sb.append("      verifiedLimit: ").append(toIndentedString(verifiedLimit)).append("\n");
        sb.append("      minCompletedLimit: ").append(toIndentedString(minCompletedLimit)).append("\n");
        sb.append("      maxCompletedLimit: ").append(toIndentedString(maxCompletedLimit)).append("\n");
        sb.append("      userOrdersLimit: ").append(toIndentedString(userOrdersLimit)).append("\n");
        sb.append("      completedRateLimit: ").append(toIndentedString(completedRateLimit)).append("\n");
        sb.append("      userCountryLimit: ").append(toIndentedString(userCountryLimit)).append("\n");
        sb.append("      limitCountryCn: ").append(toIndentedString(limitCountryCn)).append("\n");
        sb.append("      limitCountryEn: ").append(toIndentedString(limitCountryEn)).append("\n");
        sb.append("      isHedge: ").append(toIndentedString(isHedge)).append("\n");
        sb.append("      hidePayment: ").append(toIndentedString(hidePayment)).append("\n");
        sb.append("      fee: ").append(toIndentedString(fee)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

