/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.P2pPaymentMethodAccount;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * P2pPaymentMethodGroup
 */
public class P2pPaymentMethodGroup {
    public static final String SERIALIZED_NAME_PAY_TYPE = "pay_type";
    @SerializedName(SERIALIZED_NAME_PAY_TYPE)
    private String payType;

    public static final String SERIALIZED_NAME_PAY_NAME = "pay_name";
    @SerializedName(SERIALIZED_NAME_PAY_NAME)
    private String payName;

    public static final String SERIALIZED_NAME_IDS = "ids";
    @SerializedName(SERIALIZED_NAME_IDS)
    private List<Integer> ids = null;

    public static final String SERIALIZED_NAME_LIST = "list";
    @SerializedName(SERIALIZED_NAME_LIST)
    private List<P2pPaymentMethodAccount> list = null;


    public P2pPaymentMethodGroup payType(String payType) {
        
        this.payType = payType;
        return this;
    }

     /**
     * Payment method type
     * @return payType
    **/
    @javax.annotation.Nullable
    public String getPayType() {
        return payType;
    }


    public void setPayType(String payType) {
        this.payType = payType;
    }

    public P2pPaymentMethodGroup payName(String payName) {
        
        this.payName = payName;
        return this;
    }

     /**
     * Payment method name
     * @return payName
    **/
    @javax.annotation.Nullable
    public String getPayName() {
        return payName;
    }


    public void setPayName(String payName) {
        this.payName = payName;
    }

    public P2pPaymentMethodGroup ids(List<Integer> ids) {
        
        this.ids = ids;
        return this;
    }

    public P2pPaymentMethodGroup addIdsItem(Integer idsItem) {
        if (this.ids == null) {
            this.ids = new ArrayList<>();
        }
        this.ids.add(idsItem);
        return this;
    }

     /**
     * User&#39;s currently bound payment method (primary key ID)
     * @return ids
    **/
    @javax.annotation.Nullable
    public List<Integer> getIds() {
        return ids;
    }


    public void setIds(List<Integer> ids) {
        this.ids = ids;
    }

    public P2pPaymentMethodGroup list(List<P2pPaymentMethodAccount> list) {
        
        this.list = list;
        return this;
    }

    public P2pPaymentMethodGroup addListItem(P2pPaymentMethodAccount listItem) {
        if (this.list == null) {
            this.list = new ArrayList<>();
        }
        this.list.add(listItem);
        return this;
    }

     /**
     * Get list
     * @return list
    **/
    @javax.annotation.Nullable
    public List<P2pPaymentMethodAccount> getList() {
        return list;
    }


    public void setList(List<P2pPaymentMethodAccount> list) {
        this.list = list;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        P2pPaymentMethodGroup p2pPaymentMethodGroup = (P2pPaymentMethodGroup) o;
        return Objects.equals(this.payType, p2pPaymentMethodGroup.payType) &&
                Objects.equals(this.payName, p2pPaymentMethodGroup.payName) &&
                Objects.equals(this.ids, p2pPaymentMethodGroup.ids) &&
                Objects.equals(this.list, p2pPaymentMethodGroup.list);
    }

    @Override
    public int hashCode() {
        return Objects.hash(payType, payName, ids, list);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class P2pPaymentMethodGroup {\n");
        sb.append("      payType: ").append(toIndentedString(payType)).append("\n");
        sb.append("      payName: ").append(toIndentedString(payName)).append("\n");
        sb.append("      ids: ").append(toIndentedString(ids)).append("\n");
        sb.append("      list: ").append(toIndentedString(list)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

