/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.OtherContact;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * PartnerApplication
 */
public class PartnerApplication {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;

    public static final String SERIALIZED_NAME_UID = "uid";
    @SerializedName(SERIALIZED_NAME_UID)
    private Integer uid;

    public static final String SERIALIZED_NAME_LANGUAGE = "language";
    @SerializedName(SERIALIZED_NAME_LANGUAGE)
    private String language;

    public static final String SERIALIZED_NAME_COUNTRY_ID = "country_id";
    @SerializedName(SERIALIZED_NAME_COUNTRY_ID)
    private Integer countryId;

    public static final String SERIALIZED_NAME_FIRSTNAME = "firstname";
    @SerializedName(SERIALIZED_NAME_FIRSTNAME)
    private String firstname;

    public static final String SERIALIZED_NAME_LASTNAME = "lastname";
    @SerializedName(SERIALIZED_NAME_LASTNAME)
    private String lastname;

    public static final String SERIALIZED_NAME_EMAIL = "email";
    @SerializedName(SERIALIZED_NAME_EMAIL)
    private String email;

    public static final String SERIALIZED_NAME_JOIN_UID = "join_uid";
    @SerializedName(SERIALIZED_NAME_JOIN_UID)
    private Integer joinUid;

    public static final String SERIALIZED_NAME_JOIN_COUNTRY_ID = "join_country_id";
    @SerializedName(SERIALIZED_NAME_JOIN_COUNTRY_ID)
    private Integer joinCountryId;

    public static final String SERIALIZED_NAME_IDENTITY_COMMENT = "identity_comment";
    @SerializedName(SERIALIZED_NAME_IDENTITY_COMMENT)
    private String identityComment;

    public static final String SERIALIZED_NAME_PROMOTION_CHANNELS = "promotion_channels";
    @SerializedName(SERIALIZED_NAME_PROMOTION_CHANNELS)
    private String promotionChannels;

    public static final String SERIALIZED_NAME_CONTACT_DETAILS = "contact_details";
    @SerializedName(SERIALIZED_NAME_CONTACT_DETAILS)
    private String contactDetails;

    public static final String SERIALIZED_NAME_KNOW_DETAILS = "know_details";
    @SerializedName(SERIALIZED_NAME_KNOW_DETAILS)
    private String knowDetails;

    public static final String SERIALIZED_NAME_QUESTION_LANG = "question_lang";
    @SerializedName(SERIALIZED_NAME_QUESTION_LANG)
    private String questionLang;

    public static final String SERIALIZED_NAME_CREATE_TIMEST = "create_timest";
    @SerializedName(SERIALIZED_NAME_CREATE_TIMEST)
    private OffsetDateTime createTimest;

    public static final String SERIALIZED_NAME_UPDATE_TIMEST = "update_timest";
    @SerializedName(SERIALIZED_NAME_UPDATE_TIMEST)
    private OffsetDateTime updateTimest;

    public static final String SERIALIZED_NAME_APPLY_TYPE = "apply_type";
    @SerializedName(SERIALIZED_NAME_APPLY_TYPE)
    private Integer applyType;

    public static final String SERIALIZED_NAME_AUDIT_STATUS = "audit_status";
    @SerializedName(SERIALIZED_NAME_AUDIT_STATUS)
    private Integer auditStatus;

    public static final String SERIALIZED_NAME_EDIT_COUNTS = "edit_counts";
    @SerializedName(SERIALIZED_NAME_EDIT_COUNTS)
    private Integer editCounts;

    public static final String SERIALIZED_NAME_PROOF_IMAGES = "proof_images";
    @SerializedName(SERIALIZED_NAME_PROOF_IMAGES)
    private String proofImages;

    public static final String SERIALIZED_NAME_PROOF_VIDEOS = "proof_videos";
    @SerializedName(SERIALIZED_NAME_PROOF_VIDEOS)
    private String proofVideos;

    public static final String SERIALIZED_NAME_PROOF_URL = "proof_url";
    @SerializedName(SERIALIZED_NAME_PROOF_URL)
    private URI proofUrl;

    public static final String SERIALIZED_NAME_AUDIT_REASON = "audit_reason";
    @SerializedName(SERIALIZED_NAME_AUDIT_REASON)
    private Integer auditReason;

    public static final String SERIALIZED_NAME_CHANNEL_TYPE = "channel_type";
    @SerializedName(SERIALIZED_NAME_CHANNEL_TYPE)
    private Integer channelType;

    public static final String SERIALIZED_NAME_REGION = "region";
    @SerializedName(SERIALIZED_NAME_REGION)
    private String region;

    public static final String SERIALIZED_NAME_PHONE = "phone";
    @SerializedName(SERIALIZED_NAME_PHONE)
    private String phone;

    public static final String SERIALIZED_NAME_TELEGRAM = "telegram";
    @SerializedName(SERIALIZED_NAME_TELEGRAM)
    private String telegram;

    public static final String SERIALIZED_NAME_OTHER_CONTACT = "other_contact";
    @SerializedName(SERIALIZED_NAME_OTHER_CONTACT)
    private OtherContact otherContact;

    public static final String SERIALIZED_NAME_PROOF_IMAGES_URL_LIST = "proof_images_url_list";
    @SerializedName(SERIALIZED_NAME_PROOF_IMAGES_URL_LIST)
    private List<URI> proofImagesUrlList = null;

    public static final String SERIALIZED_NAME_PROOF_VIDEOS_URL_LIST = "proof_videos_url_list";
    @SerializedName(SERIALIZED_NAME_PROOF_VIDEOS_URL_LIST)
    private List<URI> proofVideosUrlList = null;

    public static final String SERIALIZED_NAME_APPLY_MSG = "apply_msg";
    @SerializedName(SERIALIZED_NAME_APPLY_MSG)
    private String applyMsg;

    public static final String SERIALIZED_NAME_JUMP_URL = "jump_url";
    @SerializedName(SERIALIZED_NAME_JUMP_URL)
    private String jumpUrl;


    public PartnerApplication id(Integer id) {
        
        this.id = id;
        return this;
    }

     /**
     * Application record ID
     * @return id
    **/
    @javax.annotation.Nullable
    public Integer getId() {
        return id;
    }


    public void setId(Integer id) {
        this.id = id;
    }

    public PartnerApplication uid(Integer uid) {
        
        this.uid = uid;
        return this;
    }

     /**
     * User ID
     * @return uid
    **/
    @javax.annotation.Nullable
    public Integer getUid() {
        return uid;
    }


    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public PartnerApplication language(String language) {
        
        this.language = language;
        return this;
    }

     /**
     * Language code
     * @return language
    **/
    @javax.annotation.Nullable
    public String getLanguage() {
        return language;
    }


    public void setLanguage(String language) {
        this.language = language;
    }

    public PartnerApplication countryId(Integer countryId) {
        
        this.countryId = countryId;
        return this;
    }

     /**
     * Country ID
     * @return countryId
    **/
    @javax.annotation.Nullable
    public Integer getCountryId() {
        return countryId;
    }


    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    public PartnerApplication firstname(String firstname) {
        
        this.firstname = firstname;
        return this;
    }

     /**
     * First name
     * @return firstname
    **/
    @javax.annotation.Nullable
    public String getFirstname() {
        return firstname;
    }


    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public PartnerApplication lastname(String lastname) {
        
        this.lastname = lastname;
        return this;
    }

     /**
     * Last name
     * @return lastname
    **/
    @javax.annotation.Nullable
    public String getLastname() {
        return lastname;
    }


    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public PartnerApplication email(String email) {
        
        this.email = email;
        return this;
    }

     /**
     * Email address
     * @return email
    **/
    @javax.annotation.Nullable
    public String getEmail() {
        return email;
    }


    public void setEmail(String email) {
        this.email = email;
    }

    public PartnerApplication joinUid(Integer joinUid) {
        
        this.joinUid = joinUid;
        return this;
    }

     /**
     * Joined user ID
     * @return joinUid
    **/
    @javax.annotation.Nullable
    public Integer getJoinUid() {
        return joinUid;
    }


    public void setJoinUid(Integer joinUid) {
        this.joinUid = joinUid;
    }

    public PartnerApplication joinCountryId(Integer joinCountryId) {
        
        this.joinCountryId = joinCountryId;
        return this;
    }

     /**
     * Joined country ID
     * @return joinCountryId
    **/
    @javax.annotation.Nullable
    public Integer getJoinCountryId() {
        return joinCountryId;
    }


    public void setJoinCountryId(Integer joinCountryId) {
        this.joinCountryId = joinCountryId;
    }

    public PartnerApplication identityComment(String identityComment) {
        
        this.identityComment = identityComment;
        return this;
    }

     /**
     * Identity description
     * @return identityComment
    **/
    @javax.annotation.Nullable
    public String getIdentityComment() {
        return identityComment;
    }


    public void setIdentityComment(String identityComment) {
        this.identityComment = identityComment;
    }

    public PartnerApplication promotionChannels(String promotionChannels) {
        
        this.promotionChannels = promotionChannels;
        return this;
    }

     /**
     * Promotion channels, separated by |
     * @return promotionChannels
    **/
    @javax.annotation.Nullable
    public String getPromotionChannels() {
        return promotionChannels;
    }


    public void setPromotionChannels(String promotionChannels) {
        this.promotionChannels = promotionChannels;
    }

    public PartnerApplication contactDetails(String contactDetails) {
        
        this.contactDetails = contactDetails;
        return this;
    }

     /**
     * Contact details (JSON string)
     * @return contactDetails
    **/
    @javax.annotation.Nullable
    public String getContactDetails() {
        return contactDetails;
    }


    public void setContactDetails(String contactDetails) {
        this.contactDetails = contactDetails;
    }

    public PartnerApplication knowDetails(String knowDetails) {
        
        this.knowDetails = knowDetails;
        return this;
    }

     /**
     * Learn more
     * @return knowDetails
    **/
    @javax.annotation.Nullable
    public String getKnowDetails() {
        return knowDetails;
    }


    public void setKnowDetails(String knowDetails) {
        this.knowDetails = knowDetails;
    }

    public PartnerApplication questionLang(String questionLang) {
        
        this.questionLang = questionLang;
        return this;
    }

     /**
     * Question language
     * @return questionLang
    **/
    @javax.annotation.Nullable
    public String getQuestionLang() {
        return questionLang;
    }


    public void setQuestionLang(String questionLang) {
        this.questionLang = questionLang;
    }

    public PartnerApplication createTimest(OffsetDateTime createTimest) {
        
        this.createTimest = createTimest;
        return this;
    }

     /**
     * Created time
     * @return createTimest
    **/
    @javax.annotation.Nullable
    public OffsetDateTime getCreateTimest() {
        return createTimest;
    }


    public void setCreateTimest(OffsetDateTime createTimest) {
        this.createTimest = createTimest;
    }

    public PartnerApplication updateTimest(OffsetDateTime updateTimest) {
        
        this.updateTimest = updateTimest;
        return this;
    }

     /**
     * Update time
     * @return updateTimest
    **/
    @javax.annotation.Nullable
    public OffsetDateTime getUpdateTimest() {
        return updateTimest;
    }


    public void setUpdateTimest(OffsetDateTime updateTimest) {
        this.updateTimest = updateTimest;
    }

    public PartnerApplication applyType(Integer applyType) {
        
        this.applyType = applyType;
        return this;
    }

     /**
     * Application type
     * @return applyType
    **/
    @javax.annotation.Nullable
    public Integer getApplyType() {
        return applyType;
    }


    public void setApplyType(Integer applyType) {
        this.applyType = applyType;
    }

    public PartnerApplication auditStatus(Integer auditStatus) {
        
        this.auditStatus = auditStatus;
        return this;
    }

     /**
     * Review status (0 - pending, 1 - approved, 2 - rejected)
     * @return auditStatus
    **/
    @javax.annotation.Nullable
    public Integer getAuditStatus() {
        return auditStatus;
    }


    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    public PartnerApplication editCounts(Integer editCounts) {
        
        this.editCounts = editCounts;
        return this;
    }

     /**
     * Edit count
     * @return editCounts
    **/
    @javax.annotation.Nullable
    public Integer getEditCounts() {
        return editCounts;
    }


    public void setEditCounts(Integer editCounts) {
        this.editCounts = editCounts;
    }

    public PartnerApplication proofImages(String proofImages) {
        
        this.proofImages = proofImages;
        return this;
    }

     /**
     * Proof image path
     * @return proofImages
    **/
    @javax.annotation.Nullable
    public String getProofImages() {
        return proofImages;
    }


    public void setProofImages(String proofImages) {
        this.proofImages = proofImages;
    }

    public PartnerApplication proofVideos(String proofVideos) {
        
        this.proofVideos = proofVideos;
        return this;
    }

     /**
     * Proof video path
     * @return proofVideos
    **/
    @javax.annotation.Nullable
    public String getProofVideos() {
        return proofVideos;
    }


    public void setProofVideos(String proofVideos) {
        this.proofVideos = proofVideos;
    }

    public PartnerApplication proofUrl(URI proofUrl) {
        
        this.proofUrl = proofUrl;
        return this;
    }

     /**
     * Proof link
     * @return proofUrl
    **/
    @javax.annotation.Nullable
    public URI getProofUrl() {
        return proofUrl;
    }


    public void setProofUrl(URI proofUrl) {
        this.proofUrl = proofUrl;
    }

    public PartnerApplication auditReason(Integer auditReason) {
        
        this.auditReason = auditReason;
        return this;
    }

     /**
     * Review reason code
     * @return auditReason
    **/
    @javax.annotation.Nullable
    public Integer getAuditReason() {
        return auditReason;
    }


    public void setAuditReason(Integer auditReason) {
        this.auditReason = auditReason;
    }

    public PartnerApplication channelType(Integer channelType) {
        
        this.channelType = channelType;
        return this;
    }

     /**
     * Channel type
     * @return channelType
    **/
    @javax.annotation.Nullable
    public Integer getChannelType() {
        return channelType;
    }


    public void setChannelType(Integer channelType) {
        this.channelType = channelType;
    }

    public PartnerApplication region(String region) {
        
        this.region = region;
        return this;
    }

     /**
     * Region
     * @return region
    **/
    @javax.annotation.Nullable
    public String getRegion() {
        return region;
    }


    public void setRegion(String region) {
        this.region = region;
    }

    public PartnerApplication phone(String phone) {
        
        this.phone = phone;
        return this;
    }

     /**
     * Phone number
     * @return phone
    **/
    @javax.annotation.Nullable
    public String getPhone() {
        return phone;
    }


    public void setPhone(String phone) {
        this.phone = phone;
    }

    public PartnerApplication telegram(String telegram) {
        
        this.telegram = telegram;
        return this;
    }

     /**
     * Telegram account
     * @return telegram
    **/
    @javax.annotation.Nullable
    public String getTelegram() {
        return telegram;
    }


    public void setTelegram(String telegram) {
        this.telegram = telegram;
    }

    public PartnerApplication otherContact(OtherContact otherContact) {
        
        this.otherContact = otherContact;
        return this;
    }

     /**
     * Get otherContact
     * @return otherContact
    **/
    @javax.annotation.Nullable
    public OtherContact getOtherContact() {
        return otherContact;
    }


    public void setOtherContact(OtherContact otherContact) {
        this.otherContact = otherContact;
    }

    public PartnerApplication proofImagesUrlList(List<URI> proofImagesUrlList) {
        
        this.proofImagesUrlList = proofImagesUrlList;
        return this;
    }

    public PartnerApplication addProofImagesUrlListItem(URI proofImagesUrlListItem) {
        if (this.proofImagesUrlList == null) {
            this.proofImagesUrlList = new ArrayList<>();
        }
        this.proofImagesUrlList.add(proofImagesUrlListItem);
        return this;
    }

     /**
     * List of proof image URLs
     * @return proofImagesUrlList
    **/
    @javax.annotation.Nullable
    public List<URI> getProofImagesUrlList() {
        return proofImagesUrlList;
    }


    public void setProofImagesUrlList(List<URI> proofImagesUrlList) {
        this.proofImagesUrlList = proofImagesUrlList;
    }

    public PartnerApplication proofVideosUrlList(List<URI> proofVideosUrlList) {
        
        this.proofVideosUrlList = proofVideosUrlList;
        return this;
    }

    public PartnerApplication addProofVideosUrlListItem(URI proofVideosUrlListItem) {
        if (this.proofVideosUrlList == null) {
            this.proofVideosUrlList = new ArrayList<>();
        }
        this.proofVideosUrlList.add(proofVideosUrlListItem);
        return this;
    }

     /**
     * List of proof video URLs
     * @return proofVideosUrlList
    **/
    @javax.annotation.Nullable
    public List<URI> getProofVideosUrlList() {
        return proofVideosUrlList;
    }


    public void setProofVideosUrlList(List<URI> proofVideosUrlList) {
        this.proofVideosUrlList = proofVideosUrlList;
    }

    public PartnerApplication applyMsg(String applyMsg) {
        
        this.applyMsg = applyMsg;
        return this;
    }

     /**
     * Application message
     * @return applyMsg
    **/
    @javax.annotation.Nullable
    public String getApplyMsg() {
        return applyMsg;
    }


    public void setApplyMsg(String applyMsg) {
        this.applyMsg = applyMsg;
    }

    public PartnerApplication jumpUrl(String jumpUrl) {
        
        this.jumpUrl = jumpUrl;
        return this;
    }

     /**
     * Redirect URL
     * @return jumpUrl
    **/
    @javax.annotation.Nullable
    public String getJumpUrl() {
        return jumpUrl;
    }


    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartnerApplication partnerApplication = (PartnerApplication) o;
        return Objects.equals(this.id, partnerApplication.id) &&
                Objects.equals(this.uid, partnerApplication.uid) &&
                Objects.equals(this.language, partnerApplication.language) &&
                Objects.equals(this.countryId, partnerApplication.countryId) &&
                Objects.equals(this.firstname, partnerApplication.firstname) &&
                Objects.equals(this.lastname, partnerApplication.lastname) &&
                Objects.equals(this.email, partnerApplication.email) &&
                Objects.equals(this.joinUid, partnerApplication.joinUid) &&
                Objects.equals(this.joinCountryId, partnerApplication.joinCountryId) &&
                Objects.equals(this.identityComment, partnerApplication.identityComment) &&
                Objects.equals(this.promotionChannels, partnerApplication.promotionChannels) &&
                Objects.equals(this.contactDetails, partnerApplication.contactDetails) &&
                Objects.equals(this.knowDetails, partnerApplication.knowDetails) &&
                Objects.equals(this.questionLang, partnerApplication.questionLang) &&
                Objects.equals(this.createTimest, partnerApplication.createTimest) &&
                Objects.equals(this.updateTimest, partnerApplication.updateTimest) &&
                Objects.equals(this.applyType, partnerApplication.applyType) &&
                Objects.equals(this.auditStatus, partnerApplication.auditStatus) &&
                Objects.equals(this.editCounts, partnerApplication.editCounts) &&
                Objects.equals(this.proofImages, partnerApplication.proofImages) &&
                Objects.equals(this.proofVideos, partnerApplication.proofVideos) &&
                Objects.equals(this.proofUrl, partnerApplication.proofUrl) &&
                Objects.equals(this.auditReason, partnerApplication.auditReason) &&
                Objects.equals(this.channelType, partnerApplication.channelType) &&
                Objects.equals(this.region, partnerApplication.region) &&
                Objects.equals(this.phone, partnerApplication.phone) &&
                Objects.equals(this.telegram, partnerApplication.telegram) &&
                Objects.equals(this.otherContact, partnerApplication.otherContact) &&
                Objects.equals(this.proofImagesUrlList, partnerApplication.proofImagesUrlList) &&
                Objects.equals(this.proofVideosUrlList, partnerApplication.proofVideosUrlList) &&
                Objects.equals(this.applyMsg, partnerApplication.applyMsg) &&
                Objects.equals(this.jumpUrl, partnerApplication.jumpUrl);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, uid, language, countryId, firstname, lastname, email, joinUid, joinCountryId, identityComment, promotionChannels, contactDetails, knowDetails, questionLang, createTimest, updateTimest, applyType, auditStatus, editCounts, proofImages, proofVideos, proofUrl, auditReason, channelType, region, phone, telegram, otherContact, proofImagesUrlList, proofVideosUrlList, applyMsg, jumpUrl);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PartnerApplication {\n");
        sb.append("      id: ").append(toIndentedString(id)).append("\n");
        sb.append("      uid: ").append(toIndentedString(uid)).append("\n");
        sb.append("      language: ").append(toIndentedString(language)).append("\n");
        sb.append("      countryId: ").append(toIndentedString(countryId)).append("\n");
        sb.append("      firstname: ").append(toIndentedString(firstname)).append("\n");
        sb.append("      lastname: ").append(toIndentedString(lastname)).append("\n");
        sb.append("      email: ").append(toIndentedString(email)).append("\n");
        sb.append("      joinUid: ").append(toIndentedString(joinUid)).append("\n");
        sb.append("      joinCountryId: ").append(toIndentedString(joinCountryId)).append("\n");
        sb.append("      identityComment: ").append(toIndentedString(identityComment)).append("\n");
        sb.append("      promotionChannels: ").append(toIndentedString(promotionChannels)).append("\n");
        sb.append("      contactDetails: ").append(toIndentedString(contactDetails)).append("\n");
        sb.append("      knowDetails: ").append(toIndentedString(knowDetails)).append("\n");
        sb.append("      questionLang: ").append(toIndentedString(questionLang)).append("\n");
        sb.append("      createTimest: ").append(toIndentedString(createTimest)).append("\n");
        sb.append("      updateTimest: ").append(toIndentedString(updateTimest)).append("\n");
        sb.append("      applyType: ").append(toIndentedString(applyType)).append("\n");
        sb.append("      auditStatus: ").append(toIndentedString(auditStatus)).append("\n");
        sb.append("      editCounts: ").append(toIndentedString(editCounts)).append("\n");
        sb.append("      proofImages: ").append(toIndentedString(proofImages)).append("\n");
        sb.append("      proofVideos: ").append(toIndentedString(proofVideos)).append("\n");
        sb.append("      proofUrl: ").append(toIndentedString(proofUrl)).append("\n");
        sb.append("      auditReason: ").append(toIndentedString(auditReason)).append("\n");
        sb.append("      channelType: ").append(toIndentedString(channelType)).append("\n");
        sb.append("      region: ").append(toIndentedString(region)).append("\n");
        sb.append("      phone: ").append(toIndentedString(phone)).append("\n");
        sb.append("      telegram: ").append(toIndentedString(telegram)).append("\n");
        sb.append("      otherContact: ").append(toIndentedString(otherContact)).append("\n");
        sb.append("      proofImagesUrlList: ").append(toIndentedString(proofImagesUrlList)).append("\n");
        sb.append("      proofVideosUrlList: ").append(toIndentedString(proofVideosUrlList)).append("\n");
        sb.append("      applyMsg: ").append(toIndentedString(applyMsg)).append("\n");
        sb.append("      jumpUrl: ").append(toIndentedString(jumpUrl)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

