/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Recommend
 */
public class Recommend {
    public static final String SERIALIZED_NAME_BALANCE = "balance";
    @SerializedName(SERIALIZED_NAME_BALANCE)
    private Map<String, String> balance = new HashMap<>();

    public static final String SERIALIZED_NAME_BTC_FAITH = "btc_faith";
    @SerializedName(SERIALIZED_NAME_BTC_FAITH)
    private Map<String, String> btcFaith = new HashMap<>();

    public static final String SERIALIZED_NAME_CONSERVATIVE = "conservative";
    @SerializedName(SERIALIZED_NAME_CONSERVATIVE)
    private Map<String, String> conservative = new HashMap<>();

    public static final String SERIALIZED_NAME_GT_FAITH = "gt_faith";
    @SerializedName(SERIALIZED_NAME_GT_FAITH)
    private Map<String, String> gtFaith = new HashMap<>();


    public Recommend balance(Map<String, String> balance) {
        
        this.balance = balance;
        return this;
    }

    public Recommend putBalanceItem(String key, String balanceItem) {
        this.balance.put(key, balanceItem);
        return this;
    }

     /**
     * 字符串键到字符串值的映射，对应 Go 的 map[string]string。
     * @return balance
    **/
    public Map<String, String> getBalance() {
        return balance;
    }


    public void setBalance(Map<String, String> balance) {
        this.balance = balance;
    }

    public Recommend btcFaith(Map<String, String> btcFaith) {
        
        this.btcFaith = btcFaith;
        return this;
    }

    public Recommend putBtcFaithItem(String key, String btcFaithItem) {
        this.btcFaith.put(key, btcFaithItem);
        return this;
    }

     /**
     * 字符串键到字符串值的映射，对应 Go 的 map[string]string。
     * @return btcFaith
    **/
    public Map<String, String> getBtcFaith() {
        return btcFaith;
    }


    public void setBtcFaith(Map<String, String> btcFaith) {
        this.btcFaith = btcFaith;
    }

    public Recommend conservative(Map<String, String> conservative) {
        
        this.conservative = conservative;
        return this;
    }

    public Recommend putConservativeItem(String key, String conservativeItem) {
        this.conservative.put(key, conservativeItem);
        return this;
    }

     /**
     * 字符串键到字符串值的映射，对应 Go 的 map[string]string。
     * @return conservative
    **/
    public Map<String, String> getConservative() {
        return conservative;
    }


    public void setConservative(Map<String, String> conservative) {
        this.conservative = conservative;
    }

    public Recommend gtFaith(Map<String, String> gtFaith) {
        
        this.gtFaith = gtFaith;
        return this;
    }

    public Recommend putGtFaithItem(String key, String gtFaithItem) {
        this.gtFaith.put(key, gtFaithItem);
        return this;
    }

     /**
     * 字符串键到字符串值的映射，对应 Go 的 map[string]string。
     * @return gtFaith
    **/
    public Map<String, String> getGtFaith() {
        return gtFaith;
    }


    public void setGtFaith(Map<String, String> gtFaith) {
        this.gtFaith = gtFaith;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Recommend recommend = (Recommend) o;
        return Objects.equals(this.balance, recommend.balance) &&
                Objects.equals(this.btcFaith, recommend.btcFaith) &&
                Objects.equals(this.conservative, recommend.conservative) &&
                Objects.equals(this.gtFaith, recommend.gtFaith);
    }

    @Override
    public int hashCode() {
        return Objects.hash(balance, btcFaith, conservative, gtFaith);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Recommend {\n");
        sb.append("      balance: ").append(toIndentedString(balance)).append("\n");
        sb.append("      btcFaith: ").append(toIndentedString(btcFaith)).append("\n");
        sb.append("      conservative: ").append(toIndentedString(conservative)).append("\n");
        sb.append("      gtFaith: ").append(toIndentedString(gtFaith)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

