/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * 资金转入转出请求体
 */
public class TradFiTransactionRequest {
    public static final String SERIALIZED_NAME_ASSET = "asset";
    @SerializedName(SERIALIZED_NAME_ASSET)
    private String asset;

    public static final String SERIALIZED_NAME_CHANGE = "change";
    @SerializedName(SERIALIZED_NAME_CHANGE)
    private String change;

    /**
     * Transaction Type (deposit - transfer in, withdraw - transfer out)
     */
    @JsonAdapter(TypeEnum.Adapter.class)
    public enum TypeEnum {
        DEPOSIT("deposit"),
        
        WITHDRAW("withdraw");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<TypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public TypeEnum read(final JsonReader jsonReader) throws IOException {
                String value =  jsonReader.nextString();
                return TypeEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    private TypeEnum type;


    public TradFiTransactionRequest asset(String asset) {
        
        this.asset = asset;
        return this;
    }

     /**
     * Asset type, e.g., USDT, currently only USDT is supported
     * @return asset
    **/
    public String getAsset() {
        return asset;
    }


    public void setAsset(String asset) {
        this.asset = asset;
    }

    public TradFiTransactionRequest change(String change) {
        
        this.change = change;
        return this;
    }

     /**
     * Change Quantity, supports up to two decimal places
     * @return change
    **/
    public String getChange() {
        return change;
    }


    public void setChange(String change) {
        this.change = change;
    }

    public TradFiTransactionRequest type(TypeEnum type) {
        
        this.type = type;
        return this;
    }

     /**
     * Transaction Type (deposit - transfer in, withdraw - transfer out)
     * @return type
    **/
    public TypeEnum getType() {
        return type;
    }


    public void setType(TypeEnum type) {
        this.type = type;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TradFiTransactionRequest tradFiTransactionRequest = (TradFiTransactionRequest) o;
        return Objects.equals(this.asset, tradFiTransactionRequest.asset) &&
                Objects.equals(this.change, tradFiTransactionRequest.change) &&
                Objects.equals(this.type, tradFiTransactionRequest.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(asset, change, type);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TradFiTransactionRequest {\n");
        sb.append("      asset: ").append(toIndentedString(asset)).append("\n");
        sb.append("      change: ").append(toIndentedString(change)).append("\n");
        sb.append("      type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

