/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Upload chat file request
 */
public class UploadChatFile {
    /**
     * File MIME type: supports &#x60;image/jpeg&#x60;, &#x60;image/jpg&#x60;, &#x60;image/png&#x60;, &#x60;video/mp4&#x60;.
     */
    @JsonAdapter(ImageContentTypeEnum.Adapter.class)
    public enum ImageContentTypeEnum {
        IMAGE_JPEG("image/jpeg"),
        
        IMAGE_JPG("image/jpg"),
        
        IMAGE_PNG("image/png"),
        
        VIDEO_MP4("video/mp4");

        private String value;

        ImageContentTypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static ImageContentTypeEnum fromValue(String value) {
            for (ImageContentTypeEnum b : ImageContentTypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<ImageContentTypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final ImageContentTypeEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public ImageContentTypeEnum read(final JsonReader jsonReader) throws IOException {
                String value =  jsonReader.nextString();
                return ImageContentTypeEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_IMAGE_CONTENT_TYPE = "image_content_type";
    @SerializedName(SERIALIZED_NAME_IMAGE_CONTENT_TYPE)
    private ImageContentTypeEnum imageContentType;

    public static final String SERIALIZED_NAME_BASE64_IMG = "base64_img";
    @SerializedName(SERIALIZED_NAME_BASE64_IMG)
    private String base64Img;


    public UploadChatFile imageContentType(ImageContentTypeEnum imageContentType) {
        
        this.imageContentType = imageContentType;
        return this;
    }

     /**
     * File MIME type: supports &#x60;image/jpeg&#x60;, &#x60;image/jpg&#x60;, &#x60;image/png&#x60;, &#x60;video/mp4&#x60;.
     * @return imageContentType
    **/
    public ImageContentTypeEnum getImageContentType() {
        return imageContentType;
    }


    public void setImageContentType(ImageContentTypeEnum imageContentType) {
        this.imageContentType = imageContentType;
    }

    public UploadChatFile base64Img(String base64Img) {
        
        this.base64Img = base64Img;
        return this;
    }

     /**
     * Base64 file content; max 20 MB.
     * @return base64Img
    **/
    public String getBase64Img() {
        return base64Img;
    }


    public void setBase64Img(String base64Img) {
        this.base64Img = base64Img;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UploadChatFile uploadChatFile = (UploadChatFile) o;
        return Objects.equals(this.imageContentType, uploadChatFile.imageContentType) &&
                Objects.equals(this.base64Img, uploadChatFile.base64Img);
    }

    @Override
    public int hashCode() {
        return Objects.hash(imageContentType, base64Img);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UploadChatFile {\n");
        sb.append("      imageContentType: ").append(toIndentedString(imageContentType)).append("\n");
        sb.append("      base64Img: ").append(toIndentedString(base64Img)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

